"""IL-level instrumentation for --mem-safe (the C tier).

The macro tier in runtime/crust_memsafe.h only checks accesses the programmer
wrote the macros around, which is right for generated C but useless for a
directory full of hand-written .c files. This pass gets the same checks without
touching the source: it rewrites the IL after `make_il`, inserting a call to
the shadow-table runtime before every dereference and redirecting the allocator
calls to the tracking wrappers.

Running on the IL rather than the source is what makes it complete. Every way C
has of reaching memory -- `*p`, `a[i]`, `s->field`, a compound assignment's
implicit read-modify-write, a dereference buried in a macro expansion -- has
already been lowered to the same handful of commands by the time this pass
sees it, so there is one place to instrument instead of a dozen syntactic
forms to chase.

Two things make this possible and are worth knowing:

*Positions.* IL commands carry source ranges (`ILCommand.r`), so an inserted
check reports the same `file:line` a hand-written macro does. Without that this
pass could only say which function was at fault.

*Direct calls.* A `Call` whose `direct_name` is set never materializes its
function pointer -- `Call.inputs()` omits it and the back ends emit `call
<name>` straight from the name. So a callee can be synthesized here from
nothing but a ctype, without being declared in the translation unit or entered
in the symbol table. `--auto-free` predates this trick and has to scavenge an
existing `free` reference out of the IL, which is why it silently does nothing
in a unit that never frees anything.
"""

import shivyc.ctypes as ctypes
import shivyc.il_cmds.control as control_cmds
import shivyc.il_cmds.math as math_cmds
import shivyc.il_cmds.value as value_cmds

from shivyc.ctypes import FunctionCType, PointerCType
from shivyc.il_gen import ILValue


# Allocator name -> (runtime replacement, index of the size-ish args to keep).
# The wrappers take the original arguments followed by (file, line, func), so
# only the name and the trailing site arguments differ.
_ALLOC_MAP = {
    "malloc": "crust_ms_malloc",
    "calloc": "crust_ms_calloc",
    "realloc": "crust_ms_realloc",
}
_FREE_MAP = {
    "free": "crust_ms_free",
}

# The macro tier's check entry points. When source already expanded the
# CRUST_MS_* macros -- C generated by `cpprust.py --mem-safe`, most importantly
# -- the access it guards must not be checked a second time here, or every bug
# is reported twice.
_MACRO_CHECKS = frozenset([
    "crust_ms_check_read", "crust_ms_check_write",
])
_MACRO_CHECKED_WR = "crust_ms_checked_wr"

# The runtime's own entry points, so instrumentation never instruments itself.
_RUNTIME_FUNCS = frozenset([
    "crust_ms_il_read", "crust_ms_il_write", "crust_ms_il_escape",
    "crust_ms_malloc", "crust_ms_calloc", "crust_ms_realloc", "crust_ms_free",
    "crust_ms_check_read", "crust_ms_check_write", "crust_ms_checked_wr",
    "crust_ms_register", "crust_ms_unregister", "crust_ms_mark_init",
    "crust_ms_stack", "crust_ms_stack_end", "crust_ms_global",
])


class _Builder:
    """Makes the ILValues an inserted call needs.

    String literals are interned per translation unit: a file name repeated at
    every check would otherwise emit one copy of the string per access, which
    on a large file is a great deal of .rodata for no benefit.
    """

    def __init__(self, il_code):
        self.il = il_code
        self._strs = {}
        self._ints = {}

    def string(self, text):
        """The array ILValue for a string literal (interned per TU)."""
        if text in self._strs:
            return self._strs[text]
        chars = [ord(ch) for ch in text] + [0]
        val = ILValue(ctypes.ArrayCType(ctypes.char, len(chars)))
        self.il.register_string_literal(val, chars)
        self._strs[text] = val
        return val

    def string_ptr(self, text, out):
        """A char* to `text`, appending the AddrOf that produces it to `out`.

        A string literal's ILValue has array type, and an array does not decay
        on its own down here -- passing one straight to a call hands the back
        end a value whose width is the length of the string, which is not a
        register size. The front end decays through AddrOf and so does this.

        Emitted immediately before each use rather than once per function: a
        single hoisted definition would be skipped by any branch that jumps
        over it, and the address of a static string is a `lea` that the
        optimizer is welcome to fold back together.
        """
        arr = self.string(text)
        ptr = ILValue(PointerCType(ctypes.char))
        out.append(value_cmds.AddrOf(ptr, arr))
        return ptr

    def integer(self, n, ctype):
        """An ILValue holding the integer literal `n`."""
        key = (n, id(ctype))
        if key in self._ints:
            return self._ints[key]
        val = ILValue(ctype)
        self.il.register_literal_var(val, n)
        self._ints[key] = val
        return val

    def callee(self, name, arg_types, ret=None):
        """A function ILValue for `name`, synthesized rather than declared.

        Only the ctype is ever consulted: Call reads `func.ctype.arg.ret` to
        decide whether the result is used, and the back ends take the symbol
        from direct_name. Nothing here has to exist in the symbol table.
        """
        ret = ret if ret is not None else ctypes.void
        ftype = FunctionCType(list(arg_types), ret, False)
        return ILValue(PointerCType(ftype))


def _site_file(r):
    if r is not None and getattr(r, "start", None) is not None:
        return r.start.file
    return "<generated>"


def _site_line(r):
    if r is not None and getattr(r, "start", None) is not None:
        return r.start.line
    return 0


def _site_args(builder, cmd, func_name, out):
    """The (file, line, func) triple every runtime entry point ends with.

    Appends to `out` the commands needed to materialize the two strings.
    """
    r = cmd.r
    if r is not None and getattr(r, "start", None) is not None:
        path = r.start.file
        line = r.start.line
    else:
        # A command with no range is one a previous pass synthesized. Naming
        # the function is still better than dropping the check.
        path = "<generated>"
        line = 0
    return [builder.string_ptr(path, out),
            builder.integer(line, ctypes.integer),
            builder.string_ptr(func_name, out)]


def _char_ptr():
    return PointerCType(ctypes.char)


def _void_ptr():
    return PointerCType(ctypes.void)


def _access_size(cmd):
    """Bytes touched by an access, or None when it cannot be determined.

    A read names the size through its output's type and a write through the
    value being stored; the pointer's own pointee type is not reliable, since
    the front end freely casts pointers to char* while lowering.
    """
    if isinstance(cmd, (value_cmds.ReadAt, value_cmds.ReadRel)):
        ct = cmd.output.ctype
    else:
        ct = cmd.val.ctype
    size = getattr(ct, "size", None)
    if not isinstance(size, int) or size <= 0:
        return None
    return size


def _rel_address(builder, cmd, out):
    """Materialize the address a ReadRel/SetRel touches: `&base + chunk*count`.

    The relative forms never compute their address as a value -- the back end
    folds base, chunk and count straight into an addressing mode -- so there is
    no pointer to hand the checker. It has to be built here. This is the shape
    every access to a local array takes, which is why stack arrays went
    unchecked while heap ones did not: `p[i]` through a pointer lowers to
    ReadAt, but `buf[i]` on an array object lowers to ReadRel.
    """
    ptr = ILValue(PointerCType(ctypes.char))
    addr_cmd = value_cmds.AddrOf(ptr, cmd.base)
    addr_cmd.r = cmd.r
    out.append(addr_cmd)

    if cmd.count is None:
        if not cmd.chunk:
            return ptr
        off = builder.integer(cmd.chunk, ctypes.unsig_longint)
    else:
        off = ILValue(ctypes.unsig_longint)
        mul = math_cmds.Mult(
            off, cmd.count, builder.integer(cmd.chunk, ctypes.unsig_longint))
        mul.r = cmd.r
        out.append(mul)

    total = ILValue(PointerCType(ctypes.char))
    add = math_cmds.Add(total, ptr, off)
    add.r = cmd.r
    out.append(add)
    return total


def _check_call(builder, cmd, func_name, writing, out):
    """Append to `out` the runtime check that guards `cmd`.

    Returns True when a check was emitted.
    """
    size = _access_size(cmd)
    if size is None:
        return False
    name = "crust_ms_il_write" if writing else "crust_ms_il_read"
    arg_types = [_void_ptr(), ctypes.unsig_longint, _char_ptr(),
                 ctypes.integer, _char_ptr()]
    callee = builder.callee(name, arg_types)
    if isinstance(cmd, (value_cmds.ReadRel, value_cmds.SetRel)):
        addr = _rel_address(builder, cmd, out)
    else:
        addr = cmd.addr
    args = ([addr, builder.integer(size, ctypes.unsig_longint)]
            + _site_args(builder, cmd, func_name, out))
    call = control_cmds.Call(callee, args, None)
    call.direct_name = name
    # Inherit the position of the access being checked, so a diagnostic raised
    # about the inserted call points at the user's code rather than nowhere.
    call.r = cmd.r
    for c in out[len(out) - 2:]:
        c.r = cmd.r
    out.append(call)
    return True


# Suffixes the C++ tier treats as its own. A `.cpp` is lowered to C by
# tools/cpprust.py and spliced into the same translation unit as the
# hand-written C that included it, so the file name on a command's source
# range is what separates the two -- there is nothing else left by then.
_CPP_SUFFIXES = (".cpp", ".cc", ".cxx", ".c++", ".hpp", ".hh", ".hxx")


def _is_cpp_range(r):
    """True when this position came from C++ source rather than C."""
    if r is None or getattr(r, "start", None) is None:
        return False
    path = r.start.file
    if not path:
        return False
    low = path.lower()
    for suf in _CPP_SUFFIXES:
        if low.endswith(suf):
            return True
    return False


def _stack_objects(cmds, symbol_table, il_code):
    """Frame objects a checked access can reach, in first-use order.

    Returns (ILValue, size, name, track_definedness) per object.

    Definedness is tracked only for arrays, and the reason is specific: the
    runtime learns a byte is defined from an instrumented write, and only an
    array has all its writes go through one. An array element is written by
    SetRel or SetAt; a scalar or a struct is assigned wholesale by Set, and a
    parameter arrives via LoadArg -- neither is a memory access, neither is
    instrumented, and neither ever will be. Registering those as
    uninitialized reported a false uninitialized read on the first use of
    every by-value parameter.
    """
    storage = getattr(symbol_table, "storage", {})
    names = getattr(symbol_table, "names", {})
    static = getattr(symbol_table, "STATIC", 1)
    literals = getattr(il_code, "string_literals", {})

    seen = []
    found = set()
    for c in cmds:
        # Two ways a local becomes reachable through an address. AddrOf is the
        # obvious one. The relative forms are the one that matters for arrays:
        # `buf[i]` names the array object directly as ReadRel's base and never
        # takes its address at all, so collecting only AddrOf found the format
        # string and missed the buffer.
        if isinstance(c, value_cmds.AddrOf):
            var = c.var
        elif isinstance(c, (value_cmds.ReadRel, value_cmds.SetRel)):
            var = c.base
        else:
            continue
        if id(var) in found:
            continue
        if storage.get(var) == static:
            continue          # a global lives for the whole program, not a frame
        if var in literals or getattr(var, "literal", None) is not None:
            # String literals live in .rodata and are never declared, so they
            # are absent from the storage map and slip past the check above.
            # Registering one as a frame object put a bogus region in the
            # table, and the underflow search then blamed it for reads of the
            # genuinely static data sitting next to it.
            continue
        ct = getattr(var, "ctype", None)
        size = getattr(ct, "size", None)
        if not isinstance(size, int) or size <= 0:
            continue
        if ct is not None and ct.is_function():
            continue
        found.add(id(var))
        is_array = ct is not None and ct.is_array()
        seen.append((var, size, names.get(var, "local"), is_array))
    return seen


def _global_objects(cmds, symbol_table, il_code):
    """Static objects in this TU a checked access can reach.

    Same collection as the frame objects, with the storage test inverted.
    Globals are always registered as defined: C zero-initializes anything
    without an initializer, so there is no such thing as an uninitialized
    global to find.
    """
    storage = getattr(symbol_table, "storage", {})
    names = getattr(symbol_table, "names", {})
    static = getattr(symbol_table, "STATIC", 1)
    literals = getattr(il_code, "string_literals", {})

    seen = []
    found = set()
    for c in cmds:
        if isinstance(c, value_cmds.AddrOf):
            var = c.var
        elif isinstance(c, (value_cmds.ReadRel, value_cmds.SetRel)):
            var = c.base
        else:
            continue
        if id(var) in found or storage.get(var) != static:
            continue
        if var in literals or getattr(var, "literal", None) is not None:
            continue
        ct = getattr(var, "ctype", None)
        size = getattr(ct, "size", None)
        if not isinstance(size, int) or size <= 0:
            continue
        if ct is not None and ct.is_function():
            continue
        found.add(id(var))
        seen.append((var, size, names.get(var, "global")))
    return seen


def _register_global(builder, var, size, name, r, out):
    """Emit the AddrOf + crust_ms_global pair for one static object."""
    ptr = ILValue(PointerCType(ctypes.char))
    addr = value_cmds.AddrOf(ptr, var)
    addr.r = r
    out.append(addr)
    name_ptr = builder.string_ptr(name, out)
    file_ptr = builder.string_ptr(_site_file(r), out)
    for c in out[len(out) - 2:]:
        c.r = r
    args = [ptr, builder.integer(size, ctypes.unsig_longint), name_ptr,
            file_ptr, builder.integer(_site_line(r), ctypes.integer)]
    arg_types = [_void_ptr(), ctypes.unsig_longint, _char_ptr(),
                 _char_ptr(), ctypes.integer]
    call = control_cmds.Call(
        builder.callee("crust_ms_global", arg_types), args, None)
    call.direct_name = "crust_ms_global"
    call.r = r
    out.append(call)


def _prologue_end(cmds):
    """Index just past the prologue.

    Registration cannot be emitted before it. LoadArg reads the argument
    registers and VaSaveBase reads r11, while a Call clobbers every
    caller-saved register -- inserting above them hands the callee's own
    arguments to the runtime and loses the real ones.
    """
    # Every command that consumes an incoming argument, not just LoadArg.
    # LoadStructArg is the one that bit: a function taking a struct by value
    # begins with it and no LoadArg at all, so a scan that knew only LoadArg
    # stopped at index 0 and put the registration call *above* the argument
    # load. The call clobbered the argument registers and the function ran on
    # garbage.
    prologue = (value_cmds.LoadArg, value_cmds.LoadStructArg,
                value_cmds.VaSaveBase)
    i = 0
    last = 0
    while i < len(cmds):
        c = cmds[i]
        if isinstance(c, prologue) or hasattr(c, "arg_num"):
            last = i + 1
        elif isinstance(c, (control_cmds.Label, control_cmds.Jump,
                            control_cmds._GeneralJump, control_cmds.Return)):
            break            # past the entry block; nothing more is prologue
        i += 1
        if i - last > 24:
            break            # far enough in that no argument load remains
    return last


def _register_stack(builder, var, size, name, defined, fn, r, out):
    """Emit the AddrOf + crust_ms_register pair for one local."""
    ptr = ILValue(PointerCType(ctypes.char))
    addr = value_cmds.AddrOf(ptr, var)
    addr.r = r
    out.append(addr)

    name_ptr = builder.string_ptr(name, out)
    file_ptr = builder.string_ptr(_site_file(r), out)
    for c in out[len(out) - 2:]:
        c.r = r
    args = [ptr,
            builder.integer(size, ctypes.unsig_longint),
            builder.integer(1 if defined else 0, ctypes.integer),
            name_ptr,
            file_ptr,
            builder.integer(_site_line(r), ctypes.integer)]
    arg_types = [_void_ptr(), ctypes.unsig_longint, ctypes.integer,
                 _char_ptr(), _char_ptr(), ctypes.integer]
    call = control_cmds.Call(
        builder.callee("crust_ms_stack", arg_types), args, None)
    call.direct_name = "crust_ms_stack"
    call.r = r
    out.append(call)
    return ptr


def _unregister_stack(builder, var, fn, r, out):
    """Emit the AddrOf + crust_ms_unregister pair for one local.

    A fresh AddrOf rather than reusing the one from entry: the frame slot's
    address is a constant offset from the frame pointer, so recomputing it is
    a `lea`, and keeping the entry value live across the whole function would
    pin a register for nothing.
    """
    ptr = ILValue(PointerCType(ctypes.char))
    addr = value_cmds.AddrOf(ptr, var)
    addr.r = r
    out.append(addr)
    file_ptr = builder.string_ptr(_site_file(r), out)
    out[len(out) - 1].r = r
    args = [ptr, file_ptr, builder.integer(_site_line(r), ctypes.integer)]
    arg_types = [_void_ptr(), _char_ptr(), ctypes.integer]
    call = control_cmds.Call(
        builder.callee("crust_ms_stack_end", arg_types), args, None)
    call.direct_name = "crust_ms_stack_end"
    call.r = r
    out.append(call)


class _Fake:
    """Carries a range for _site_args when there is no command to point at."""

    def __init__(self, r):
        self.r = r


def _hoisted_mark(builder, base, off, span, r, out):
    """One `crust_ms_mark_init` covering everything a proved loop writes."""
    addr = base
    if off:
        shifted = ILValue(PointerCType(ctypes.char))
        add = math_cmds.Add(shifted, base,
                            builder.integer(off, ctypes.unsig_longint))
        add.r = r
        out.append(add)
        addr = shifted
    name = "crust_ms_mark_init"
    callee = builder.callee(name, [_void_ptr(), ctypes.unsig_longint])
    call = control_cmds.Call(
        callee, [addr, builder.integer(span, ctypes.unsig_longint)], None)
    call.direct_name = name
    call.r = r
    out.append(call)


def _mark_init_call(builder, cmd, out):
    """Emit `crust_ms_mark_init(addr, n)` in place of a proved write check."""
    size = _access_size(cmd)
    if size is None:
        return
    if isinstance(cmd, (value_cmds.ReadRel, value_cmds.SetRel)):
        addr = _rel_address(builder, cmd, out)
    else:
        addr = cmd.addr
    name = "crust_ms_mark_init"
    callee = builder.callee(name, [_void_ptr(), ctypes.unsig_longint])
    call = control_cmds.Call(
        callee, [addr, builder.integer(size, ctypes.unsig_longint)], None)
    call.direct_name = name
    call.r = cmd.r
    out.append(call)


def _rewrite_alloc(builder, cmd, func_name, out):
    """Redirect an allocator/deallocator call to its tracking wrapper.

    Rewritten in place rather than wrapped: the runtime has to see the *real*
    malloc return value to record the region, and it has to intercept free
    rather than merely observe it, so that a double free is reported instead of
    being passed to libc a second time.
    """
    name = cmd.direct_name
    repl = _ALLOC_MAP.get(name) or _FREE_MAP.get(name)
    if repl is None:
        return False
    site = _site_args(builder, cmd, func_name, out)
    for c in out[len(out) - 2:]:
        c.r = cmd.r
    cmd.args = list(cmd.args) + site
    cmd.direct_name = repl
    # The synthesized ctype has to keep the original return type: Call caches
    # void_return at construction, and the back ends decide whether to move
    # RAX into `ret` from that.
    ret = cmd.func.ctype.arg.ret
    arg_types = [a.ctype for a in cmd.args]
    cmd.func = builder.callee(repl, arg_types, ret)
    cmd.void_return = ret.is_void()
    return True


def _already_macro_instrumented(il_code, symbol_table):
    """True when this TU's source expanded the CRUST_MS_* check macros."""
    import shivyc.stackless as stackless
    for fn in list(il_code.commands):
        cmds = stackless._apply_direct_calls(il_code.commands[fn],
                                             symbol_table)
        il_code.commands[fn] = cmds
        for c in cmds:
            if (isinstance(c, control_cmds.Call)
                    and c.direct_name in _MACRO_CHECKS
                    or (isinstance(c, control_cmds.Call)
                        and c.direct_name == _MACRO_CHECKED_WR)):
                return True
    return False


def _escape_calls(builder, cmd, local_funcs, out):
    """Tell the runtime about pointers handed to uninstrumented code.

    Emitted only for callees not defined in this translation unit. A call to a
    function compiled alongside this one needs nothing: its own writes are
    instrumented, so the shadow already saw them, and staying quiet there keeps
    full uninitialized-read detection everywhere except at the boundary with
    code the flag does not reach.

    Returns the number of hooks emitted.
    """
    name = cmd.direct_name
    if name in local_funcs or name in _ALLOC_MAP or name in _FREE_MAP:
        return 0
    if name in _RUNTIME_FUNCS:
        return 0
    n = 0
    for arg in cmd.args:
        ct = arg.ctype
        if not (ct.is_pointer() if hasattr(ct, "is_pointer") else False):
            continue
        callee = builder.callee("crust_ms_il_escape", [_void_ptr()])
        call = control_cmds.Call(callee, [arg], None)
        call.direct_name = "crust_ms_il_escape"
        call.r = cmd.r
        out.append(call)
        n += 1
    return n


def instrument(il_code, symbol_table, args=None):
    """Insert runtime memory-safety checks into every function's IL.

    Returns (checks inserted, allocator calls redirected, checks elided).
    """
    import shivyc.stackless as stackless

    builder = _Builder(il_code)
    checks = 0
    allocs = 0
    local_funcs = frozenset(il_code.commands)
    n_stack = 0
    n_global = 0
    track_stack = not getattr(args, "mem_safe_no_stack", False)
    cpp_only = getattr(args, "mem_safe", None) == "cpp"
    # A global has no single entry point the way a frame does, so registration
    # goes wherever it is certain to run before any access. `main` is that
    # place when this unit defines it; otherwise every function in the unit
    # gets the call and the runtime discards the repeats. The idempotent path
    # is a hash lookup per global per call, which is why `main` is preferred
    # when it is available.
    has_main = "main" in il_code.commands

    # Collected across the whole unit, not per function. A global is usually
    # touched somewhere other than where it is registered -- `main` calls the
    # functions that use it and may never name it itself -- so scanning only
    # the function being instrumented found nothing at all.
    all_globals = []
    if track_stack:
        seen_g = set()
        for _fn in list(il_code.commands):
            for entry in _global_objects(il_code.commands[_fn], symbol_table,
                                         il_code):
                if id(entry[0]) not in seen_g:
                    seen_g.add(id(entry[0]))
                    all_globals.append(entry)

    # A translation unit that already carries macro checks was instrumented by
    # the C++ tier (`cpprust.py --mem-safe`), and re-checking every access here
    # would run two checks per dereference for one bug. Tiers are chosen per
    # translation unit, so this one defers.
    #
    # Matching the guarded access individually was the first attempt and does
    # not work: the macro casts its pointer to `const void *` before the call,
    # so the value passed to the check and the value dereferenced afterwards
    # are different ILValues.
    if _already_macro_instrumented(il_code, symbol_table):
        return 0, 0, 0, 0, 0, 0, 0

    # Ask the whole-program analysis which accesses need no check. This is the
    # part Fil-C has no way to do: its capability test is per-pointer at run
    # time, so it pays for every dereference whether or not the answer was
    # knowable in advance.
    elide = {}
    marks = {}
    hoists = {}
    n_elided = 0
    n_marked = 0
    n_hoisted = 0
    if not getattr(args, "mem_safe_no_elide", False):
        try:
            import shivyc.memsafe_elide as memsafe_elide
            (elide, marks, hoists, n_red, n_bnd, n_rng,
             n_hoi) = memsafe_elide.safe_accesses(il_code, symbol_table)
            n_elided = n_red
            n_marked = n_bnd
            n_hoisted = n_hoi
        except Exception:
            # Elision is an optimization; instrumenting everything is always
            # a correct answer. Falling back keeps a checked build possible
            # even if the analysis trips over something.
            elide = {}
            marks = {}
            hoists = {}
            n_elided = 0
            n_marked = 0
            n_hoisted = 0

    for fn in list(il_code.commands):
        skip = elide.get(fn, frozenset())
        mark_only = marks.get(fn, frozenset())
        # Insert index -> the whole-loop shadow updates to emit there.
        loop_marks = {}
        for at, base, off, span, r in hoists.get(fn, []):
            loop_marks.setdefault(at, []).append((base, off, span, r))
        # `direct_name` is what identifies a callee by name, and it is set by
        # the stackless pass, which runs after this one -- until it does, a
        # call to malloc is an indirect call through an AddrOf. Resolve names
        # here so allocator calls are recognizable; the result is written back,
        # so the later pass finds the work already done rather than repeating
        # it. This is the same thing --check-memory does to see the call graph.
        cmds = stackless._apply_direct_calls(il_code.commands[fn],
                                             symbol_table)
        il_code.commands[fn] = cmds
        out = []
        # Stack objects are registered once at entry and retired at every
        # exit, rather than at each AddrOf: a frame slot's address is fixed
        # for the call, and re-registering inside a loop would churn the
        # region table for no new information. Retiring at exit is what turns
        # a returned pointer to a local into a reported use-after-scope
        # instead of silence.
        # Under the C++ tier only C++ frames are registered. Registration is a
        # call per invocation, and paying it in a C function would break the
        # promise that verified C keeps running at full speed. The cost is
        # that a C-owned local passed into C++ is not bounds-checked there.
        cpp_fn = (not cpp_only) or (cmds and _is_cpp_range(cmds[0].r))
        locals_ = (_stack_objects(cmds, symbol_table, il_code)
                   if (track_stack and cpp_fn) else [])
        globals_ = all_globals if (not has_main or fn == "main") else []
        prologue = _prologue_end(cmds)
        entry_r = cmds[0].r if cmds else None

        for idx in range(len(cmds)):
            cmd = cmds[idx]

            if idx in loop_marks:
                for base, off, span, r in loop_marks[idx]:
                    _hoisted_mark(builder, base, off, span, r, out)

            if idx == prologue and globals_:
                for var, size, name in globals_:
                    _register_global(builder, var, size, name, entry_r, out)
                    n_global += 1

            if idx == prologue and locals_:
                for var, size, name, track_def in locals_:
                    _register_stack(builder, var, size, name, not track_def,
                                    fn, entry_r, out)
                    n_stack += 1

            if locals_ and isinstance(cmd, control_cmds.Return):
                for var, _size, _name, _td in locals_:
                    _unregister_stack(builder, var, fn, cmd.r, out)
            if isinstance(cmd, control_cmds.Call) and cmd.direct_name:
                if _rewrite_alloc(builder, cmd, fn, out):
                    allocs += 1
                    out.append(cmd)
                    continue
                out.append(cmd)
                _escape_calls(builder, cmd, local_funcs, out)
                continue

            if cpp_only and not _is_cpp_range(cmd.r):
                # The C++ tier checks only what came from C++. Hand-written C
                # in the same unit keeps running at full speed, which is the
                # whole reason the level exists: the C has usually been
                # audited already and the doubt is about the layer above it.
                out.append(cmd)
                continue

            if idx in skip:
                pass                       # proved safe; no check emitted
            elif idx in mark_only:
                # Proved in bounds, but the shadow still has to learn these
                # bytes are defined or a later read of them is reported as
                # uninitialized.
                _mark_init_call(builder, cmd, out)
            elif isinstance(cmd, (value_cmds.ReadAt, value_cmds.ReadRel)):
                if _check_call(builder, cmd, fn, False, out):
                    checks += 1
            elif isinstance(cmd, (value_cmds.SetAt, value_cmds.SetRel)):
                if _check_call(builder, cmd, fn, True, out):
                    checks += 1
            out.append(cmd)
        il_code.commands[fn] = out

    return (checks, allocs, n_elided, n_marked, n_stack, n_hoisted, n_global)
