"""IL-level instrumentation for --mem-safe (the C tier).

The macro tier in runtime/crust_memsafe.h only checks accesses the programmer
wrote the macros around, which is right for generated C but useless for a
directory full of hand-written .c files. This pass gets the same checks without
touching the source: it rewrites the IL after `make_il`, inserting a call to
the shadow-table runtime before every dereference and redirecting the allocator
calls to the tracking wrappers.

Running on the IL rather than the source is what makes it complete. Every way C
has of reaching memory -- `*p`, `a[i]`, `s->field`, a compound assignment's
implicit read-modify-write, a dereference buried in a macro expansion -- has
already been lowered to the same handful of commands by the time this pass
sees it, so there is one place to instrument instead of a dozen syntactic
forms to chase.

Two things make this possible and are worth knowing:

*Positions.* IL commands carry source ranges (`ILCommand.r`), so an inserted
check reports the same `file:line` a hand-written macro does. Without that this
pass could only say which function was at fault.

*Direct calls.* A `Call` whose `direct_name` is set never materializes its
function pointer -- `Call.inputs()` omits it and the back ends emit `call
<name>` straight from the name. So a callee can be synthesized here from
nothing but a ctype, without being declared in the translation unit or entered
in the symbol table. `--auto-free` predates this trick and has to scavenge an
existing `free` reference out of the IL, which is why it silently does nothing
in a unit that never frees anything.
"""

import shivyc.ctypes as ctypes
import shivyc.il_cmds.control as control_cmds
import shivyc.il_cmds.value as value_cmds

from shivyc.ctypes import FunctionCType, PointerCType
from shivyc.il_gen import ILValue


# Allocator name -> (runtime replacement, index of the size-ish args to keep).
# The wrappers take the original arguments followed by (file, line, func), so
# only the name and the trailing site arguments differ.
_ALLOC_MAP = {
    "malloc": "crust_ms_malloc",
    "calloc": "crust_ms_calloc",
    "realloc": "crust_ms_realloc",
}
_FREE_MAP = {
    "free": "crust_ms_free",
}

# The macro tier's check entry points. When source already expanded the
# CRUST_MS_* macros -- C generated by `cpprust.py --mem-safe`, most importantly
# -- the access it guards must not be checked a second time here, or every bug
# is reported twice.
_MACRO_CHECKS = frozenset([
    "crust_ms_check_read", "crust_ms_check_write",
])
_MACRO_CHECKED_WR = "crust_ms_checked_wr"

# The runtime's own entry points, so instrumentation never instruments itself.
_RUNTIME_FUNCS = frozenset([
    "crust_ms_il_read", "crust_ms_il_write", "crust_ms_il_escape",
    "crust_ms_malloc", "crust_ms_calloc", "crust_ms_realloc", "crust_ms_free",
    "crust_ms_check_read", "crust_ms_check_write", "crust_ms_checked_wr",
    "crust_ms_register", "crust_ms_unregister", "crust_ms_mark_init",
])


class _Builder:
    """Makes the ILValues an inserted call needs.

    String literals are interned per translation unit: a file name repeated at
    every check would otherwise emit one copy of the string per access, which
    on a large file is a great deal of .rodata for no benefit.
    """

    def __init__(self, il_code):
        self.il = il_code
        self._strs = {}
        self._ints = {}

    def string(self, text):
        """The array ILValue for a string literal (interned per TU)."""
        if text in self._strs:
            return self._strs[text]
        chars = [ord(ch) for ch in text] + [0]
        val = ILValue(ctypes.ArrayCType(ctypes.char, len(chars)))
        self.il.register_string_literal(val, chars)
        self._strs[text] = val
        return val

    def string_ptr(self, text, out):
        """A char* to `text`, appending the AddrOf that produces it to `out`.

        A string literal's ILValue has array type, and an array does not decay
        on its own down here -- passing one straight to a call hands the back
        end a value whose width is the length of the string, which is not a
        register size. The front end decays through AddrOf and so does this.

        Emitted immediately before each use rather than once per function: a
        single hoisted definition would be skipped by any branch that jumps
        over it, and the address of a static string is a `lea` that the
        optimizer is welcome to fold back together.
        """
        arr = self.string(text)
        ptr = ILValue(PointerCType(ctypes.char))
        out.append(value_cmds.AddrOf(ptr, arr))
        return ptr

    def integer(self, n, ctype):
        """An ILValue holding the integer literal `n`."""
        key = (n, id(ctype))
        if key in self._ints:
            return self._ints[key]
        val = ILValue(ctype)
        self.il.register_literal_var(val, n)
        self._ints[key] = val
        return val

    def callee(self, name, arg_types, ret=None):
        """A function ILValue for `name`, synthesized rather than declared.

        Only the ctype is ever consulted: Call reads `func.ctype.arg.ret` to
        decide whether the result is used, and the back ends take the symbol
        from direct_name. Nothing here has to exist in the symbol table.
        """
        ret = ret if ret is not None else ctypes.void
        ftype = FunctionCType(list(arg_types), ret, False)
        return ILValue(PointerCType(ftype))


def _site_args(builder, cmd, func_name, out):
    """The (file, line, func) triple every runtime entry point ends with.

    Appends to `out` the commands needed to materialize the two strings.
    """
    r = cmd.r
    if r is not None and getattr(r, "start", None) is not None:
        path = r.start.file
        line = r.start.line
    else:
        # A command with no range is one a previous pass synthesized. Naming
        # the function is still better than dropping the check.
        path = "<generated>"
        line = 0
    return [builder.string_ptr(path, out),
            builder.integer(line, ctypes.integer),
            builder.string_ptr(func_name, out)]


def _char_ptr():
    return PointerCType(ctypes.char)


def _void_ptr():
    return PointerCType(ctypes.void)


def _access_size(cmd):
    """Bytes touched by a ReadAt/SetAt, or None when it cannot be determined.

    ReadAt names the size through its output's type and SetAt through the
    value being stored; the pointer's own pointee type is not reliable, since
    the front end freely casts pointers to char* while lowering.
    """
    if isinstance(cmd, value_cmds.ReadAt):
        ct = cmd.output.ctype
    else:
        ct = cmd.val.ctype
    size = getattr(ct, "size", None)
    if not isinstance(size, int) or size <= 0:
        return None
    return size


def _check_call(builder, cmd, func_name, writing, out):
    """Append to `out` the runtime check that guards `cmd`.

    Returns True when a check was emitted.
    """
    size = _access_size(cmd)
    if size is None:
        return False
    name = "crust_ms_il_write" if writing else "crust_ms_il_read"
    arg_types = [_void_ptr(), ctypes.unsig_longint, _char_ptr(),
                 ctypes.integer, _char_ptr()]
    callee = builder.callee(name, arg_types)
    args = ([cmd.addr, builder.integer(size, ctypes.unsig_longint)]
            + _site_args(builder, cmd, func_name, out))
    call = control_cmds.Call(callee, args, None)
    call.direct_name = name
    # Inherit the position of the access being checked, so a diagnostic raised
    # about the inserted call points at the user's code rather than nowhere.
    call.r = cmd.r
    for c in out[len(out) - 2:]:
        c.r = cmd.r
    out.append(call)
    return True


def _rewrite_alloc(builder, cmd, func_name, out):
    """Redirect an allocator/deallocator call to its tracking wrapper.

    Rewritten in place rather than wrapped: the runtime has to see the *real*
    malloc return value to record the region, and it has to intercept free
    rather than merely observe it, so that a double free is reported instead of
    being passed to libc a second time.
    """
    name = cmd.direct_name
    repl = _ALLOC_MAP.get(name) or _FREE_MAP.get(name)
    if repl is None:
        return False
    site = _site_args(builder, cmd, func_name, out)
    for c in out[len(out) - 2:]:
        c.r = cmd.r
    cmd.args = list(cmd.args) + site
    cmd.direct_name = repl
    # The synthesized ctype has to keep the original return type: Call caches
    # void_return at construction, and the back ends decide whether to move
    # RAX into `ret` from that.
    ret = cmd.func.ctype.arg.ret
    arg_types = [a.ctype for a in cmd.args]
    cmd.func = builder.callee(repl, arg_types, ret)
    cmd.void_return = ret.is_void()
    return True


def _already_macro_instrumented(il_code, symbol_table):
    """True when this TU's source expanded the CRUST_MS_* check macros."""
    import shivyc.stackless as stackless
    for fn in list(il_code.commands):
        cmds = stackless._apply_direct_calls(il_code.commands[fn],
                                             symbol_table)
        il_code.commands[fn] = cmds
        for c in cmds:
            if (isinstance(c, control_cmds.Call)
                    and c.direct_name in _MACRO_CHECKS
                    or (isinstance(c, control_cmds.Call)
                        and c.direct_name == _MACRO_CHECKED_WR)):
                return True
    return False


def _escape_calls(builder, cmd, local_funcs, out):
    """Tell the runtime about pointers handed to uninstrumented code.

    Emitted only for callees not defined in this translation unit. A call to a
    function compiled alongside this one needs nothing: its own writes are
    instrumented, so the shadow already saw them, and staying quiet there keeps
    full uninitialized-read detection everywhere except at the boundary with
    code the flag does not reach.

    Returns the number of hooks emitted.
    """
    name = cmd.direct_name
    if name in local_funcs or name in _ALLOC_MAP or name in _FREE_MAP:
        return 0
    if name in _RUNTIME_FUNCS:
        return 0
    n = 0
    for arg in cmd.args:
        ct = arg.ctype
        if not (ct.is_pointer() if hasattr(ct, "is_pointer") else False):
            continue
        callee = builder.callee("crust_ms_il_escape", [_void_ptr()])
        call = control_cmds.Call(callee, [arg], None)
        call.direct_name = "crust_ms_il_escape"
        call.r = cmd.r
        out.append(call)
        n += 1
    return n


def instrument(il_code, symbol_table, args=None):
    """Insert runtime memory-safety checks into every function's IL.

    Returns (checks inserted, allocator calls redirected).
    """
    import shivyc.stackless as stackless

    builder = _Builder(il_code)
    checks = 0
    allocs = 0
    local_funcs = frozenset(il_code.commands)

    # A translation unit that already carries macro checks was instrumented by
    # the C++ tier (`cpprust.py --mem-safe`), and re-checking every access here
    # would run two checks per dereference for one bug. Tiers are chosen per
    # translation unit, so this one defers.
    #
    # Matching the guarded access individually was the first attempt and does
    # not work: the macro casts its pointer to `const void *` before the call,
    # so the value passed to the check and the value dereferenced afterwards
    # are different ILValues.
    if _already_macro_instrumented(il_code, symbol_table):
        return 0, 0

    for fn in list(il_code.commands):
        # `direct_name` is what identifies a callee by name, and it is set by
        # the stackless pass, which runs after this one -- until it does, a
        # call to malloc is an indirect call through an AddrOf. Resolve names
        # here so allocator calls are recognizable; the result is written back,
        # so the later pass finds the work already done rather than repeating
        # it. This is the same thing --check-memory does to see the call graph.
        cmds = stackless._apply_direct_calls(il_code.commands[fn],
                                             symbol_table)
        il_code.commands[fn] = cmds
        out = []
        for cmd in cmds:
            if isinstance(cmd, control_cmds.Call) and cmd.direct_name:
                if _rewrite_alloc(builder, cmd, fn, out):
                    allocs += 1
                    out.append(cmd)
                    continue
                out.append(cmd)
                _escape_calls(builder, cmd, local_funcs, out)
                continue

            if isinstance(cmd, value_cmds.ReadAt):
                if _check_call(builder, cmd, fn, False, out):
                    checks += 1
            elif isinstance(cmd, value_cmds.SetAt):
                if _check_call(builder, cmd, fn, True, out):
                    checks += 1
            out.append(cmd)
        il_code.commands[fn] = out

    return checks, allocs
