"""Export tables for the Windows DLLs rlink links against by name.

rlink writes a PE executable's import table itself (see rlink_pe.py), so it
needs to know, without any file from a Windows system being present, which
DLL provides each symbol a program leaves undefined, and whether that symbol
is a function (reached through a jump stub rlink generates) or data (which
must be reached through its import-address-table slot, `__imp_NAME`, since
a stub is code and cannot stand in for a variable).

Provenance -- facts about the DLLs' interfaces, not code from them:

* Names: the `__imp_` symbols of MinGW-w64's import libraries,
  libmsvcrt-os.a (exactly what msvcrt.dll exports, without the MinGW
  emulations libmsvcrt.a layers on top) and libkernel32.a, from the
  x86_64-w64-mingw32 packages of mingw-w64 11.0.
* Data versus code: an import library marks a data export by giving it no
  code thunk -- but MinGW also withholds the thunk from functions it
  substitutes with its own implementations (sin, pow, atexit, ...). So each
  candidate was checked against Wine 9.0's msvcrt.dll, whose export table
  says whether an address lands in an executable section. DATA below is the
  set both agree on, plus five Wine does not export at all (_fileinfo,
  _mbcasemap, daylight, timezone, tzname), which Microsoft documents as
  variables.

Regenerating needs those two packages; see WINDOWS.md.
"""

MSVCRT_FUNCS = """
$I10_OUTPUT ??0__non_rtti_object@@QEAA@AEBV0@@Z
??0__non_rtti_object@@QEAA@PEBD@Z ??0bad_cast@@AEAA@PEBQEBD@Z
??0bad_cast@@QEAA@AEBQEBD@Z ??0bad_cast@@QEAA@AEBV0@@Z
??0bad_cast@@QEAA@PEBD@Z ??0bad_typeid@@QEAA@AEBV0@@Z
??0bad_typeid@@QEAA@PEBD@Z ??0exception@@QEAA@AEBQEBD@Z
??0exception@@QEAA@AEBQEBDH@Z ??0exception@@QEAA@AEBV0@@Z
??0exception@@QEAA@XZ ??1__non_rtti_object@@UEAA@XZ ??1bad_cast@@UEAA@XZ
??1bad_typeid@@UEAA@XZ ??1exception@@UEAA@XZ ??1type_info@@UEAA@XZ
??2@YAPEAX_K@Z ??3@YAXPEAX@Z ??4__non_rtti_object@@QEAAAEAV0@AEBV0@@Z
??4bad_cast@@QEAAAEAV0@AEBV0@@Z ??4bad_typeid@@QEAAAEAV0@AEBV0@@Z
??4exception@@QEAAAEAV0@AEBV0@@Z ??8type_info@@QEBAHAEBV0@@Z
??9type_info@@QEBAHAEBV0@@Z ??_7__non_rtti_object@@6B@ ??_7bad_cast@@6B@
??_7bad_typeid@@6B@ ??_7exception@@6B@ ??_Fbad_cast@@QEAAXXZ
??_Fbad_typeid@@QEAAXXZ ??_U@YAPEAX_K@Z ??_V@YAXPEAX@Z
?_query_new_handler@@YAP6AH_K@ZXZ ?_query_new_mode@@YAHXZ
?_set_new_handler@@YAP6AH_K@ZP6AH0@Z@Z ?_set_new_mode@@YAHH@Z
?_set_se_translator@@YAP6AXIPEAU_EXCEPTION_POINTERS@@@ZP6AXI0@Z@Z
?before@type_info@@QEBAHAEBV1@@Z ?name@type_info@@QEBAPEBDXZ
?raw_name@type_info@@QEBAPEBDXZ ?set_new_handler@@YAP6AXXZP6AXXZ@Z
?set_terminate@@YAP6AXXZP6AXXZ@Z ?set_unexpected@@YAP6AXXZP6AXXZ@Z
?terminate@@YAXXZ ?unexpected@@YAXXZ ?what@exception@@UEBAPEBDXZ
_CxxThrowException _Getdays _Getmonths _Gettnames _Strftime _XcptFilter
__C_specific_handler __CppXcptFilter __CxxFrameHandler
__DestructExceptionObject __RTCastToVoid __RTDynamicCast __RTtypeid
__STRINGTOLD ___lc_codepage_func ___lc_collate_cp_func ___lc_handle_func
___mb_cur_max_func ___setlc_active_func ___unguarded_readlc_active_add_func
__crtCompareStringA __crtCompareStringW __crtGetLocaleInfoW
__crtGetStringTypeW __crtLCMapStringA __crtLCMapStringW __dllonexit
__doserrno __fpecode __getmainargs __iob_func __isascii __iscsym __iscsymf
__lconv_init __ms_fprintf __ms_fscanf __ms_fwprintf __ms_fwscanf __ms_printf
__ms_scanf __ms_sprintf __ms_sscanf __ms_swprintf __ms_swscanf __ms_vfprintf
__ms_vfwprintf __ms_vprintf __ms_vsprintf __ms_vswprintf __ms_vwprintf
__ms_wprintf __ms_wscanf __pctype_func __pwctype_func __pxcptinfoptrs
__set_app_type __setusermatherr __threadhandle __threadid __toascii
__unDName __unDNameEx __uncaught_exception __wcserror __wcserror_s
__wgetmainargs _abs64 _access _aligned_free _aligned_malloc
_aligned_offset_malloc _aligned_offset_realloc _aligned_realloc _amsg_exit
_assert _atodbl _atodbl_l _atof_l _atoflt_l _atoi64 _atoi64_l _atoi_l
_atol_l _atoldbl _atoldbl_l _atoll_l _beep _beginthread _beginthreadex
_c_exit _cabs _callnewh _cexit _cgets _cgetws _chdir _chdrive _chgsign
_chgsignf _chmod _chsize _clearfp _close _commit _control87 _controlfp
_copysign _copysignf _cprintf _cprintf_l _cprintf_p _cprintf_p_l _cputs
_cputws _creat _cscanf _cscanf_l _cscanf_s _cscanf_s_l _ctime64 _ctype
_cwait _cwprintf _cwprintf_l _cwprintf_p _cwprintf_p_l _cwscanf _cwscanf_l
_cwscanf_s _cwscanf_s_l _difftime32 _difftime64 _dup _dup2 _ecvt _ecvt_s
_endthread _endthreadex _eof _errno _execl _execle _execlp _execlpe _execv
_execve _execvp _execvpe _exit _expand _fcloseall _fcvt _fcvt_s _fdopen
_fgetchar _fgetwchar _filbuf _filelength _filelengthi64 _fileno _findclose
_findfirst _findfirst64 _findfirst64i32 _findfirsti64 _findnext _findnext64
_findnext64i32 _findnexti64 _finite _finitef _flsbuf _flushall _fpclass
_fpclassf _fpreset _fprintf_l _fprintf_p _fprintf_p_l _fprintf_s_l _fputchar
_fputwchar _fscanf_l _fscanf_s_l _fsopen _fstat _fstat64 _fstat64i32
_fstati64 _ftime _ftime32 _ftime32_s _ftime64 _ftime64_s _ftime_s _fullpath
_futime _futime32 _futime64 _fwprintf_l _fwprintf_p _fwprintf_p_l
_fwprintf_s_l _fwscanf_l _fwscanf_s_l _gcvt _gcvt_s _get_doserrno
_get_heap_handle _get_osfhandle _get_sbh_threshold _getch _getche _getcwd
_getdcwd _getdiskfree _getdllprocaddr _getdrive _getdrives _getmaxstdio
_getmbcp _getpid _getsystime _getw _getwch _getwche _getws _gmtime32
_gmtime64 _heapadd _heapchk _heapmin _heapset _heapused _heapwalk _hypot
_hypotf _i64toa _i64toa_s _i64tow _i64tow_s _initterm _isalnum_l _isalpha_l
_isatty _iscntrl_l _isctype _isctype_l _isdigit_l _isgraph_l _isleadbyte_l
_islower_l _ismbbalnum _ismbbalnum_l _ismbbalpha _ismbbalpha_l _ismbbgraph
_ismbbgraph_l _ismbbkalnum _ismbbkalnum_l _ismbbkana _ismbbkana_l
_ismbbkprint _ismbbkprint_l _ismbbkpunct _ismbbkpunct_l _ismbblead
_ismbblead_l _ismbbprint _ismbbprint_l _ismbbpunct _ismbbpunct_l _ismbbtrail
_ismbbtrail_l _ismbcalnum _ismbcalnum_l _ismbcalpha _ismbcalpha_l
_ismbcdigit _ismbcdigit_l _ismbcgraph _ismbcgraph_l _ismbchira _ismbchira_l
_ismbckata _ismbckata_l _ismbcl0 _ismbcl0_l _ismbcl1 _ismbcl1_l _ismbcl2
_ismbcl2_l _ismbclegal _ismbclegal_l _ismbclower _ismbclower_l _ismbcprint
_ismbcprint_l _ismbcpunct _ismbcpunct_l _ismbcspace _ismbcspace_l
_ismbcsymbol _ismbcsymbol_l _ismbcupper _ismbcupper_l _ismbslead
_ismbslead_l _ismbstrail _ismbstrail_l _isnan _isnanf _isprint_l _isspace_l
_isupper_l _iswalnum_l _iswalpha_l _iswcntrl_l _iswctype_l _iswdigit_l
_iswgraph_l _iswlower_l _iswprint_l _iswpunct_l _iswspace_l _iswupper_l
_iswxdigit_l _isxdigit_l _itoa _itoa_s _itow _itow_s _j0 _j1 _jn _kbhit
_lfind _lfind_s _loaddll _local_unwind _localtime32 _localtime64 _lock
_locking _logb _logbf _lrotl _lrotr _lsearch _lsearch_s _lseek _lseeki64
_ltoa _ltoa_s _ltow _ltow_s _makepath _makepath_s _mbbtombc _mbbtombc_l
_mbbtype _mbccpy _mbccpy_l _mbccpy_s _mbccpy_s_l _mbcjistojms _mbcjistojms_l
_mbcjmstojis _mbcjmstojis_l _mbclen _mbclen_l _mbctohira _mbctohira_l
_mbctokata _mbctokata_l _mbctolower _mbctolower_l _mbctombb _mbctombb_l
_mbctoupper _mbctoupper_l _mblen_l _mbsbtype _mbsbtype_l _mbscat _mbscat_s
_mbscat_s_l _mbschr _mbschr_l _mbscmp _mbscmp_l _mbscoll _mbscoll_l _mbscpy
_mbscpy_s _mbscpy_s_l _mbscspn _mbscspn_l _mbsdec _mbsdec_l _mbsdup _mbsicmp
_mbsicmp_l _mbsicoll _mbsicoll_l _mbsinc _mbsinc_l _mbslen _mbslen_l _mbslwr
_mbslwr_l _mbslwr_s _mbslwr_s_l _mbsnbcat _mbsnbcat_l _mbsnbcat_s
_mbsnbcat_s_l _mbsnbcmp _mbsnbcmp_l _mbsnbcnt _mbsnbcnt_l _mbsnbcoll
_mbsnbcoll_l _mbsnbcpy _mbsnbcpy_l _mbsnbcpy_s _mbsnbcpy_s_l _mbsnbicmp
_mbsnbicmp_l _mbsnbicoll _mbsnbicoll_l _mbsnbset _mbsnbset_l _mbsnbset_s
_mbsnbset_s_l _mbsncat _mbsncat_l _mbsncat_s _mbsncat_s_l _mbsnccnt
_mbsnccnt_l _mbsncmp _mbsncmp_l _mbsncoll _mbsncoll_l _mbsncpy _mbsncpy_l
_mbsncpy_s _mbsncpy_s_l _mbsnextc _mbsnextc_l _mbsnicmp _mbsnicmp_l
_mbsnicoll _mbsnicoll_l _mbsninc _mbsninc_l _mbsnlen _mbsnlen_l _mbsnset
_mbsnset_l _mbsnset_s _mbsnset_s_l _mbspbrk _mbspbrk_l _mbsrchr _mbsrchr_l
_mbsrev _mbsrev_l _mbsset _mbsset_l _mbsset_s _mbsset_s_l _mbsspn _mbsspn_l
_mbsspnp _mbsspnp_l _mbsstr _mbsstr_l _mbstok _mbstok_l _mbstok_s
_mbstok_s_l _mbstowcs_l _mbstowcs_s_l _mbstrlen _mbstrlen_l _mbstrnlen
_mbstrnlen_l _mbsupr _mbsupr_l _mbsupr_s _mbsupr_s_l _mbtowc_l _memccpy
_memicmp _memicmp_l _mkdir _mkgmtime _mkgmtime32 _mkgmtime64 _mktemp
_mktime64 _msize _nextafter _nextafterf _onexit _open _open_osfhandle
_pclose _pipe _popen _printf_l _printf_p _printf_p_l _printf_s_l _purecall
_putch _putenv _putenv_s _putw _putwch _putws _read _resetstkoflw _rmdir
_rmtmp _rotl _rotl64 _rotr _rotr64 _scalb _scalbf _scanf_l _scanf_s_l
_scprintf _scprintf_l _scprintf_p_l _scwprintf _scwprintf_l _scwprintf_p_l
_searchenv _searchenv_s _set_controlfp _set_doserrno _set_error_mode
_set_sbh_threshold _seterrormode _setjmp _setjmpex _setmaxstdio _setmbcp
_setmode _setsystime _sleep _snprintf _snprintf_c _snprintf_c_l _snprintf_l
_snprintf_s _snprintf_s_l _snscanf _snscanf_l _snscanf_s _snscanf_s_l
_snwprintf _snwprintf_l _snwprintf_s _snwprintf_s_l _snwscanf _snwscanf_l
_snwscanf_s _snwscanf_s_l _sopen _spawnl _spawnle _spawnlp _spawnlpe _spawnv
_spawnve _spawnvp _spawnvpe _splitpath _splitpath_s _sprintf_l _sprintf_p_l
_sprintf_s_l _sscanf_l _sscanf_s_l _stat _stat64 _stat64i32 _stati64
_statusfp _strcmpi _strcoll_l _strdate _strdup _strerror _strerror_s
_stricmp _stricmp_l _stricoll _stricoll_l _strlwr _strlwr_l _strlwr_s
_strlwr_s_l _strncoll _strncoll_l _strnicmp _strnicmp_l _strnicoll
_strnicoll_l _strnset _strnset_s _strrev _strset _strset_s _strtime
_strtod_l _strtoi64 _strtoi64_l _strtoimax_l _strtol_l _strtoll_l _strtoui64
_strtoui64_l _strtoul_l _strtoull_l _strtoumax_l _strupr _strupr_l _strupr_s
_strupr_s_l _strxfrm_l _swab _swprintf _swprintf_c _swprintf_c_l
_swprintf_p_l _swprintf_s_l _swscanf_l _swscanf_s_l _tell _telli64 _tempnam
_time64 _tolower _tolower_l _toupper _toupper_l _towlower_l _towupper_l
_tzset _ui64toa _ui64toa_s _ui64tow _ui64tow_s _ultoa _ultoa_s _ultow
_ultow_s _umask _ungetch _ungetwch _unlink _unloaddll _unlock _utime
_utime32 _utime64 _vcprintf _vcprintf_l _vcprintf_p _vcprintf_p_l _vcwprintf
_vcwprintf_l _vcwprintf_p _vcwprintf_p_l _vfprintf_l _vfprintf_p
_vfprintf_p_l _vfprintf_s_l _vfwprintf_l _vfwprintf_p _vfwprintf_p_l
_vfwprintf_s_l _vprintf_l _vprintf_p _vprintf_p_l _vprintf_s_l _vscprintf
_vscprintf_l _vscprintf_p_l _vscwprintf _vscwprintf_l _vscwprintf_p_l
_vsnprintf _vsnprintf_c _vsnprintf_c_l _vsnprintf_l _vsnprintf_s
_vsnprintf_s_l _vsnwprintf _vsnwprintf_l _vsnwprintf_s _vsnwprintf_s_l
_vsprintf_l _vsprintf_p _vsprintf_p_l _vsprintf_s_l _vswprintf _vswprintf_c
_vswprintf_c_l _vswprintf_l _vswprintf_p_l _vswprintf_s_l _vwprintf_l
_vwprintf_p _vwprintf_p_l _vwprintf_s_l _waccess _wasctime _wassert _wchdir
_wchmod _wcreat _wcscoll_l _wcsdup _wcserror _wcserror_s _wcsftime_l
_wcsicmp _wcsicmp_l _wcsicoll _wcsicoll_l _wcslwr _wcslwr_l _wcslwr_s
_wcslwr_s_l _wcsncoll _wcsncoll_l _wcsnicmp _wcsnicmp_l _wcsnicoll
_wcsnicoll_l _wcsnset _wcsnset_s _wcsrev _wcsset _wcsset_s _wcstoi64
_wcstoi64_l _wcstol_l _wcstombs_l _wcstombs_s_l _wcstoui64 _wcstoui64_l
_wcstoul_l _wcsupr _wcsupr_l _wcsupr_s _wcsupr_s_l _wcsxfrm_l _wctime
_wctime64 _wctomb_l _wctomb_s_l _wctype _wexecl _wexecle _wexeclp _wexeclpe
_wexecv _wexecve _wexecvp _wexecvpe _wfdopen _wfindfirst _wfindfirst64
_wfindfirst64i32 _wfindfirsti64 _wfindnext _wfindnext64 _wfindnext64i32
_wfindnexti64 _wfopen _wfopen_s _wfreopen _wfreopen_s _wfsopen _wfullpath
_wgetcwd _wgetdcwd _wgetenv _wgetenv_s _winput_s _wmakepath _wmakepath_s
_wmkdir _wmktemp _wopen _woutput_s _wperror _wpopen _wprintf_l _wprintf_p
_wprintf_p_l _wprintf_s_l _wputenv _wputenv_s _wremove _wrename _write
_wrmdir _wscanf_l _wscanf_s_l _wsearchenv _wsearchenv_s _wsetlocale _wsopen
_wsopen_s _wspawnl _wspawnle _wspawnlp _wspawnlpe _wspawnv _wspawnve
_wspawnvp _wspawnvpe _wsplitpath _wsplitpath_s _wstat _wstat64 _wstat64i32
_wstati64 _wstrdate _wstrtime _wsystem _wtempnam _wtmpnam _wtmpnam_s _wtof
_wtof_l _wtoi _wtoi64 _wtoi64_l _wtoi_l _wtol _wtol_l _wunlink _wutime
_wutime32 _wutime64 _y0 _y1 _yn abort abs access acos acosf asctime asin
asinf atan atan2 atan2f atanf atexit atof atoi atol atoll bsearch bsearch_s
calloc ceil ceilf chdir chgsign chmod chsize clearerr clearerr_s clock close
cos cosf cosh coshf creat ctime cwait difftime div dup dup2 ecvt eof execl
execle execlp execlpe execv execve execvp execvpe exit exp expf fabs fclose
fcvt fdopen feof ferror fflush fgetc fgetchar fgetpos fgets fgetwc fgetwchar
fgetws filelength fileno finite floor floorf fmod fmodf fopen fopen_s
fpclass fprintf fprintf_s fputc fputchar fputs fputwc fputwchar fputws fread
free freopen freopen_s frexp fscanf fscanf_s fseek fsetpos ftell fwprintf
fwprintf_s fwrite fwscanf fwscanf_s gcvt getc getch getchar getche getcwd
getenv getenv_s getpid gets getw getwc getwchar gmtime heapwalk hypot
imaxabs is_wctype isalnum isalpha isascii isatty iscntrl iscsym iscsymf
isdigit isgraph isleadbyte islower isprint ispunct isspace isupper iswalnum
iswalpha iswascii iswcntrl iswctype iswdigit iswgraph iswlower iswprint
iswpunct iswspace iswupper iswxdigit isxdigit itoa j0 j1 jn kbhit labs ldexp
ldiv lfind llabs localeconv localtime log log10 log10f logf longjmp lsearch
lseek ltoa malloc mblen mbsrtowcs_s mbstowcs mbstowcs_s mbtowc memccpy
memchr memcmp memcpy memicmp memmove memset mkdir mktemp mktime modf modff
nextafter open pclose perror popen pow powf printf printf_s putc putch
putchar putenv puts putw putwc putwchar qsort qsort_s raise rand read
realloc remove rename rewind rmdir rmtmp scanf scanf_s searchenv setbuf
setjmp setlocale setmode setvbuf signal sin sinf sinh sinhf snwprintf sopen
spawnl spawnle spawnlp spawnlpe spawnv spawnve spawnvp spawnvpe sprintf sqrt
sqrtf srand sscanf sscanf_s strcasecmp strcat strcat_s strchr strcmp strcmpi
strcoll strcpy strcpy_s strcspn strdup strerror strftime stricmp stricoll
strlen strlwr strncasecmp strncat strncat_s strncmp strncpy strncpy_s
strnicmp strnset strpbrk strrchr strrev strset strspn strstr strtod
strtoimax strtok strtok_s strtol strtoll strtoul strtoull strtoumax strupr
strxfrm swab swprintf swprintf_s swscanf swscanf_s system tan tanf tanh tell
tempnam time tmpfile tmpfile_s tmpnam tmpnam_s toascii tolower toupper
towlower towupper tzset umask ungetc ungetch ungetwc unlink utime vfprintf
vfprintf_s vfwprintf vfwprintf_s vprintf vprintf_s vsnprintf_s vsnwprintf
vsprintf vswprintf vswprintf_s vwprintf vwprintf_s wcrtomb_s wcscat wcscat_s
wcschr wcscmp wcscmpi wcscoll wcscpy wcscpy_s wcscspn wcsdup wcsftime
wcsicmp wcsicoll wcslen wcslwr wcsncat wcsncat_s wcsncmp wcsncpy wcsncpy_s
wcsnicmp wcsnlen wcsnset wcspbrk wcsrchr wcsrev wcsrtombs_s wcsset wcsspn
wcsstr wcstod wcstok wcstok_s wcstol wcstombs wcstombs_s wcstoul wcsupr
wcsxfrm wctomb wctomb_s wpopen wprintf wprintf_s write wscanf wscanf_s y0 y1
yn
"""

MSVCRT_DATA = """
_HUGE __argc __argv __badioinfo __initenv __lc_codepage __lc_collate_cp
__lc_handle __mb_cur_max __pioinfo __setlc_active __unguarded_readlc_active
__wargv __winitenv _acmdln _aexit_rtn _commode _daylight _dstbias _environ
_fileinfo _fmode _iob _mbcasemap _mbctype _osplatform _osver _pctype _pgmptr
_pwctype _sys_errlist _sys_nerr _timezone _tzname _wcmdln _wenviron
_winmajor _winminor _winver _wpgmptr daylight timezone tzname
"""

KERNEL32_FUNCS = """
AcquireSRWLockExclusive AcquireSRWLockShared ActivateActCtx
ActivateActCtxWorker AddAtomA AddAtomW AddConsoleAliasA AddConsoleAliasW
AddDllDirectory AddIntegrityLabelToBoundaryDescriptor
AddLocalAlternateComputerNameA AddLocalAlternateComputerNameW AddRefActCtx
AddRefActCtxWorker AddResourceAttributeAce AddSIDToBoundaryDescriptor
AddScopedPolicyIDAce AddSecureMemoryCacheCallback AddVectoredContinueHandler
AddVectoredExceptionHandler AdjustCalendarDate AllocConsole
AllocateUserPhysicalPages AllocateUserPhysicalPagesNuma
AppPolicyGetClrCompat AppPolicyGetCreateFileAccess
AppPolicyGetLifecycleManagement AppPolicyGetMediaFoundationCodecLoading
AppPolicyGetProcessTerminationMethod AppPolicyGetShowDeveloperDiagnostic
AppPolicyGetThreadInitializationType AppPolicyGetWindowingModel
AppXGetOSMaxVersionTested ApplicationRecoveryFinished
ApplicationRecoveryInProgress AreFileApisANSI AssignProcessToJobObject
AttachConsole BackupRead BackupSeek BackupWrite BaseCheckAppcompatCache
BaseCheckAppcompatCacheEx BaseCheckAppcompatCacheExWorker
BaseCheckAppcompatCacheWorker BaseCheckElevation BaseCheckRunApp
BaseCleanupAppcompatCacheSupport BaseCleanupAppcompatCacheSupportWorker
BaseDestroyVDMEnvironment BaseDllReadWriteIniFile BaseDumpAppcompatCache
BaseDumpAppcompatCacheWorker BaseElevationPostProcessing
BaseFlushAppcompatCache BaseFlushAppcompatCacheWorker
BaseFormatObjectAttributes BaseFormatTimeOut
BaseFreeAppCompatDataForProcessWorker BaseGenerateAppCompatData
BaseGetNamedObjectDirectory BaseInitAppcompatCacheSupport
BaseInitAppcompatCacheSupportWorker BaseIsAppcompatInfrastructureDisabled
BaseIsAppcompatInfrastructureDisabledWorker BaseIsDosApplication
BaseProcessInitPostImport BaseProcessStart BaseQueryModuleData
BaseReadAppCompatDataForProcessWorker BaseSetLastNTError BaseThreadInitThunk
BaseThreadStart BaseUpdateAppcompatCache BaseUpdateAppcompatCacheWorker
BaseUpdateVDMEntry BaseVerifyUnicodeString
BaseWriteErrorElevationRequiredEvent Basep8BitStringToDynamicUnicodeString
BasepAllocateActivationContextActivationBlock
BasepAnsiStringToDynamicUnicodeString BasepAppContainerEnvironmentExtension
BasepAppXExtension BasepCheckAppCompat BasepCheckBadapp
BasepCheckWebBladeHashes BasepCheckWinSaferRestrictions
BasepConstructSxsCreateProcessMessage BasepCopyEncryption
BasepFreeActivationContextActivationBlock BasepFreeAppCompatData
BasepGetAppCompatData BasepGetComputerNameFromNtPath BasepGetExeArchType
BasepInitAppCompatData BasepIsProcessAllowed BasepMapModuleHandle
BasepNotifyLoadStringResource BasepPostSuccessAppXExtension
BasepProcessInvalidImage BasepQueryAppCompat BasepQueryModuleChpeSettings
BasepReleaseAppXContext BasepReleaseSxsCreateProcessUtilityStruct
BasepReportFault BasepSetFileEncryptionCompression Beep BeginUpdateResourceA
BeginUpdateResourceW BindIoCompletionCallback BuildCommDCBA
BuildCommDCBAndTimeoutsA BuildCommDCBAndTimeoutsW BuildCommDCBW
CallNamedPipeA CallNamedPipeW CallbackMayRunLong CalloutOnFiberStack
CancelDeviceWakeupRequest CancelIo CancelIoEx CancelSynchronousIo
CancelThreadpoolIo CancelTimerQueueTimer CancelWaitableTimer CeipIsOptedIn
ChangeTimerQueueTimer CheckAllowDecryptedRemoteDestinationPolicy
CheckElevation CheckElevationEnabled CheckForReadOnlyResource
CheckForReadOnlyResourceFilter CheckNameLegalDOS8Dot3A
CheckNameLegalDOS8Dot3W CheckRemoteDebuggerPresent CheckTokenCapability
CheckTokenMembershipEx ClearCommBreak ClearCommError CloseConsoleHandle
CloseHandle ClosePackageInfo ClosePrivateNamespace CloseProfileUserMapping
ClosePseudoConsole CloseState CloseThreadpool CloseThreadpoolCleanupGroup
CloseThreadpoolCleanupGroupMembers CloseThreadpoolIo CloseThreadpoolTimer
CloseThreadpoolWait CloseThreadpoolWork CmdBatNotification CommConfigDialogA
CommConfigDialogW CompareCalendarDates CompareFileTime CompareStringA
CompareStringEx CompareStringOrdinal CompareStringW ConnectNamedPipe
ConsoleIMERoutine ConsoleMenuControl ContinueDebugEvent
ConvertCalDateTimeToSystemTime ConvertDefaultLocale ConvertFiberToThread
ConvertNLSDayOfWeekToWin32DayOfWeek ConvertSystemTimeToCalDateTime
ConvertThreadToFiber ConvertThreadToFiberEx CopyContext CopyExtendedContext
CopyFile2 CopyFileA CopyFileExA CopyFileExW CopyFileTransactedA
CopyFileTransactedW CopyFileW CopyLZFile CreateActCtxA CreateActCtxW
CreateActCtxWWorker CreateBoundaryDescriptorA CreateBoundaryDescriptorW
CreateConsoleScreenBuffer CreateDirectoryA CreateDirectoryExA
CreateDirectoryExW CreateDirectoryTransactedA CreateDirectoryTransactedW
CreateDirectoryW CreateEnclave CreateEventA CreateEventExA CreateEventExW
CreateEventW CreateFiber CreateFiberEx CreateFile2 CreateFileA
CreateFileMappingA CreateFileMappingFromApp CreateFileMappingNumaA
CreateFileMappingNumaW CreateFileMappingW CreateFileTransactedA
CreateFileTransactedW CreateFileW CreateHardLinkA CreateHardLinkTransactedA
CreateHardLinkTransactedW CreateHardLinkW CreateIoCompletionPort
CreateJobObjectA CreateJobObjectW CreateJobSet CreateMailslotA
CreateMailslotW CreateMemoryResourceNotification CreateMutexA CreateMutexExA
CreateMutexExW CreateMutexW CreateNamedPipeA CreateNamedPipeW
CreateNlsSecurityDescriptor CreatePipe CreatePrivateNamespaceA
CreatePrivateNamespaceW CreateProcessA CreateProcessInternalA
CreateProcessInternalW CreateProcessW CreatePseudoConsole CreateRemoteThread
CreateRemoteThreadEx CreateSemaphoreA CreateSemaphoreExA CreateSemaphoreExW
CreateSemaphoreW CreateSymbolicLinkA CreateSymbolicLinkTransactedA
CreateSymbolicLinkTransactedW CreateSymbolicLinkW CreateTapePartition
CreateThread CreateThreadpool CreateThreadpoolCleanupGroup
CreateThreadpoolIo CreateThreadpoolTimer CreateThreadpoolWait
CreateThreadpoolWork CreateTimerQueue CreateTimerQueueTimer
CreateToolhelp32Snapshot CreateUmsCompletionList CreateUmsThreadContext
CreateWaitableTimerA CreateWaitableTimerExA CreateWaitableTimerExW
CreateWaitableTimerW CtrlRoutine DeactivateActCtx DeactivateActCtxWorker
DebugActiveProcess DebugActiveProcessStop DebugBreak DebugBreakProcess
DebugSetProcessKillOnExit DecodePointer DecodeSystemPointer DefineDosDeviceA
DefineDosDeviceW DelayLoadFailureHook DeleteAtom DeleteBoundaryDescriptor
DeleteCriticalSection DeleteFiber DeleteFileA DeleteFileTransactedA
DeleteFileTransactedW DeleteFileW DeleteProcThreadAttributeList
DeleteSynchronizationBarrier DeleteTimerQueue DeleteTimerQueueEx
DeleteTimerQueueTimer DeleteUmsCompletionList DeleteUmsThreadContext
DeleteVolumeMountPointA DeleteVolumeMountPointW
DequeueUmsCompletionListItems DeviceIoControl DisableThreadLibraryCalls
DisableThreadProfiling DisassociateCurrentThreadFromCallback
DiscardVirtualMemory DisconnectNamedPipe DnsHostnameToComputerNameA
DnsHostnameToComputerNameExW DnsHostnameToComputerNameW
DosDateTimeToFileTime DosPathToSessionPathA DosPathToSessionPathW
DuplicateConsoleHandle DuplicateEncryptionInfoFileExt DuplicateHandle
EnableThreadProfiling EncodePointer EncodeSystemPointer EndUpdateResourceA
EndUpdateResourceW EnterCriticalSection EnterSynchronizationBarrier
EnterUmsSchedulingMode EnumCalendarInfoA EnumCalendarInfoExA
EnumCalendarInfoExEx EnumCalendarInfoExW EnumCalendarInfoW EnumDateFormatsA
EnumDateFormatsExA EnumDateFormatsExEx EnumDateFormatsExW EnumDateFormatsW
EnumLanguageGroupLocalesA EnumLanguageGroupLocalesW EnumResourceLanguagesA
EnumResourceLanguagesExA EnumResourceLanguagesExW EnumResourceLanguagesW
EnumResourceNamesA EnumResourceNamesExA EnumResourceNamesExW
EnumResourceNamesW EnumResourceTypesA EnumResourceTypesExA
EnumResourceTypesExW EnumResourceTypesW EnumSystemCodePagesA
EnumSystemCodePagesW EnumSystemFirmwareTables EnumSystemGeoID
EnumSystemGeoNames EnumSystemLanguageGroupsA EnumSystemLanguageGroupsW
EnumSystemLocalesA EnumSystemLocalesEx EnumSystemLocalesW EnumTimeFormatsA
EnumTimeFormatsEx EnumTimeFormatsW EnumUILanguagesA EnumUILanguagesW
EnumerateLocalComputerNamesA EnumerateLocalComputerNamesW EraseTape
EscapeCommFunction ExecuteUmsThread ExitProcess ExitThread ExitVDM
ExpandEnvironmentStringsA ExpandEnvironmentStringsW
ExpungeConsoleCommandHistoryA ExpungeConsoleCommandHistoryW FatalAppExitA
FatalAppExitW FatalExit FileTimeToDosDateTime FileTimeToLocalFileTime
FileTimeToSystemTime FillConsoleOutputAttribute FillConsoleOutputCharacterA
FillConsoleOutputCharacterW FindActCtxSectionGuid
FindActCtxSectionGuidWorker FindActCtxSectionStringA
FindActCtxSectionStringW FindActCtxSectionStringWWorker FindAtomA FindAtomW
FindClose FindCloseChangeNotification FindFirstChangeNotificationA
FindFirstChangeNotificationW FindFirstFileA FindFirstFileExA
FindFirstFileExW FindFirstFileNameTransactedW FindFirstFileNameW
FindFirstFileTransactedA FindFirstFileTransactedW FindFirstFileW
FindFirstStreamTransactedW FindFirstStreamW FindFirstVolumeA
FindFirstVolumeMountPointA FindFirstVolumeMountPointW FindFirstVolumeW
FindNLSString FindNLSStringEx FindNextChangeNotification FindNextFileA
FindNextFileNameW FindNextFileW FindNextStreamW FindNextVolumeA
FindNextVolumeMountPointA FindNextVolumeMountPointW FindNextVolumeW
FindPackagesByPackageFamily FindResourceA FindResourceExA FindResourceExW
FindResourceW FindStringOrdinal FindVolumeClose FindVolumeMountPointClose
FlsAlloc FlsFree FlsGetValue FlsSetValue FlushConsoleInputBuffer
FlushFileBuffers FlushInstructionCache FlushProcessWriteBuffers
FlushViewOfFile FoldStringA FoldStringW FormatApplicationUserModelId
FormatMessageA FormatMessageW FreeConsole FreeEnvironmentStringsA
FreeEnvironmentStringsW FreeLibrary FreeLibraryAndExitThread
FreeLibraryWhenCallbackReturns FreeMemoryJobObject FreeResource
FreeUserPhysicalPages GenerateConsoleCtrlEvent GetACP
GetActiveProcessorCount GetActiveProcessorGroupCount GetAppContainerAce
GetAppContainerNamedObjectPath GetApplicationRecoveryCallback
GetApplicationRecoveryCallbackWorker GetApplicationRestartSettings
GetApplicationRestartSettingsWorker GetApplicationUserModelId GetAtomNameA
GetAtomNameW GetBinaryType GetBinaryTypeA GetBinaryTypeW
GetCPFileNameFromRegistry GetCPInfo GetCPInfoExA GetCPInfoExW
GetCachedSigningLevel GetCalendarDateFormat GetCalendarDateFormatEx
GetCalendarDaysInMonth GetCalendarDifferenceInDays GetCalendarInfoA
GetCalendarInfoEx GetCalendarInfoW GetCalendarMonthsInYear
GetCalendarSupportedDateRange GetCalendarWeekNumber
GetComPlusPackageInstallStatus GetCommConfig GetCommMask GetCommModemStatus
GetCommProperties GetCommState GetCommTimeouts GetCommandLineA
GetCommandLineW GetCompressedFileSizeA GetCompressedFileSizeTransactedA
GetCompressedFileSizeTransactedW GetCompressedFileSizeW GetComputerNameA
GetComputerNameExA GetComputerNameExW GetComputerNameW GetConsoleAliasA
GetConsoleAliasExesA GetConsoleAliasExesLengthA GetConsoleAliasExesLengthW
GetConsoleAliasExesW GetConsoleAliasW GetConsoleAliasesA
GetConsoleAliasesLengthA GetConsoleAliasesLengthW GetConsoleAliasesW
GetConsoleCP GetConsoleCharType GetConsoleCommandHistoryA
GetConsoleCommandHistoryLengthA GetConsoleCommandHistoryLengthW
GetConsoleCommandHistoryW GetConsoleCursorInfo GetConsoleCursorMode
GetConsoleDisplayMode GetConsoleFontInfo GetConsoleFontSize
GetConsoleHardwareState GetConsoleHistoryInfo GetConsoleInputExeNameA
GetConsoleInputExeNameW GetConsoleInputWaitHandle
GetConsoleKeyboardLayoutNameA GetConsoleKeyboardLayoutNameW GetConsoleMode
GetConsoleNlsMode GetConsoleOriginalTitleA GetConsoleOriginalTitleW
GetConsoleOutputCP GetConsoleProcessList GetConsoleScreenBufferInfo
GetConsoleScreenBufferInfoEx GetConsoleSelectionInfo GetConsoleTitleA
GetConsoleTitleW GetConsoleWindow GetCurrencyFormatA GetCurrencyFormatEx
GetCurrencyFormatW GetCurrentActCtx GetCurrentActCtxWorker
GetCurrentApplicationUserModelId GetCurrentConsoleFont
GetCurrentConsoleFontEx GetCurrentDirectoryA GetCurrentDirectoryW
GetCurrentPackageFamilyName GetCurrentPackageFullName GetCurrentPackageId
GetCurrentPackageInfo GetCurrentPackagePath GetCurrentProcess
GetCurrentProcessId GetCurrentProcessorNumber GetCurrentProcessorNumberEx
GetCurrentThread GetCurrentThreadId GetCurrentThreadStackLimits
GetCurrentUmsThread GetDateFormatA GetDateFormatAWorker GetDateFormatEx
GetDateFormatW GetDateFormatWWorker GetDefaultCommConfigA
GetDefaultCommConfigW GetDefaultSortkeySize GetDevicePowerState
GetDiskFreeSpaceA GetDiskFreeSpaceExA GetDiskFreeSpaceExW GetDiskFreeSpaceW
GetDiskSpaceInformationA GetDiskSpaceInformationW GetDllDirectoryA
GetDllDirectoryW GetDriveTypeA GetDriveTypeW GetDurationFormat
GetDurationFormatEx GetDynamicTimeZoneInformation GetEnabledExtendedFeatures
GetEnabledXStateFeatures GetEncryptedFileVersionExt GetEnvironmentStrings
GetEnvironmentStringsA GetEnvironmentStringsW GetEnvironmentVariableA
GetEnvironmentVariableW GetEraNameCountedString GetErrorMode
GetExitCodeProcess GetExitCodeThread GetExpandedNameA GetExpandedNameW
GetExtendedContextLength GetExtendedFeaturesMask GetFileAttributesA
GetFileAttributesExA GetFileAttributesExW GetFileAttributesTransactedA
GetFileAttributesTransactedW GetFileAttributesW GetFileBandwidthReservation
GetFileInformationByHandle GetFileInformationByHandleEx GetFileMUIInfo
GetFileMUIPath GetFileSize GetFileSizeEx GetFileTime GetFileType
GetFinalPathNameByHandleA GetFinalPathNameByHandleW
GetFirmwareEnvironmentVariableA GetFirmwareEnvironmentVariableExA
GetFirmwareEnvironmentVariableExW GetFirmwareEnvironmentVariableW
GetFirmwareType GetFullPathNameA GetFullPathNameTransactedA
GetFullPathNameTransactedW GetFullPathNameW GetGeoInfoA GetGeoInfoEx
GetGeoInfoW GetHandleInformation GetLargePageMinimum
GetLargestConsoleWindowSize GetLastError GetLinguistLangSize GetLocalTime
GetLocaleInfoA GetLocaleInfoEx GetLocaleInfoW GetLogicalDriveStringsA
GetLogicalDriveStringsW GetLogicalDrives GetLogicalProcessorInformation
GetLogicalProcessorInformationEx GetLongPathNameA GetLongPathNameTransactedA
GetLongPathNameTransactedW GetLongPathNameW GetMailslotInfo
GetMaximumProcessorCount GetMaximumProcessorGroupCount
GetMemoryErrorHandlingCapabilities GetModuleFileNameA GetModuleFileNameW
GetModuleHandleA GetModuleHandleExA GetModuleHandleExW GetModuleHandleW
GetNLSVersion GetNLSVersionEx GetNamedPipeAttribute
GetNamedPipeClientComputerNameA GetNamedPipeClientComputerNameW
GetNamedPipeClientProcessId GetNamedPipeClientSessionId
GetNamedPipeHandleStateA GetNamedPipeHandleStateW GetNamedPipeInfo
GetNamedPipeServerProcessId GetNamedPipeServerSessionId GetNativeSystemInfo
GetNextUmsListItem GetNextVDMCommand GetNlsSectionName
GetNumaAvailableMemoryNode GetNumaAvailableMemoryNodeEx
GetNumaHighestNodeNumber GetNumaNodeNumberFromHandle
GetNumaNodeProcessorMask GetNumaNodeProcessorMaskEx GetNumaProcessorNode
GetNumaProcessorNodeEx GetNumaProximityNode GetNumaProximityNodeEx
GetNumberFormatA GetNumberFormatEx GetNumberFormatW GetNumberOfConsoleFonts
GetNumberOfConsoleInputEvents GetNumberOfConsoleMouseButtons GetOEMCP
GetOverlappedResult GetOverlappedResultEx GetPackageApplicationIds
GetPackageFamilyName GetPackageFullName GetPackageId GetPackageInfo
GetPackagePath GetPackagePathByFullName GetPackagesByPackageFamily
GetPhysicallyInstalledSystemMemory GetPriorityClass GetPrivateProfileIntA
GetPrivateProfileIntW GetPrivateProfileSectionA
GetPrivateProfileSectionNamesA GetPrivateProfileSectionNamesW
GetPrivateProfileSectionW GetPrivateProfileStringA GetPrivateProfileStringW
GetPrivateProfileStructA GetPrivateProfileStructW GetProcAddress
GetProcessAffinityMask GetProcessDEPPolicy GetProcessDefaultCpuSets
GetProcessGroupAffinity GetProcessHandleCount GetProcessHeap GetProcessHeaps
GetProcessId GetProcessIdOfThread GetProcessInformation GetProcessIoCounters
GetProcessMitigationPolicy GetProcessPreferredUILanguages
GetProcessPriorityBoost GetProcessShutdownParameters GetProcessTimes
GetProcessVersion GetProcessWorkingSetSize GetProcessWorkingSetSizeEx
GetProcessorSystemCycleTime GetProductInfo GetProfileIntA GetProfileIntW
GetProfileSectionA GetProfileSectionW GetProfileStringA GetProfileStringW
GetQueuedCompletionStatus GetQueuedCompletionStatusEx GetShortPathNameA
GetShortPathNameW GetStagedPackagePathByFullName GetStartupInfoA
GetStartupInfoW GetStateFolder GetStdHandle GetStringScripts GetStringTypeA
GetStringTypeExA GetStringTypeExW GetStringTypeW GetSystemAppDataKey
GetSystemCpuSetInformation GetSystemDEPPolicy GetSystemDefaultLCID
GetSystemDefaultLangID GetSystemDefaultLocaleName GetSystemDefaultUILanguage
GetSystemDirectoryA GetSystemDirectoryW GetSystemFileCacheSize
GetSystemFirmwareTable GetSystemInfo GetSystemPowerStatus
GetSystemPreferredUILanguages GetSystemRegistryQuota GetSystemTime
GetSystemTimeAdjustment GetSystemTimeAsFileTime
GetSystemTimePreciseAsFileTime GetSystemTimes GetSystemWindowsDirectoryA
GetSystemWindowsDirectoryW GetSystemWow64DirectoryA GetSystemWow64DirectoryW
GetTapeParameters GetTapePosition GetTapeStatus GetTempFileNameA
GetTempFileNameW GetTempPathA GetTempPathW GetThreadContext
GetThreadDescription GetThreadErrorMode GetThreadGroupAffinity
GetThreadIOPendingFlag GetThreadId GetThreadIdealProcessorEx
GetThreadInformation GetThreadLocale GetThreadPreferredUILanguages
GetThreadPriority GetThreadPriorityBoost GetThreadSelectedCpuSets
GetThreadSelectorEntry GetThreadTimes GetThreadUILanguage GetTickCount
GetTickCount64 GetTimeFormatA GetTimeFormatAWorker GetTimeFormatEx
GetTimeFormatW GetTimeFormatWWorker GetTimeZoneInformation
GetTimeZoneInformationForYear GetUILanguageInfo GetUmsCompletionListEvent
GetUmsSystemThreadInformation GetUserDefaultGeoName GetUserDefaultLCID
GetUserDefaultLangID GetUserDefaultLocaleName GetUserDefaultUILanguage
GetUserGeoID GetUserPreferredUILanguages GetVDMCurrentDirectories GetVersion
GetVersionExA GetVersionExW GetVolumeInformationA
GetVolumeInformationByHandleW GetVolumeInformationW
GetVolumeNameForVolumeMountPointA GetVolumeNameForVolumeMountPointW
GetVolumePathNameA GetVolumePathNameW GetVolumePathNamesForVolumeNameA
GetVolumePathNamesForVolumeNameW GetWindowsDirectoryA GetWindowsDirectoryW
GetWriteWatch GetXStateFeaturesMask GlobalAddAtomA GlobalAddAtomExA
GlobalAddAtomExW GlobalAddAtomW GlobalAlloc GlobalCompact GlobalDeleteAtom
GlobalFindAtomA GlobalFindAtomW GlobalFix GlobalFlags GlobalFree
GlobalGetAtomNameA GlobalGetAtomNameW GlobalHandle GlobalLock
GlobalMemoryStatus GlobalMemoryStatusEx GlobalReAlloc GlobalSize
GlobalUnWire GlobalUnfix GlobalUnlock GlobalWire Heap32First Heap32ListFirst
Heap32ListNext Heap32Next HeapAlloc HeapCompact HeapCreate HeapCreateTagsW
HeapDestroy HeapExtend HeapFree HeapLock HeapQueryInformation HeapQueryTagW
HeapReAlloc HeapSetInformation HeapSize HeapSummary HeapUnlock HeapUsage
HeapValidate HeapWalk IdnToAscii IdnToNameprepUnicode IdnToUnicode
InitAtomTable InitOnceBeginInitialize InitOnceComplete InitOnceExecuteOnce
InitOnceInitialize InitializeConditionVariable InitializeContext
InitializeContext2 InitializeCriticalSection
InitializeCriticalSectionAndSpinCount InitializeCriticalSectionEx
InitializeEnclave InitializeExtendedContext
InitializeProcThreadAttributeList InitializeSListHead InitializeSRWLock
InitializeSynchronizationBarrier InstallELAMCertificateInfo
InterlockedFlushSList InterlockedPopEntrySList InterlockedPushEntrySList
InterlockedPushListSList InterlockedPushListSListEx InvalidateConsoleDIBits
IsBadCodePtr IsBadHugeReadPtr IsBadHugeWritePtr IsBadReadPtr IsBadStringPtrA
IsBadStringPtrW IsBadWritePtr IsCalendarLeapDay IsCalendarLeapMonth
IsCalendarLeapYear IsDBCSLeadByte IsDBCSLeadByteEx IsDebuggerPresent
IsEnclaveTypeSupported IsNLSDefinedString IsNativeVhdBoot IsNormalizedString
IsProcessCritical IsProcessInJob IsProcessorFeaturePresent
IsSystemResumeAutomatic IsThreadAFiber IsThreadpoolTimerSet
IsTimeZoneRedirectionEnabled IsValidCalDateTime IsValidCodePage
IsValidLanguageGroup IsValidLocale IsValidLocaleName IsValidNLSVersion
IsValidUILanguage IsWow64GuestMachineSupported IsWow64Process
IsWow64Process2 K32EmptyWorkingSet K32EnumDeviceDrivers K32EnumPageFilesA
K32EnumPageFilesW K32EnumProcessModules K32EnumProcessModulesEx
K32EnumProcesses K32GetDeviceDriverBaseNameA K32GetDeviceDriverBaseNameW
K32GetDeviceDriverFileNameA K32GetDeviceDriverFileNameW
K32GetMappedFileNameA K32GetMappedFileNameW K32GetModuleBaseNameA
K32GetModuleBaseNameW K32GetModuleFileNameExA K32GetModuleFileNameExW
K32GetModuleInformation K32GetPerformanceInfo K32GetProcessImageFileNameA
K32GetProcessImageFileNameW K32GetProcessMemoryInfo K32GetWsChanges
K32GetWsChangesEx K32InitializeProcessForWsWatch K32QueryWorkingSet
K32QueryWorkingSetEx LCIDToLocaleName LCMapStringA LCMapStringEx
LCMapStringW LZClose LZCloseFile LZCopy LZCreateFileW LZDone LZInit
LZOpenFileA LZOpenFileW LZRead LZSeek LZStart LeaveCriticalSection
LeaveCriticalSectionWhenCallbackReturns LoadAppInitDlls LoadEnclaveData
LoadLibraryA LoadLibraryExA LoadLibraryExW LoadLibraryW LoadModule
LoadPackagedLibrary LoadResource LoadStringBaseExW LoadStringBaseW
LocalAlloc LocalCompact LocalFileTimeToFileTime
LocalFileTimeToLocalSystemTime LocalFlags LocalFree LocalHandle LocalLock
LocalReAlloc LocalShrink LocalSize LocalSystemTimeToLocalFileTime
LocalUnlock LocaleNameToLCID LocateExtendedFeature LocateLegacyContext
LocateXStateFeature LockFile LockFileEx LockResource MapUserPhysicalPages
MapUserPhysicalPagesScatter MapViewOfFile MapViewOfFileEx
MapViewOfFileExNuma MapViewOfFileFromApp Module32First Module32FirstW
Module32Next Module32NextW MoveFileA MoveFileExA MoveFileExW
MoveFileTransactedA MoveFileTransactedW MoveFileW MoveFileWithProgressA
MoveFileWithProgressW MulDiv MultiByteToWideChar
NeedCurrentDirectoryForExePathA NeedCurrentDirectoryForExePathW
NlsCheckPolicy NlsConvertIntegerToString NlsEventDataDescCreate
NlsGetCacheUpdateCount NlsResetProcessLocale NlsUpdateLocale
NlsUpdateSystemLocale NlsWriteEtwEvent NormalizeString NotifyMountMgr
NotifyUILanguageChange NtVdm64CreateProcessInternalW OOBEComplete
OfferVirtualMemory OpenConsoleW OpenConsoleWStub OpenDataFile OpenEventA
OpenEventW OpenFile OpenFileById OpenFileMappingA OpenFileMappingW
OpenJobObjectA OpenJobObjectW OpenMutexA OpenMutexW
OpenPackageInfoByFullName OpenPrivateNamespaceA OpenPrivateNamespaceW
OpenProcess OpenProfileUserMapping OpenSemaphoreA OpenSemaphoreW OpenState
OpenStateExplicit OpenThread OpenWaitableTimerA OpenWaitableTimerW
OutputDebugStringA OutputDebugStringW PackageFamilyNameFromFullName
PackageFamilyNameFromId PackageFullNameFromId PackageIdFromFullName
PackageNameAndPublisherIdFromFamilyName ParseApplicationUserModelId
PeekConsoleInputA PeekConsoleInputW PeekNamedPipe PostQueuedCompletionStatus
PowerClearRequest PowerCreateRequest PowerSetRequest PrefetchVirtualMemory
PrepareTape PrivCopyFileExW PrivMoveFileIdentityW Process32First
Process32FirstW Process32Next Process32NextW ProcessIdToSessionId
PssCaptureSnapshot PssDuplicateSnapshot PssFreeSnapshot PssQuerySnapshot
PssWalkMarkerCreate PssWalkMarkerFree PssWalkMarkerGetPosition
PssWalkMarkerRewind PssWalkMarkerSeek PssWalkMarkerSeekToBeginning
PssWalkMarkerSetPosition PssWalkMarkerTell PssWalkSnapshot PulseEvent
PurgeComm QueryActCtxSettingsW QueryActCtxSettingsWWorker QueryActCtxW
QueryActCtxWWorker QueryDepthSList QueryDosDeviceA QueryDosDeviceW
QueryFullProcessImageNameA QueryFullProcessImageNameW
QueryIdleProcessorCycleTime QueryIdleProcessorCycleTimeEx
QueryInformationJobObject QueryIoRateControlInformationJobObject
QueryMemoryResourceNotification QueryPerformanceCounter
QueryPerformanceFrequency QueryProcessAffinityUpdateMode
QueryProcessCycleTime QueryProtectedPolicy QueryThreadCycleTime
QueryThreadProfiling QueryThreadpoolStackInformation
QueryUmsThreadInformation QueryUnbiasedInterruptTime QueueUserAPC
QueueUserWorkItem QuirkGetData2Worker QuirkGetDataWorker
QuirkIsEnabled2Worker QuirkIsEnabled3Worker QuirkIsEnabledForPackage2Worker
QuirkIsEnabledForPackage3Worker QuirkIsEnabledForPackage4Worker
QuirkIsEnabledForPackageWorker QuirkIsEnabledForProcessWorker
QuirkIsEnabledWorker RaiseException RaiseFailFastException
RaiseInvalid16BitExeError ReOpenFile ReadConsoleA ReadConsoleInputA
ReadConsoleInputExA ReadConsoleInputExW ReadConsoleInputW ReadConsoleOutputA
ReadConsoleOutputAttribute ReadConsoleOutputCharacterA
ReadConsoleOutputCharacterW ReadConsoleOutputW ReadConsoleW
ReadDirectoryChangesExW ReadDirectoryChangesW ReadFile ReadFileEx
ReadFileScatter ReadProcessMemory ReadThreadProfilingData
ReclaimVirtualMemory RegKrnGetGlobalState RegKrnInitialize
RegisterApplicationRecoveryCallback RegisterApplicationRestart
RegisterBadMemoryNotification RegisterConsoleIME RegisterConsoleOS2
RegisterConsoleVDM RegisterWaitForInputIdle RegisterWaitForSingleObject
RegisterWaitForSingleObjectEx RegisterWaitUntilOOBECompleted
RegisterWowBaseHandlers RegisterWowExec ReleaseActCtx ReleaseActCtxWorker
ReleaseMutex ReleaseMutexWhenCallbackReturns ReleaseSRWLockExclusive
ReleaseSRWLockShared ReleaseSemaphore ReleaseSemaphoreWhenCallbackReturns
RemoveDirectoryA RemoveDirectoryTransactedA RemoveDirectoryTransactedW
RemoveDirectoryW RemoveDllDirectory RemoveLocalAlternateComputerNameA
RemoveLocalAlternateComputerNameW RemoveSecureMemoryCacheCallback
RemoveVectoredContinueHandler RemoveVectoredExceptionHandler ReplaceFile
ReplaceFileA ReplaceFileW ReplacePartitionUnit RequestDeviceWakeup
RequestWakeupLatency ResetEvent ResetWriteWatch ResizePseudoConsole
ResolveDelayLoadedAPI ResolveDelayLoadsFromDll ResolveLocaleName
RestoreLastError ResumeThread RtlAddFunctionTable RtlCaptureContext
RtlCaptureStackBackTrace RtlCompareMemory RtlCopyMemory
RtlDeleteFunctionTable RtlFillMemory RtlInstallFunctionTableCallback
RtlLookupFunctionEntry RtlMoveMemory RtlPcToFileHeader RtlRaiseException
RtlRestoreContext RtlUnwind RtlUnwindEx RtlVirtualUnwind RtlZeroMemory
ScrollConsoleScreenBufferA ScrollConsoleScreenBufferW SearchPathA
SearchPathW SetCPGlobal SetCachedSigningLevel SetCalendarInfoA
SetCalendarInfoW SetComPlusPackageInstallStatus SetCommBreak SetCommConfig
SetCommMask SetCommState SetCommTimeouts SetComputerNameA
SetComputerNameEx2W SetComputerNameExA SetComputerNameExW SetComputerNameW
SetConsoleActiveScreenBuffer SetConsoleCP SetConsoleCommandHistoryMode
SetConsoleCtrlHandler SetConsoleCursor SetConsoleCursorInfo
SetConsoleCursorMode SetConsoleCursorPosition SetConsoleDisplayMode
SetConsoleFont SetConsoleHardwareState SetConsoleHistoryInfo SetConsoleIcon
SetConsoleInputExeNameA SetConsoleInputExeNameW SetConsoleKeyShortcuts
SetConsoleLocalEUDC SetConsoleMaximumWindowSize SetConsoleMenuClose
SetConsoleMode SetConsoleNlsMode SetConsoleNumberOfCommandsA
SetConsoleNumberOfCommandsW SetConsoleOS2OemFormat SetConsoleOutputCP
SetConsolePalette SetConsoleScreenBufferInfoEx SetConsoleScreenBufferSize
SetConsoleTextAttribute SetConsoleTitleA SetConsoleTitleW
SetConsoleWindowInfo SetCriticalSectionSpinCount SetCurrentConsoleFontEx
SetCurrentDirectoryA SetCurrentDirectoryW SetDefaultCommConfigA
SetDefaultCommConfigW SetDefaultDllDirectories SetDllDirectoryA
SetDllDirectoryW SetDynamicTimeZoneInformation SetEndOfFile
SetEnvironmentStringsA SetEnvironmentStringsW SetEnvironmentVariableA
SetEnvironmentVariableW SetErrorMode SetEvent SetEventWhenCallbackReturns
SetExtendedFeaturesMask SetFileApisToANSI SetFileApisToOEM
SetFileAttributesA SetFileAttributesTransactedA SetFileAttributesTransactedW
SetFileAttributesW SetFileBandwidthReservation
SetFileCompletionNotificationModes SetFileInformationByHandle
SetFileIoOverlappedRange SetFilePointer SetFilePointerEx SetFileShortNameA
SetFileShortNameW SetFileTime SetFileValidData
SetFirmwareEnvironmentVariableA SetFirmwareEnvironmentVariableExA
SetFirmwareEnvironmentVariableExW SetFirmwareEnvironmentVariableW
SetHandleCount SetHandleInformation SetInformationJobObject
SetIoRateControlInformationJobObject SetLastConsoleEventActive SetLastError
SetLocalPrimaryComputerNameA SetLocalPrimaryComputerNameW SetLocalTime
SetLocaleInfoA SetLocaleInfoW SetMailslotInfo SetMessageWaitingIndicator
SetNamedPipeAttribute SetNamedPipeHandleState SetPriorityClass
SetProcessAffinityMask SetProcessAffinityUpdateMode SetProcessDEPPolicy
SetProcessDefaultCpuSets SetProcessInformation SetProcessMitigationPolicy
SetProcessPreferredUILanguages SetProcessPriorityBoost
SetProcessShutdownParameters SetProcessWorkingSetSize
SetProcessWorkingSetSizeEx SetProtectedPolicy SetSearchPathMode SetStdHandle
SetStdHandleEx SetSystemFileCacheSize SetSystemPowerState SetSystemTime
SetSystemTimeAdjustment SetTapeParameters SetTapePosition
SetTermsrvAppInstallMode SetThreadAffinityMask SetThreadContext
SetThreadDescription SetThreadErrorMode SetThreadExecutionState
SetThreadGroupAffinity SetThreadIdealProcessor SetThreadIdealProcessorEx
SetThreadInformation SetThreadLocale SetThreadPreferredUILanguages
SetThreadPriority SetThreadPriorityBoost SetThreadSelectedCpuSets
SetThreadStackGuarantee SetThreadUILanguage SetThreadpoolStackInformation
SetThreadpoolThreadMaximum SetThreadpoolThreadMinimum SetThreadpoolTimer
SetThreadpoolTimerEx SetThreadpoolWait SetThreadpoolWaitEx
SetTimeZoneInformation SetTimerQueueTimer SetUmsThreadInformation
SetUnhandledExceptionFilter SetUserGeoID SetUserGeoName
SetVDMCurrentDirectories SetVolumeLabelA SetVolumeLabelW
SetVolumeMountPointA SetVolumeMountPointW SetVolumeMountPointWStub
SetWaitableTimer SetWaitableTimerEx SetXStateFeaturesMask SetupComm
ShowConsoleCursor SignalObjectAndWait SizeofResource Sleep
SleepConditionVariableCS SleepConditionVariableSRW SleepEx SortCloseHandle
SortGetHandle StartThreadpoolIo SubmitThreadpoolWork SuspendThread
SwitchToFiber SwitchToThread SystemTimeToFileTime
SystemTimeToTzSpecificLocalTime SystemTimeToTzSpecificLocalTimeEx
TerminateJobObject TerminateProcess TerminateThread TermsrvAppInstallMode
TermsrvConvertSysRootToUserDir TermsrvCreateRegEntry TermsrvDeleteKey
TermsrvDeleteValue TermsrvGetPreSetValue TermsrvGetWindowsDirectoryA
TermsrvGetWindowsDirectoryW TermsrvOpenRegEntry TermsrvOpenUserClasses
TermsrvRestoreKey TermsrvSetKeySecurity TermsrvSetValueKey
TermsrvSyncUserIniFileExt Thread32First Thread32Next TlsAlloc TlsFree
TlsGetValue TlsSetValue Toolhelp32ReadProcessMemory TransactNamedPipe
TransmitCommChar TryAcquireSRWLockExclusive TryAcquireSRWLockShared
TryEnterCriticalSection TrySubmitThreadpoolCallback
TzSpecificLocalTimeToSystemTime TzSpecificLocalTimeToSystemTimeEx UTRegister
UTUnRegister UmsThreadYield UnhandledExceptionFilter UnlockFile UnlockFileEx
UnmapViewOfFile UnmapViewOfFileEx UnregisterApplicationRecoveryCallback
UnregisterApplicationRestart UnregisterBadMemoryNotification
UnregisterConsoleIME UnregisterWait UnregisterWaitEx
UnregisterWaitUntilOOBECompleted UpdateCalendarDayOfWeek
UpdateProcThreadAttribute UpdateResourceA UpdateResourceW
VDMConsoleOperation VDMOperationStarted ValidateLCType ValidateLocale
VerLanguageNameA VerLanguageNameW VerSetConditionMask VerifyConsoleIoHandle
VerifyScripts VerifyVersionInfoA VerifyVersionInfoW VirtualAlloc
VirtualAllocEx VirtualAllocExNuma VirtualFree VirtualFreeEx VirtualLock
VirtualProtect VirtualProtectEx VirtualQuery VirtualQueryEx VirtualUnlock
WTSGetActiveConsoleSessionId WaitCommEvent WaitForDebugEvent
WaitForDebugEventEx WaitForMultipleObjects WaitForMultipleObjectsEx
WaitForSingleObject WaitForSingleObjectEx WaitForThreadpoolIoCallbacks
WaitForThreadpoolTimerCallbacks WaitForThreadpoolWaitCallbacks
WaitForThreadpoolWorkCallbacks WaitNamedPipeA WaitNamedPipeW
WakeAllConditionVariable WakeConditionVariable WerGetFlags WerGetFlagsWorker
WerRegisterAdditionalProcess WerRegisterAppLocalDump
WerRegisterCustomMetadata WerRegisterExcludedMemoryBlock WerRegisterFile
WerRegisterFileWorker WerRegisterMemoryBlock WerRegisterMemoryBlockWorker
WerRegisterRuntimeExceptionModule WerRegisterRuntimeExceptionModuleWorker
WerSetFlags WerSetFlagsWorker WerUnregisterAdditionalProcess
WerUnregisterAppLocalDump WerUnregisterCustomMetadata
WerUnregisterExcludedMemoryBlock WerUnregisterFile WerUnregisterFileWorker
WerUnregisterMemoryBlock WerUnregisterMemoryBlockWorker
WerUnregisterRuntimeExceptionModule
WerUnregisterRuntimeExceptionModuleWorker WerpCleanupMessageMapping
WerpGetDebugger WerpInitiateRemoteRecovery WerpLaunchAeDebug
WerpNotifyLoadStringResource WerpNotifyLoadStringResourceEx
WerpNotifyLoadStringResourceWorker WerpNotifyUseStringResource
WerpNotifyUseStringResourceWorker WerpStringLookup WideCharToMultiByte
WinExec Wow64DisableWow64FsRedirection Wow64EnableWow64FsRedirection
Wow64GetThreadContext Wow64GetThreadSelectorEntry
Wow64RevertWow64FsRedirection Wow64SetThreadContext Wow64SuspendThread
WriteConsoleA WriteConsoleInputA WriteConsoleInputVDMA WriteConsoleInputVDMW
WriteConsoleInputW WriteConsoleOutputA WriteConsoleOutputAttribute
WriteConsoleOutputCharacterA WriteConsoleOutputCharacterW
WriteConsoleOutputW WriteConsoleW WriteFile WriteFileEx WriteFileGather
WritePrivateProfileSectionA WritePrivateProfileSectionW
WritePrivateProfileStringA WritePrivateProfileStringW
WritePrivateProfileStructA WritePrivateProfileStructW WriteProcessMemory
WriteProfileSectionA WriteProfileSectionW WriteProfileStringA
WriteProfileStringW WriteTapemark ZombifyActCtx ZombifyActCtxWorker
__misaligned_access _hread _hwrite _lclose _lcreat _llseek _lopen _lread
_lwrite lstrcat lstrcatA lstrcatW lstrcmp lstrcmpA lstrcmpW lstrcmpi
lstrcmpiA lstrcmpiW lstrcpy lstrcpyA lstrcpyW lstrcpyn lstrcpynA lstrcpynW
lstrlen lstrlenA lstrlenW uaw_lstrcmpW uaw_lstrcmpiW uaw_lstrlenW uaw_wcschr
uaw_wcscpy uaw_wcsicmp uaw_wcslen uaw_wcsrchr
"""

# DLL name -> (function names, data names), in search order. msvcrt comes
# first: the two names both export (__C_specific_handler, _local_unwind) are
# the C runtime's.
_TABLES = [("msvcrt.dll", MSVCRT_FUNCS, MSVCRT_DATA),
           ("KERNEL32.dll", KERNEL32_FUNCS, "")]

_index = None


def _build():
    idx = {}
    for dll, funcs, data in _TABLES:
        for n in funcs.split():
            if n not in idx:
                idx[n] = (dll, False)
        for n in data.split():
            if n not in idx:
                idx[n] = (dll, True)
    return idx


def lookup(name):
    """(dll, is_data) for an exported symbol, or None if no known DLL has
    it."""
    global _index
    if _index is None:
        _index = _build()
    return _index.get(name, None)


def default_dlls():
    """The DLLs searched when a program does not name any."""
    return [t[0] for t in _TABLES]
