/* WebAssembly SIMD intrinsics.
 *
 *     #include <wasm_simd128.h>
 *
 * Under --target wasm each intrinsic becomes the single SIMD
 * instruction it names. Under any other target the same calls
 * compile to portable scalar C, so a program using them builds and
 * runs anywhere -- which is what lets an ordinary compiler act as
 * the oracle when checking the vector code.
 *
 * GENERATED by tools/gen_wasm_simd128.py from shivyc/wasm_simd.py.
 * Edit the generator, not this file.
 */
#ifndef _WASM_SIMD128_H
#define _WASM_SIMD128_H

/* A vector is sixteen bytes. It is a struct rather than a builtin
 * type because the front end has no vector type: aggregates already
 * live in memory and are passed by address, which is what a v128
 * needs anyway. */
typedef struct { unsigned char __v[16]; } v128_t;

#ifdef __wasm__

/* Every operator the back end can emit, including the ones with no
 * scalar fallback below. */
v128_t __builtin_wasm_v128_load(int);
v128_t __builtin_wasm_v128_load8x8_s(int);
v128_t __builtin_wasm_v128_load8x8_u(int);
v128_t __builtin_wasm_v128_load16x4_s(int);
v128_t __builtin_wasm_v128_load16x4_u(int);
v128_t __builtin_wasm_v128_load32x2_s(int);
v128_t __builtin_wasm_v128_load32x2_u(int);
v128_t __builtin_wasm_v128_load8_splat(int);
v128_t __builtin_wasm_v128_load16_splat(int);
v128_t __builtin_wasm_v128_load32_splat(int);
v128_t __builtin_wasm_v128_load64_splat(int);
void __builtin_wasm_v128_store(int, v128_t);
v128_t __builtin_wasm_i8x16_swizzle(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_splat(int);
v128_t __builtin_wasm_i16x8_splat(int);
v128_t __builtin_wasm_i32x4_splat(int);
v128_t __builtin_wasm_i64x2_splat(long);
v128_t __builtin_wasm_f32x4_splat(float);
v128_t __builtin_wasm_f64x2_splat(double);
int __builtin_wasm_i8x16_extract_lane_s(v128_t, int);
int __builtin_wasm_i8x16_extract_lane_u(v128_t, int);
v128_t __builtin_wasm_i8x16_replace_lane(v128_t, int, int);
int __builtin_wasm_i16x8_extract_lane_s(v128_t, int);
int __builtin_wasm_i16x8_extract_lane_u(v128_t, int);
v128_t __builtin_wasm_i16x8_replace_lane(v128_t, int, int);
int __builtin_wasm_i32x4_extract_lane(v128_t, int);
v128_t __builtin_wasm_i32x4_replace_lane(v128_t, int, int);
long __builtin_wasm_i64x2_extract_lane(v128_t, int);
v128_t __builtin_wasm_i64x2_replace_lane(v128_t, long, int);
float __builtin_wasm_f32x4_extract_lane(v128_t, int);
v128_t __builtin_wasm_f32x4_replace_lane(v128_t, float, int);
double __builtin_wasm_f64x2_extract_lane(v128_t, int);
v128_t __builtin_wasm_f64x2_replace_lane(v128_t, double, int);
v128_t __builtin_wasm_i8x16_eq(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_ne(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_lt_s(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_lt_u(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_gt_s(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_gt_u(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_le_s(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_le_u(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_ge_s(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_ge_u(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_eq(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_ne(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_lt_s(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_lt_u(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_gt_s(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_gt_u(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_le_s(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_le_u(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_ge_s(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_ge_u(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_eq(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_ne(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_lt_s(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_lt_u(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_gt_s(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_gt_u(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_le_s(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_le_u(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_ge_s(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_ge_u(v128_t, v128_t);
v128_t __builtin_wasm_f32x4_eq(v128_t, v128_t);
v128_t __builtin_wasm_f32x4_ne(v128_t, v128_t);
v128_t __builtin_wasm_f32x4_lt(v128_t, v128_t);
v128_t __builtin_wasm_f32x4_gt(v128_t, v128_t);
v128_t __builtin_wasm_f32x4_le(v128_t, v128_t);
v128_t __builtin_wasm_f32x4_ge(v128_t, v128_t);
v128_t __builtin_wasm_f64x2_eq(v128_t, v128_t);
v128_t __builtin_wasm_f64x2_ne(v128_t, v128_t);
v128_t __builtin_wasm_f64x2_lt(v128_t, v128_t);
v128_t __builtin_wasm_f64x2_gt(v128_t, v128_t);
v128_t __builtin_wasm_f64x2_le(v128_t, v128_t);
v128_t __builtin_wasm_f64x2_ge(v128_t, v128_t);
v128_t __builtin_wasm_v128_not(v128_t);
v128_t __builtin_wasm_v128_and(v128_t, v128_t);
v128_t __builtin_wasm_v128_andnot(v128_t, v128_t);
v128_t __builtin_wasm_v128_or(v128_t, v128_t);
v128_t __builtin_wasm_v128_xor(v128_t, v128_t);
v128_t __builtin_wasm_v128_bitselect(v128_t, v128_t, v128_t);
int __builtin_wasm_v128_any_true(v128_t);
v128_t __builtin_wasm_v128_load32_zero(int);
v128_t __builtin_wasm_v128_load64_zero(int);
v128_t __builtin_wasm_f32x4_demote_f64x2_zero(v128_t);
v128_t __builtin_wasm_f64x2_promote_low_f32x4(v128_t);
v128_t __builtin_wasm_i8x16_abs(v128_t);
v128_t __builtin_wasm_i8x16_neg(v128_t);
v128_t __builtin_wasm_i8x16_popcnt(v128_t);
int __builtin_wasm_i8x16_all_true(v128_t);
int __builtin_wasm_i8x16_bitmask(v128_t);
v128_t __builtin_wasm_i8x16_narrow_i16x8_s(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_narrow_i16x8_u(v128_t, v128_t);
v128_t __builtin_wasm_f32x4_ceil(v128_t);
v128_t __builtin_wasm_f32x4_floor(v128_t);
v128_t __builtin_wasm_f32x4_trunc(v128_t);
v128_t __builtin_wasm_f32x4_nearest(v128_t);
v128_t __builtin_wasm_i8x16_shl(v128_t, int);
v128_t __builtin_wasm_i8x16_shr_s(v128_t, int);
v128_t __builtin_wasm_i8x16_shr_u(v128_t, int);
v128_t __builtin_wasm_i8x16_add(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_add_sat_s(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_add_sat_u(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_sub(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_sub_sat_s(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_sub_sat_u(v128_t, v128_t);
v128_t __builtin_wasm_f64x2_ceil(v128_t);
v128_t __builtin_wasm_f64x2_floor(v128_t);
v128_t __builtin_wasm_i8x16_min_s(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_min_u(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_max_s(v128_t, v128_t);
v128_t __builtin_wasm_i8x16_max_u(v128_t, v128_t);
v128_t __builtin_wasm_f64x2_trunc(v128_t);
v128_t __builtin_wasm_i8x16_avgr_u(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_extadd_pairwise_i8x16_s(v128_t);
v128_t __builtin_wasm_i16x8_extadd_pairwise_i8x16_u(v128_t);
v128_t __builtin_wasm_i32x4_extadd_pairwise_i16x8_s(v128_t);
v128_t __builtin_wasm_i32x4_extadd_pairwise_i16x8_u(v128_t);
v128_t __builtin_wasm_i16x8_abs(v128_t);
v128_t __builtin_wasm_i16x8_neg(v128_t);
v128_t __builtin_wasm_i16x8_q15mulr_sat_s(v128_t, v128_t);
int __builtin_wasm_i16x8_all_true(v128_t);
int __builtin_wasm_i16x8_bitmask(v128_t);
v128_t __builtin_wasm_i16x8_narrow_i32x4_s(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_narrow_i32x4_u(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_extend_low_i8x16_s(v128_t);
v128_t __builtin_wasm_i16x8_extend_high_i8x16_s(v128_t);
v128_t __builtin_wasm_i16x8_extend_low_i8x16_u(v128_t);
v128_t __builtin_wasm_i16x8_extend_high_i8x16_u(v128_t);
v128_t __builtin_wasm_i16x8_shl(v128_t, int);
v128_t __builtin_wasm_i16x8_shr_s(v128_t, int);
v128_t __builtin_wasm_i16x8_shr_u(v128_t, int);
v128_t __builtin_wasm_i16x8_add(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_add_sat_s(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_add_sat_u(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_sub(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_sub_sat_s(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_sub_sat_u(v128_t, v128_t);
v128_t __builtin_wasm_f64x2_nearest(v128_t);
v128_t __builtin_wasm_i16x8_mul(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_min_s(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_min_u(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_max_s(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_max_u(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_avgr_u(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_extmul_low_i8x16_s(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_extmul_high_i8x16_s(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_extmul_low_i8x16_u(v128_t, v128_t);
v128_t __builtin_wasm_i16x8_extmul_high_i8x16_u(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_abs(v128_t);
v128_t __builtin_wasm_i32x4_neg(v128_t);
int __builtin_wasm_i32x4_all_true(v128_t);
int __builtin_wasm_i32x4_bitmask(v128_t);
v128_t __builtin_wasm_i32x4_extend_low_i16x8_s(v128_t);
v128_t __builtin_wasm_i32x4_extend_high_i16x8_s(v128_t);
v128_t __builtin_wasm_i32x4_extend_low_i16x8_u(v128_t);
v128_t __builtin_wasm_i32x4_extend_high_i16x8_u(v128_t);
v128_t __builtin_wasm_i32x4_shl(v128_t, int);
v128_t __builtin_wasm_i32x4_shr_s(v128_t, int);
v128_t __builtin_wasm_i32x4_shr_u(v128_t, int);
v128_t __builtin_wasm_i32x4_add(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_sub(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_mul(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_min_s(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_min_u(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_max_s(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_max_u(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_dot_i16x8_s(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_extmul_low_i16x8_s(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_extmul_high_i16x8_s(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_extmul_low_i16x8_u(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_extmul_high_i16x8_u(v128_t, v128_t);
v128_t __builtin_wasm_i64x2_abs(v128_t);
v128_t __builtin_wasm_i64x2_neg(v128_t);
int __builtin_wasm_i64x2_all_true(v128_t);
int __builtin_wasm_i64x2_bitmask(v128_t);
v128_t __builtin_wasm_i64x2_extend_low_i32x4_s(v128_t);
v128_t __builtin_wasm_i64x2_extend_high_i32x4_s(v128_t);
v128_t __builtin_wasm_i64x2_extend_low_i32x4_u(v128_t);
v128_t __builtin_wasm_i64x2_extend_high_i32x4_u(v128_t);
v128_t __builtin_wasm_i64x2_shl(v128_t, int);
v128_t __builtin_wasm_i64x2_shr_s(v128_t, int);
v128_t __builtin_wasm_i64x2_shr_u(v128_t, int);
v128_t __builtin_wasm_i64x2_add(v128_t, v128_t);
v128_t __builtin_wasm_i64x2_sub(v128_t, v128_t);
v128_t __builtin_wasm_i64x2_mul(v128_t, v128_t);
v128_t __builtin_wasm_i64x2_eq(v128_t, v128_t);
v128_t __builtin_wasm_i64x2_ne(v128_t, v128_t);
v128_t __builtin_wasm_i64x2_lt_s(v128_t, v128_t);
v128_t __builtin_wasm_i64x2_gt_s(v128_t, v128_t);
v128_t __builtin_wasm_i64x2_le_s(v128_t, v128_t);
v128_t __builtin_wasm_i64x2_ge_s(v128_t, v128_t);
v128_t __builtin_wasm_i64x2_extmul_low_i32x4_s(v128_t, v128_t);
v128_t __builtin_wasm_i64x2_extmul_high_i32x4_s(v128_t, v128_t);
v128_t __builtin_wasm_i64x2_extmul_low_i32x4_u(v128_t, v128_t);
v128_t __builtin_wasm_i64x2_extmul_high_i32x4_u(v128_t, v128_t);
v128_t __builtin_wasm_f32x4_abs(v128_t);
v128_t __builtin_wasm_f32x4_neg(v128_t);
v128_t __builtin_wasm_f32x4_sqrt(v128_t);
v128_t __builtin_wasm_f32x4_add(v128_t, v128_t);
v128_t __builtin_wasm_f32x4_sub(v128_t, v128_t);
v128_t __builtin_wasm_f32x4_mul(v128_t, v128_t);
v128_t __builtin_wasm_f32x4_div(v128_t, v128_t);
v128_t __builtin_wasm_f32x4_min(v128_t, v128_t);
v128_t __builtin_wasm_f32x4_max(v128_t, v128_t);
v128_t __builtin_wasm_f32x4_pmin(v128_t, v128_t);
v128_t __builtin_wasm_f32x4_pmax(v128_t, v128_t);
v128_t __builtin_wasm_f64x2_abs(v128_t);
v128_t __builtin_wasm_f64x2_neg(v128_t);
v128_t __builtin_wasm_f64x2_sqrt(v128_t);
v128_t __builtin_wasm_f64x2_add(v128_t, v128_t);
v128_t __builtin_wasm_f64x2_sub(v128_t, v128_t);
v128_t __builtin_wasm_f64x2_mul(v128_t, v128_t);
v128_t __builtin_wasm_f64x2_div(v128_t, v128_t);
v128_t __builtin_wasm_f64x2_min(v128_t, v128_t);
v128_t __builtin_wasm_f64x2_max(v128_t, v128_t);
v128_t __builtin_wasm_f64x2_pmin(v128_t, v128_t);
v128_t __builtin_wasm_f64x2_pmax(v128_t, v128_t);
v128_t __builtin_wasm_i32x4_trunc_sat_f32x4_s(v128_t);
v128_t __builtin_wasm_i32x4_trunc_sat_f32x4_u(v128_t);
v128_t __builtin_wasm_f32x4_convert_i32x4_s(v128_t);
v128_t __builtin_wasm_f32x4_convert_i32x4_u(v128_t);
v128_t __builtin_wasm_i32x4_trunc_sat_f64x2_s_zero(v128_t);
v128_t __builtin_wasm_i32x4_trunc_sat_f64x2_u_zero(v128_t);
v128_t __builtin_wasm_f64x2_convert_low_i32x4_s(v128_t);
v128_t __builtin_wasm_f64x2_convert_low_i32x4_u(v128_t);

#define wasm_i8x16_add(a0, a1) __builtin_wasm_i8x16_add(a0, a1)
#define wasm_i8x16_sub(a0, a1) __builtin_wasm_i8x16_sub(a0, a1)
#define wasm_i8x16_neg(a0) __builtin_wasm_i8x16_neg(a0)
#define wasm_i8x16_abs(a0) __builtin_wasm_i8x16_abs(a0)
#define wasm_i16x8_add(a0, a1) __builtin_wasm_i16x8_add(a0, a1)
#define wasm_i16x8_sub(a0, a1) __builtin_wasm_i16x8_sub(a0, a1)
#define wasm_i16x8_mul(a0, a1) __builtin_wasm_i16x8_mul(a0, a1)
#define wasm_i16x8_neg(a0) __builtin_wasm_i16x8_neg(a0)
#define wasm_i16x8_abs(a0) __builtin_wasm_i16x8_abs(a0)
#define wasm_i32x4_add(a0, a1) __builtin_wasm_i32x4_add(a0, a1)
#define wasm_i32x4_sub(a0, a1) __builtin_wasm_i32x4_sub(a0, a1)
#define wasm_i32x4_mul(a0, a1) __builtin_wasm_i32x4_mul(a0, a1)
#define wasm_i32x4_neg(a0) __builtin_wasm_i32x4_neg(a0)
#define wasm_i32x4_abs(a0) __builtin_wasm_i32x4_abs(a0)
#define wasm_i64x2_add(a0, a1) __builtin_wasm_i64x2_add(a0, a1)
#define wasm_i64x2_sub(a0, a1) __builtin_wasm_i64x2_sub(a0, a1)
#define wasm_i64x2_mul(a0, a1) __builtin_wasm_i64x2_mul(a0, a1)
#define wasm_i64x2_neg(a0) __builtin_wasm_i64x2_neg(a0)
#define wasm_i64x2_abs(a0) __builtin_wasm_i64x2_abs(a0)
#define wasm_i8x16_min_s(a0, a1) __builtin_wasm_i8x16_min_s(a0, a1)
#define wasm_i8x16_max_s(a0, a1) __builtin_wasm_i8x16_max_s(a0, a1)
#define wasm_i8x16_min_u(a0, a1) __builtin_wasm_i8x16_min_u(a0, a1)
#define wasm_i8x16_max_u(a0, a1) __builtin_wasm_i8x16_max_u(a0, a1)
#define wasm_i16x8_min_s(a0, a1) __builtin_wasm_i16x8_min_s(a0, a1)
#define wasm_i16x8_max_s(a0, a1) __builtin_wasm_i16x8_max_s(a0, a1)
#define wasm_i16x8_min_u(a0, a1) __builtin_wasm_i16x8_min_u(a0, a1)
#define wasm_i16x8_max_u(a0, a1) __builtin_wasm_i16x8_max_u(a0, a1)
#define wasm_i32x4_min_s(a0, a1) __builtin_wasm_i32x4_min_s(a0, a1)
#define wasm_i32x4_max_s(a0, a1) __builtin_wasm_i32x4_max_s(a0, a1)
#define wasm_i32x4_min_u(a0, a1) __builtin_wasm_i32x4_min_u(a0, a1)
#define wasm_i32x4_max_u(a0, a1) __builtin_wasm_i32x4_max_u(a0, a1)
#define wasm_f32x4_add(a0, a1) __builtin_wasm_f32x4_add(a0, a1)
#define wasm_f32x4_sub(a0, a1) __builtin_wasm_f32x4_sub(a0, a1)
#define wasm_f32x4_mul(a0, a1) __builtin_wasm_f32x4_mul(a0, a1)
#define wasm_f32x4_div(a0, a1) __builtin_wasm_f32x4_div(a0, a1)
#define wasm_f32x4_neg(a0) __builtin_wasm_f32x4_neg(a0)
#define wasm_f32x4_sqrt(a0) __builtin_wasm_f32x4_sqrt(a0)
#define wasm_f32x4_abs(a0) __builtin_wasm_f32x4_abs(a0)
#define wasm_f32x4_ceil(a0) __builtin_wasm_f32x4_ceil(a0)
#define wasm_f32x4_floor(a0) __builtin_wasm_f32x4_floor(a0)
#define wasm_f32x4_trunc(a0) __builtin_wasm_f32x4_trunc(a0)
#define wasm_f32x4_nearest(a0) __builtin_wasm_f32x4_nearest(a0)
#define wasm_f64x2_add(a0, a1) __builtin_wasm_f64x2_add(a0, a1)
#define wasm_f64x2_sub(a0, a1) __builtin_wasm_f64x2_sub(a0, a1)
#define wasm_f64x2_mul(a0, a1) __builtin_wasm_f64x2_mul(a0, a1)
#define wasm_f64x2_div(a0, a1) __builtin_wasm_f64x2_div(a0, a1)
#define wasm_f64x2_neg(a0) __builtin_wasm_f64x2_neg(a0)
#define wasm_f64x2_sqrt(a0) __builtin_wasm_f64x2_sqrt(a0)
#define wasm_f64x2_abs(a0) __builtin_wasm_f64x2_abs(a0)
#define wasm_f64x2_ceil(a0) __builtin_wasm_f64x2_ceil(a0)
#define wasm_f64x2_floor(a0) __builtin_wasm_f64x2_floor(a0)
#define wasm_f64x2_trunc(a0) __builtin_wasm_f64x2_trunc(a0)
#define wasm_f64x2_nearest(a0) __builtin_wasm_f64x2_nearest(a0)
#define wasm_i8x16_eq(a0, a1) __builtin_wasm_i8x16_eq(a0, a1)
#define wasm_i8x16_ne(a0, a1) __builtin_wasm_i8x16_ne(a0, a1)
#define wasm_i8x16_lt_s(a0, a1) __builtin_wasm_i8x16_lt_s(a0, a1)
#define wasm_i8x16_lt_u(a0, a1) __builtin_wasm_i8x16_lt_u(a0, a1)
#define wasm_i8x16_gt_s(a0, a1) __builtin_wasm_i8x16_gt_s(a0, a1)
#define wasm_i8x16_gt_u(a0, a1) __builtin_wasm_i8x16_gt_u(a0, a1)
#define wasm_i8x16_le_s(a0, a1) __builtin_wasm_i8x16_le_s(a0, a1)
#define wasm_i8x16_le_u(a0, a1) __builtin_wasm_i8x16_le_u(a0, a1)
#define wasm_i8x16_ge_s(a0, a1) __builtin_wasm_i8x16_ge_s(a0, a1)
#define wasm_i8x16_ge_u(a0, a1) __builtin_wasm_i8x16_ge_u(a0, a1)
#define wasm_i16x8_eq(a0, a1) __builtin_wasm_i16x8_eq(a0, a1)
#define wasm_i16x8_ne(a0, a1) __builtin_wasm_i16x8_ne(a0, a1)
#define wasm_i16x8_lt_s(a0, a1) __builtin_wasm_i16x8_lt_s(a0, a1)
#define wasm_i16x8_lt_u(a0, a1) __builtin_wasm_i16x8_lt_u(a0, a1)
#define wasm_i16x8_gt_s(a0, a1) __builtin_wasm_i16x8_gt_s(a0, a1)
#define wasm_i16x8_gt_u(a0, a1) __builtin_wasm_i16x8_gt_u(a0, a1)
#define wasm_i16x8_le_s(a0, a1) __builtin_wasm_i16x8_le_s(a0, a1)
#define wasm_i16x8_le_u(a0, a1) __builtin_wasm_i16x8_le_u(a0, a1)
#define wasm_i16x8_ge_s(a0, a1) __builtin_wasm_i16x8_ge_s(a0, a1)
#define wasm_i16x8_ge_u(a0, a1) __builtin_wasm_i16x8_ge_u(a0, a1)
#define wasm_i32x4_eq(a0, a1) __builtin_wasm_i32x4_eq(a0, a1)
#define wasm_i32x4_ne(a0, a1) __builtin_wasm_i32x4_ne(a0, a1)
#define wasm_i32x4_lt_s(a0, a1) __builtin_wasm_i32x4_lt_s(a0, a1)
#define wasm_i32x4_lt_u(a0, a1) __builtin_wasm_i32x4_lt_u(a0, a1)
#define wasm_i32x4_gt_s(a0, a1) __builtin_wasm_i32x4_gt_s(a0, a1)
#define wasm_i32x4_gt_u(a0, a1) __builtin_wasm_i32x4_gt_u(a0, a1)
#define wasm_i32x4_le_s(a0, a1) __builtin_wasm_i32x4_le_s(a0, a1)
#define wasm_i32x4_le_u(a0, a1) __builtin_wasm_i32x4_le_u(a0, a1)
#define wasm_i32x4_ge_s(a0, a1) __builtin_wasm_i32x4_ge_s(a0, a1)
#define wasm_i32x4_ge_u(a0, a1) __builtin_wasm_i32x4_ge_u(a0, a1)
#define wasm_i64x2_eq(a0, a1) __builtin_wasm_i64x2_eq(a0, a1)
#define wasm_i64x2_ne(a0, a1) __builtin_wasm_i64x2_ne(a0, a1)
#define wasm_i64x2_lt_s(a0, a1) __builtin_wasm_i64x2_lt_s(a0, a1)
#define wasm_i64x2_gt_s(a0, a1) __builtin_wasm_i64x2_gt_s(a0, a1)
#define wasm_i64x2_le_s(a0, a1) __builtin_wasm_i64x2_le_s(a0, a1)
#define wasm_i64x2_ge_s(a0, a1) __builtin_wasm_i64x2_ge_s(a0, a1)
#define wasm_f32x4_eq(a0, a1) __builtin_wasm_f32x4_eq(a0, a1)
#define wasm_f32x4_ne(a0, a1) __builtin_wasm_f32x4_ne(a0, a1)
#define wasm_f32x4_lt(a0, a1) __builtin_wasm_f32x4_lt(a0, a1)
#define wasm_f32x4_gt(a0, a1) __builtin_wasm_f32x4_gt(a0, a1)
#define wasm_f32x4_le(a0, a1) __builtin_wasm_f32x4_le(a0, a1)
#define wasm_f32x4_ge(a0, a1) __builtin_wasm_f32x4_ge(a0, a1)
#define wasm_f64x2_eq(a0, a1) __builtin_wasm_f64x2_eq(a0, a1)
#define wasm_f64x2_ne(a0, a1) __builtin_wasm_f64x2_ne(a0, a1)
#define wasm_f64x2_lt(a0, a1) __builtin_wasm_f64x2_lt(a0, a1)
#define wasm_f64x2_gt(a0, a1) __builtin_wasm_f64x2_gt(a0, a1)
#define wasm_f64x2_le(a0, a1) __builtin_wasm_f64x2_le(a0, a1)
#define wasm_f64x2_ge(a0, a1) __builtin_wasm_f64x2_ge(a0, a1)
#define wasm_i8x16_shl(a0, a1) __builtin_wasm_i8x16_shl(a0, a1)
#define wasm_i8x16_shr_s(a0, a1) __builtin_wasm_i8x16_shr_s(a0, a1)
#define wasm_i8x16_shr_u(a0, a1) __builtin_wasm_i8x16_shr_u(a0, a1)
#define wasm_i16x8_shl(a0, a1) __builtin_wasm_i16x8_shl(a0, a1)
#define wasm_i16x8_shr_s(a0, a1) __builtin_wasm_i16x8_shr_s(a0, a1)
#define wasm_i16x8_shr_u(a0, a1) __builtin_wasm_i16x8_shr_u(a0, a1)
#define wasm_i32x4_shl(a0, a1) __builtin_wasm_i32x4_shl(a0, a1)
#define wasm_i32x4_shr_s(a0, a1) __builtin_wasm_i32x4_shr_s(a0, a1)
#define wasm_i32x4_shr_u(a0, a1) __builtin_wasm_i32x4_shr_u(a0, a1)
#define wasm_i64x2_shl(a0, a1) __builtin_wasm_i64x2_shl(a0, a1)
#define wasm_i64x2_shr_s(a0, a1) __builtin_wasm_i64x2_shr_s(a0, a1)
#define wasm_i64x2_shr_u(a0, a1) __builtin_wasm_i64x2_shr_u(a0, a1)
#define wasm_i8x16_splat(a0) __builtin_wasm_i8x16_splat(a0)
#define wasm_i8x16_extract_lane_s(a0, a1) __builtin_wasm_i8x16_extract_lane_s(a0, a1)
#define wasm_i8x16_extract_lane_u(a0, a1) __builtin_wasm_i8x16_extract_lane_u(a0, a1)
#define wasm_i8x16_replace_lane(a0, a1, a2) __builtin_wasm_i8x16_replace_lane(a0, a2, a1)
#define wasm_i16x8_splat(a0) __builtin_wasm_i16x8_splat(a0)
#define wasm_i16x8_extract_lane_s(a0, a1) __builtin_wasm_i16x8_extract_lane_s(a0, a1)
#define wasm_i16x8_extract_lane_u(a0, a1) __builtin_wasm_i16x8_extract_lane_u(a0, a1)
#define wasm_i16x8_replace_lane(a0, a1, a2) __builtin_wasm_i16x8_replace_lane(a0, a2, a1)
#define wasm_i32x4_splat(a0) __builtin_wasm_i32x4_splat(a0)
#define wasm_i32x4_extract_lane(a0, a1) __builtin_wasm_i32x4_extract_lane(a0, a1)
#define wasm_i32x4_replace_lane(a0, a1, a2) __builtin_wasm_i32x4_replace_lane(a0, a2, a1)
#define wasm_i64x2_splat(a0) __builtin_wasm_i64x2_splat(a0)
#define wasm_i64x2_extract_lane(a0, a1) __builtin_wasm_i64x2_extract_lane(a0, a1)
#define wasm_i64x2_replace_lane(a0, a1, a2) __builtin_wasm_i64x2_replace_lane(a0, a2, a1)
#define wasm_f32x4_splat(a0) __builtin_wasm_f32x4_splat(a0)
#define wasm_f32x4_extract_lane(a0, a1) __builtin_wasm_f32x4_extract_lane(a0, a1)
#define wasm_f32x4_replace_lane(a0, a1, a2) __builtin_wasm_f32x4_replace_lane(a0, a2, a1)
#define wasm_f64x2_splat(a0) __builtin_wasm_f64x2_splat(a0)
#define wasm_f64x2_extract_lane(a0, a1) __builtin_wasm_f64x2_extract_lane(a0, a1)
#define wasm_f64x2_replace_lane(a0, a1, a2) __builtin_wasm_f64x2_replace_lane(a0, a2, a1)
#define wasm_v128_and(a0, a1) __builtin_wasm_v128_and(a0, a1)
#define wasm_v128_or(a0, a1) __builtin_wasm_v128_or(a0, a1)
#define wasm_v128_xor(a0, a1) __builtin_wasm_v128_xor(a0, a1)
#define wasm_v128_andnot(a0, a1) __builtin_wasm_v128_andnot(a0, a1)
#define wasm_v128_not(a0) __builtin_wasm_v128_not(a0)
#define wasm_v128_bitselect(a0, a1, a2) __builtin_wasm_v128_bitselect(a0, a1, a2)
#define wasm_v128_any_true(a0) __builtin_wasm_v128_any_true(a0)
#define wasm_i8x16_all_true(a0) __builtin_wasm_i8x16_all_true(a0)
#define wasm_i8x16_bitmask(a0) __builtin_wasm_i8x16_bitmask(a0)
#define wasm_i16x8_all_true(a0) __builtin_wasm_i16x8_all_true(a0)
#define wasm_i16x8_bitmask(a0) __builtin_wasm_i16x8_bitmask(a0)
#define wasm_i32x4_all_true(a0) __builtin_wasm_i32x4_all_true(a0)
#define wasm_i32x4_bitmask(a0) __builtin_wasm_i32x4_bitmask(a0)
#define wasm_i64x2_all_true(a0) __builtin_wasm_i64x2_all_true(a0)
#define wasm_i64x2_bitmask(a0) __builtin_wasm_i64x2_bitmask(a0)

#else  /* every other target: portable scalar C */

#include <string.h>
#include <math.h>

static signed char __wsimd_get_i8(v128_t v, int k) {
  signed char a[16]; memcpy(a, v.__v, 16); return a[k];
}
static void __wsimd_set_i8(v128_t *v, int k, signed char x) {
  signed char a[16]; memcpy(a, v->__v, 16); a[k] = x;
  memcpy(v->__v, a, 16);
}
static unsigned char __wsimd_get_u8(v128_t v, int k) {
  unsigned char a[16]; memcpy(a, v.__v, 16); return a[k];
}
static void __wsimd_set_u8(v128_t *v, int k, unsigned char x) {
  unsigned char a[16]; memcpy(a, v->__v, 16); a[k] = x;
  memcpy(v->__v, a, 16);
}
static short __wsimd_get_i16(v128_t v, int k) {
  short a[8]; memcpy(a, v.__v, 16); return a[k];
}
static void __wsimd_set_i16(v128_t *v, int k, short x) {
  short a[8]; memcpy(a, v->__v, 16); a[k] = x;
  memcpy(v->__v, a, 16);
}
static unsigned short __wsimd_get_u16(v128_t v, int k) {
  unsigned short a[8]; memcpy(a, v.__v, 16); return a[k];
}
static void __wsimd_set_u16(v128_t *v, int k, unsigned short x) {
  unsigned short a[8]; memcpy(a, v->__v, 16); a[k] = x;
  memcpy(v->__v, a, 16);
}
static int __wsimd_get_i32(v128_t v, int k) {
  int a[4]; memcpy(a, v.__v, 16); return a[k];
}
static void __wsimd_set_i32(v128_t *v, int k, int x) {
  int a[4]; memcpy(a, v->__v, 16); a[k] = x;
  memcpy(v->__v, a, 16);
}
static unsigned int __wsimd_get_u32(v128_t v, int k) {
  unsigned int a[4]; memcpy(a, v.__v, 16); return a[k];
}
static void __wsimd_set_u32(v128_t *v, int k, unsigned int x) {
  unsigned int a[4]; memcpy(a, v->__v, 16); a[k] = x;
  memcpy(v->__v, a, 16);
}
static long __wsimd_get_i64(v128_t v, int k) {
  long a[2]; memcpy(a, v.__v, 16); return a[k];
}
static void __wsimd_set_i64(v128_t *v, int k, long x) {
  long a[2]; memcpy(a, v->__v, 16); a[k] = x;
  memcpy(v->__v, a, 16);
}
static unsigned long __wsimd_get_u64(v128_t v, int k) {
  unsigned long a[2]; memcpy(a, v.__v, 16); return a[k];
}
static void __wsimd_set_u64(v128_t *v, int k, unsigned long x) {
  unsigned long a[2]; memcpy(a, v->__v, 16); a[k] = x;
  memcpy(v->__v, a, 16);
}
static float __wsimd_get_f32(v128_t v, int k) {
  float a[4]; memcpy(a, v.__v, 16); return a[k];
}
static void __wsimd_set_f32(v128_t *v, int k, float x) {
  float a[4]; memcpy(a, v->__v, 16); a[k] = x;
  memcpy(v->__v, a, 16);
}
static double __wsimd_get_f64(v128_t v, int k) {
  double a[2]; memcpy(a, v.__v, 16); return a[k];
}
static void __wsimd_set_f64(v128_t *v, int k, double x) {
  double a[2]; memcpy(a, v->__v, 16); a[k] = x;
  memcpy(v->__v, a, 16);
}

static v128_t wasm_i8x16_add(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    unsigned char x = __wsimd_get_u8(a, k), y = __wsimd_get_u8(b, k);
    __wsimd_set_u8(&r, k, (unsigned char)(x + y));
  }
  return r;
}

static v128_t wasm_i8x16_sub(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    unsigned char x = __wsimd_get_u8(a, k), y = __wsimd_get_u8(b, k);
    __wsimd_set_u8(&r, k, (unsigned char)(x - y));
  }
  return r;
}

static v128_t wasm_i8x16_neg(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    unsigned char x = __wsimd_get_u8(a, k);
    __wsimd_set_u8(&r, k, (unsigned char)(-x));
  }
  return r;
}

static v128_t wasm_i8x16_abs(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    signed char x = __wsimd_get_i8(a, k);
    __wsimd_set_i8(&r, k, (signed char)(x < 0 ? -x : x));
  }
  return r;
}

static v128_t wasm_i16x8_add(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    unsigned short x = __wsimd_get_u16(a, k), y = __wsimd_get_u16(b, k);
    __wsimd_set_u16(&r, k, (unsigned short)(x + y));
  }
  return r;
}

static v128_t wasm_i16x8_sub(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    unsigned short x = __wsimd_get_u16(a, k), y = __wsimd_get_u16(b, k);
    __wsimd_set_u16(&r, k, (unsigned short)(x - y));
  }
  return r;
}

static v128_t wasm_i16x8_mul(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    unsigned short x = __wsimd_get_u16(a, k), y = __wsimd_get_u16(b, k);
    __wsimd_set_u16(&r, k, (unsigned short)(x * y));
  }
  return r;
}

static v128_t wasm_i16x8_neg(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    unsigned short x = __wsimd_get_u16(a, k);
    __wsimd_set_u16(&r, k, (unsigned short)(-x));
  }
  return r;
}

static v128_t wasm_i16x8_abs(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    short x = __wsimd_get_i16(a, k);
    __wsimd_set_i16(&r, k, (short)(x < 0 ? -x : x));
  }
  return r;
}

static v128_t wasm_i32x4_add(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    unsigned int x = __wsimd_get_u32(a, k), y = __wsimd_get_u32(b, k);
    __wsimd_set_u32(&r, k, (unsigned int)(x + y));
  }
  return r;
}

static v128_t wasm_i32x4_sub(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    unsigned int x = __wsimd_get_u32(a, k), y = __wsimd_get_u32(b, k);
    __wsimd_set_u32(&r, k, (unsigned int)(x - y));
  }
  return r;
}

static v128_t wasm_i32x4_mul(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    unsigned int x = __wsimd_get_u32(a, k), y = __wsimd_get_u32(b, k);
    __wsimd_set_u32(&r, k, (unsigned int)(x * y));
  }
  return r;
}

static v128_t wasm_i32x4_neg(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    unsigned int x = __wsimd_get_u32(a, k);
    __wsimd_set_u32(&r, k, (unsigned int)(-x));
  }
  return r;
}

static v128_t wasm_i32x4_abs(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    int x = __wsimd_get_i32(a, k);
    __wsimd_set_i32(&r, k, (int)(x < 0 ? -x : x));
  }
  return r;
}

static v128_t wasm_i64x2_add(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    unsigned long x = __wsimd_get_u64(a, k), y = __wsimd_get_u64(b, k);
    __wsimd_set_u64(&r, k, (unsigned long)(x + y));
  }
  return r;
}

static v128_t wasm_i64x2_sub(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    unsigned long x = __wsimd_get_u64(a, k), y = __wsimd_get_u64(b, k);
    __wsimd_set_u64(&r, k, (unsigned long)(x - y));
  }
  return r;
}

static v128_t wasm_i64x2_mul(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    unsigned long x = __wsimd_get_u64(a, k), y = __wsimd_get_u64(b, k);
    __wsimd_set_u64(&r, k, (unsigned long)(x * y));
  }
  return r;
}

static v128_t wasm_i64x2_neg(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    unsigned long x = __wsimd_get_u64(a, k);
    __wsimd_set_u64(&r, k, (unsigned long)(-x));
  }
  return r;
}

static v128_t wasm_i64x2_abs(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    long x = __wsimd_get_i64(a, k);
    __wsimd_set_i64(&r, k, (long)(x < 0 ? -x : x));
  }
  return r;
}

static v128_t wasm_i8x16_min_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    signed char x = __wsimd_get_i8(a, k), y = __wsimd_get_i8(b, k);
    __wsimd_set_i8(&r, k, (signed char)(x < y ? x : y));
  }
  return r;
}

static v128_t wasm_i8x16_max_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    signed char x = __wsimd_get_i8(a, k), y = __wsimd_get_i8(b, k);
    __wsimd_set_i8(&r, k, (signed char)(x > y ? x : y));
  }
  return r;
}

static v128_t wasm_i8x16_min_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    unsigned char x = __wsimd_get_u8(a, k), y = __wsimd_get_u8(b, k);
    __wsimd_set_u8(&r, k, (unsigned char)(x < y ? x : y));
  }
  return r;
}

static v128_t wasm_i8x16_max_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    unsigned char x = __wsimd_get_u8(a, k), y = __wsimd_get_u8(b, k);
    __wsimd_set_u8(&r, k, (unsigned char)(x > y ? x : y));
  }
  return r;
}

static v128_t wasm_i16x8_min_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    short x = __wsimd_get_i16(a, k), y = __wsimd_get_i16(b, k);
    __wsimd_set_i16(&r, k, (short)(x < y ? x : y));
  }
  return r;
}

static v128_t wasm_i16x8_max_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    short x = __wsimd_get_i16(a, k), y = __wsimd_get_i16(b, k);
    __wsimd_set_i16(&r, k, (short)(x > y ? x : y));
  }
  return r;
}

static v128_t wasm_i16x8_min_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    unsigned short x = __wsimd_get_u16(a, k), y = __wsimd_get_u16(b, k);
    __wsimd_set_u16(&r, k, (unsigned short)(x < y ? x : y));
  }
  return r;
}

static v128_t wasm_i16x8_max_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    unsigned short x = __wsimd_get_u16(a, k), y = __wsimd_get_u16(b, k);
    __wsimd_set_u16(&r, k, (unsigned short)(x > y ? x : y));
  }
  return r;
}

static v128_t wasm_i32x4_min_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    int x = __wsimd_get_i32(a, k), y = __wsimd_get_i32(b, k);
    __wsimd_set_i32(&r, k, (int)(x < y ? x : y));
  }
  return r;
}

static v128_t wasm_i32x4_max_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    int x = __wsimd_get_i32(a, k), y = __wsimd_get_i32(b, k);
    __wsimd_set_i32(&r, k, (int)(x > y ? x : y));
  }
  return r;
}

static v128_t wasm_i32x4_min_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    unsigned int x = __wsimd_get_u32(a, k), y = __wsimd_get_u32(b, k);
    __wsimd_set_u32(&r, k, (unsigned int)(x < y ? x : y));
  }
  return r;
}

static v128_t wasm_i32x4_max_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    unsigned int x = __wsimd_get_u32(a, k), y = __wsimd_get_u32(b, k);
    __wsimd_set_u32(&r, k, (unsigned int)(x > y ? x : y));
  }
  return r;
}

static v128_t wasm_f32x4_add(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    float x = __wsimd_get_f32(a, k), y = __wsimd_get_f32(b, k);
    __wsimd_set_f32(&r, k, (float)(x + y));
  }
  return r;
}

static v128_t wasm_f32x4_sub(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    float x = __wsimd_get_f32(a, k), y = __wsimd_get_f32(b, k);
    __wsimd_set_f32(&r, k, (float)(x - y));
  }
  return r;
}

static v128_t wasm_f32x4_mul(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    float x = __wsimd_get_f32(a, k), y = __wsimd_get_f32(b, k);
    __wsimd_set_f32(&r, k, (float)(x * y));
  }
  return r;
}

static v128_t wasm_f32x4_div(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    float x = __wsimd_get_f32(a, k), y = __wsimd_get_f32(b, k);
    __wsimd_set_f32(&r, k, (float)(x / y));
  }
  return r;
}

static v128_t wasm_f32x4_neg(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    float x = __wsimd_get_f32(a, k);
    __wsimd_set_f32(&r, k, (float)(-x));
  }
  return r;
}

static v128_t wasm_f32x4_sqrt(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    float x = __wsimd_get_f32(a, k);
    __wsimd_set_f32(&r, k, (float)(sqrtf(x)));
  }
  return r;
}

static v128_t wasm_f32x4_abs(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    float x = __wsimd_get_f32(a, k);
    __wsimd_set_f32(&r, k, (float)(fabsf(x)));
  }
  return r;
}

static v128_t wasm_f32x4_ceil(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    float x = __wsimd_get_f32(a, k);
    __wsimd_set_f32(&r, k, (float)(ceilf(x)));
  }
  return r;
}

static v128_t wasm_f32x4_floor(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    float x = __wsimd_get_f32(a, k);
    __wsimd_set_f32(&r, k, (float)(floorf(x)));
  }
  return r;
}

static v128_t wasm_f32x4_trunc(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    float x = __wsimd_get_f32(a, k);
    __wsimd_set_f32(&r, k, (float)(truncf(x)));
  }
  return r;
}

static v128_t wasm_f32x4_nearest(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    float x = __wsimd_get_f32(a, k);
    __wsimd_set_f32(&r, k, (float)(nearbyintf(x)));
  }
  return r;
}

static v128_t wasm_f64x2_add(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    double x = __wsimd_get_f64(a, k), y = __wsimd_get_f64(b, k);
    __wsimd_set_f64(&r, k, (double)(x + y));
  }
  return r;
}

static v128_t wasm_f64x2_sub(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    double x = __wsimd_get_f64(a, k), y = __wsimd_get_f64(b, k);
    __wsimd_set_f64(&r, k, (double)(x - y));
  }
  return r;
}

static v128_t wasm_f64x2_mul(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    double x = __wsimd_get_f64(a, k), y = __wsimd_get_f64(b, k);
    __wsimd_set_f64(&r, k, (double)(x * y));
  }
  return r;
}

static v128_t wasm_f64x2_div(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    double x = __wsimd_get_f64(a, k), y = __wsimd_get_f64(b, k);
    __wsimd_set_f64(&r, k, (double)(x / y));
  }
  return r;
}

static v128_t wasm_f64x2_neg(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    double x = __wsimd_get_f64(a, k);
    __wsimd_set_f64(&r, k, (double)(-x));
  }
  return r;
}

static v128_t wasm_f64x2_sqrt(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    double x = __wsimd_get_f64(a, k);
    __wsimd_set_f64(&r, k, (double)(sqrt(x)));
  }
  return r;
}

static v128_t wasm_f64x2_abs(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    double x = __wsimd_get_f64(a, k);
    __wsimd_set_f64(&r, k, (double)(fabs(x)));
  }
  return r;
}

static v128_t wasm_f64x2_ceil(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    double x = __wsimd_get_f64(a, k);
    __wsimd_set_f64(&r, k, (double)(ceil(x)));
  }
  return r;
}

static v128_t wasm_f64x2_floor(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    double x = __wsimd_get_f64(a, k);
    __wsimd_set_f64(&r, k, (double)(floor(x)));
  }
  return r;
}

static v128_t wasm_f64x2_trunc(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    double x = __wsimd_get_f64(a, k);
    __wsimd_set_f64(&r, k, (double)(trunc(x)));
  }
  return r;
}

static v128_t wasm_f64x2_nearest(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    double x = __wsimd_get_f64(a, k);
    __wsimd_set_f64(&r, k, (double)(nearbyint(x)));
  }
  return r;
}

static v128_t wasm_i8x16_eq(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    unsigned char x = __wsimd_get_u8(a, k), y = __wsimd_get_u8(b, k);
    __wsimd_set_u8(&r, k, (x == y) ? (unsigned char)~(unsigned char)0 : (unsigned char)0);
  }
  return r;
}

static v128_t wasm_i8x16_ne(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    unsigned char x = __wsimd_get_u8(a, k), y = __wsimd_get_u8(b, k);
    __wsimd_set_u8(&r, k, (x != y) ? (unsigned char)~(unsigned char)0 : (unsigned char)0);
  }
  return r;
}

static v128_t wasm_i8x16_lt_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    signed char x = __wsimd_get_i8(a, k), y = __wsimd_get_i8(b, k);
    __wsimd_set_u8(&r, k, (x < y) ? (unsigned char)~(unsigned char)0 : (unsigned char)0);
  }
  return r;
}

static v128_t wasm_i8x16_lt_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    unsigned char x = __wsimd_get_u8(a, k), y = __wsimd_get_u8(b, k);
    __wsimd_set_u8(&r, k, (x < y) ? (unsigned char)~(unsigned char)0 : (unsigned char)0);
  }
  return r;
}

static v128_t wasm_i8x16_gt_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    signed char x = __wsimd_get_i8(a, k), y = __wsimd_get_i8(b, k);
    __wsimd_set_u8(&r, k, (x > y) ? (unsigned char)~(unsigned char)0 : (unsigned char)0);
  }
  return r;
}

static v128_t wasm_i8x16_gt_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    unsigned char x = __wsimd_get_u8(a, k), y = __wsimd_get_u8(b, k);
    __wsimd_set_u8(&r, k, (x > y) ? (unsigned char)~(unsigned char)0 : (unsigned char)0);
  }
  return r;
}

static v128_t wasm_i8x16_le_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    signed char x = __wsimd_get_i8(a, k), y = __wsimd_get_i8(b, k);
    __wsimd_set_u8(&r, k, (x <= y) ? (unsigned char)~(unsigned char)0 : (unsigned char)0);
  }
  return r;
}

static v128_t wasm_i8x16_le_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    unsigned char x = __wsimd_get_u8(a, k), y = __wsimd_get_u8(b, k);
    __wsimd_set_u8(&r, k, (x <= y) ? (unsigned char)~(unsigned char)0 : (unsigned char)0);
  }
  return r;
}

static v128_t wasm_i8x16_ge_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    signed char x = __wsimd_get_i8(a, k), y = __wsimd_get_i8(b, k);
    __wsimd_set_u8(&r, k, (x >= y) ? (unsigned char)~(unsigned char)0 : (unsigned char)0);
  }
  return r;
}

static v128_t wasm_i8x16_ge_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 16; k++) {
    unsigned char x = __wsimd_get_u8(a, k), y = __wsimd_get_u8(b, k);
    __wsimd_set_u8(&r, k, (x >= y) ? (unsigned char)~(unsigned char)0 : (unsigned char)0);
  }
  return r;
}

static v128_t wasm_i16x8_eq(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    unsigned short x = __wsimd_get_u16(a, k), y = __wsimd_get_u16(b, k);
    __wsimd_set_u16(&r, k, (x == y) ? (unsigned short)~(unsigned short)0 : (unsigned short)0);
  }
  return r;
}

static v128_t wasm_i16x8_ne(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    unsigned short x = __wsimd_get_u16(a, k), y = __wsimd_get_u16(b, k);
    __wsimd_set_u16(&r, k, (x != y) ? (unsigned short)~(unsigned short)0 : (unsigned short)0);
  }
  return r;
}

static v128_t wasm_i16x8_lt_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    short x = __wsimd_get_i16(a, k), y = __wsimd_get_i16(b, k);
    __wsimd_set_u16(&r, k, (x < y) ? (unsigned short)~(unsigned short)0 : (unsigned short)0);
  }
  return r;
}

static v128_t wasm_i16x8_lt_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    unsigned short x = __wsimd_get_u16(a, k), y = __wsimd_get_u16(b, k);
    __wsimd_set_u16(&r, k, (x < y) ? (unsigned short)~(unsigned short)0 : (unsigned short)0);
  }
  return r;
}

static v128_t wasm_i16x8_gt_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    short x = __wsimd_get_i16(a, k), y = __wsimd_get_i16(b, k);
    __wsimd_set_u16(&r, k, (x > y) ? (unsigned short)~(unsigned short)0 : (unsigned short)0);
  }
  return r;
}

static v128_t wasm_i16x8_gt_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    unsigned short x = __wsimd_get_u16(a, k), y = __wsimd_get_u16(b, k);
    __wsimd_set_u16(&r, k, (x > y) ? (unsigned short)~(unsigned short)0 : (unsigned short)0);
  }
  return r;
}

static v128_t wasm_i16x8_le_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    short x = __wsimd_get_i16(a, k), y = __wsimd_get_i16(b, k);
    __wsimd_set_u16(&r, k, (x <= y) ? (unsigned short)~(unsigned short)0 : (unsigned short)0);
  }
  return r;
}

static v128_t wasm_i16x8_le_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    unsigned short x = __wsimd_get_u16(a, k), y = __wsimd_get_u16(b, k);
    __wsimd_set_u16(&r, k, (x <= y) ? (unsigned short)~(unsigned short)0 : (unsigned short)0);
  }
  return r;
}

static v128_t wasm_i16x8_ge_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    short x = __wsimd_get_i16(a, k), y = __wsimd_get_i16(b, k);
    __wsimd_set_u16(&r, k, (x >= y) ? (unsigned short)~(unsigned short)0 : (unsigned short)0);
  }
  return r;
}

static v128_t wasm_i16x8_ge_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 8; k++) {
    unsigned short x = __wsimd_get_u16(a, k), y = __wsimd_get_u16(b, k);
    __wsimd_set_u16(&r, k, (x >= y) ? (unsigned short)~(unsigned short)0 : (unsigned short)0);
  }
  return r;
}

static v128_t wasm_i32x4_eq(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    unsigned int x = __wsimd_get_u32(a, k), y = __wsimd_get_u32(b, k);
    __wsimd_set_u32(&r, k, (x == y) ? (unsigned int)~(unsigned int)0 : (unsigned int)0);
  }
  return r;
}

static v128_t wasm_i32x4_ne(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    unsigned int x = __wsimd_get_u32(a, k), y = __wsimd_get_u32(b, k);
    __wsimd_set_u32(&r, k, (x != y) ? (unsigned int)~(unsigned int)0 : (unsigned int)0);
  }
  return r;
}

static v128_t wasm_i32x4_lt_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    int x = __wsimd_get_i32(a, k), y = __wsimd_get_i32(b, k);
    __wsimd_set_u32(&r, k, (x < y) ? (unsigned int)~(unsigned int)0 : (unsigned int)0);
  }
  return r;
}

static v128_t wasm_i32x4_lt_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    unsigned int x = __wsimd_get_u32(a, k), y = __wsimd_get_u32(b, k);
    __wsimd_set_u32(&r, k, (x < y) ? (unsigned int)~(unsigned int)0 : (unsigned int)0);
  }
  return r;
}

static v128_t wasm_i32x4_gt_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    int x = __wsimd_get_i32(a, k), y = __wsimd_get_i32(b, k);
    __wsimd_set_u32(&r, k, (x > y) ? (unsigned int)~(unsigned int)0 : (unsigned int)0);
  }
  return r;
}

static v128_t wasm_i32x4_gt_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    unsigned int x = __wsimd_get_u32(a, k), y = __wsimd_get_u32(b, k);
    __wsimd_set_u32(&r, k, (x > y) ? (unsigned int)~(unsigned int)0 : (unsigned int)0);
  }
  return r;
}

static v128_t wasm_i32x4_le_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    int x = __wsimd_get_i32(a, k), y = __wsimd_get_i32(b, k);
    __wsimd_set_u32(&r, k, (x <= y) ? (unsigned int)~(unsigned int)0 : (unsigned int)0);
  }
  return r;
}

static v128_t wasm_i32x4_le_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    unsigned int x = __wsimd_get_u32(a, k), y = __wsimd_get_u32(b, k);
    __wsimd_set_u32(&r, k, (x <= y) ? (unsigned int)~(unsigned int)0 : (unsigned int)0);
  }
  return r;
}

static v128_t wasm_i32x4_ge_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    int x = __wsimd_get_i32(a, k), y = __wsimd_get_i32(b, k);
    __wsimd_set_u32(&r, k, (x >= y) ? (unsigned int)~(unsigned int)0 : (unsigned int)0);
  }
  return r;
}

static v128_t wasm_i32x4_ge_u(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    unsigned int x = __wsimd_get_u32(a, k), y = __wsimd_get_u32(b, k);
    __wsimd_set_u32(&r, k, (x >= y) ? (unsigned int)~(unsigned int)0 : (unsigned int)0);
  }
  return r;
}

static v128_t wasm_i64x2_eq(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    unsigned long x = __wsimd_get_u64(a, k), y = __wsimd_get_u64(b, k);
    __wsimd_set_u64(&r, k, (x == y) ? (unsigned long)~(unsigned long)0 : (unsigned long)0);
  }
  return r;
}

static v128_t wasm_i64x2_ne(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    unsigned long x = __wsimd_get_u64(a, k), y = __wsimd_get_u64(b, k);
    __wsimd_set_u64(&r, k, (x != y) ? (unsigned long)~(unsigned long)0 : (unsigned long)0);
  }
  return r;
}

static v128_t wasm_i64x2_lt_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    long x = __wsimd_get_i64(a, k), y = __wsimd_get_i64(b, k);
    __wsimd_set_u64(&r, k, (x < y) ? (unsigned long)~(unsigned long)0 : (unsigned long)0);
  }
  return r;
}

static v128_t wasm_i64x2_gt_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    long x = __wsimd_get_i64(a, k), y = __wsimd_get_i64(b, k);
    __wsimd_set_u64(&r, k, (x > y) ? (unsigned long)~(unsigned long)0 : (unsigned long)0);
  }
  return r;
}

static v128_t wasm_i64x2_le_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    long x = __wsimd_get_i64(a, k), y = __wsimd_get_i64(b, k);
    __wsimd_set_u64(&r, k, (x <= y) ? (unsigned long)~(unsigned long)0 : (unsigned long)0);
  }
  return r;
}

static v128_t wasm_i64x2_ge_s(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    long x = __wsimd_get_i64(a, k), y = __wsimd_get_i64(b, k);
    __wsimd_set_u64(&r, k, (x >= y) ? (unsigned long)~(unsigned long)0 : (unsigned long)0);
  }
  return r;
}

static v128_t wasm_f32x4_eq(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    float x = __wsimd_get_f32(a, k), y = __wsimd_get_f32(b, k);
    __wsimd_set_u32(&r, k, (x == y) ? (unsigned int)~(unsigned int)0 : (unsigned int)0);
  }
  return r;
}

static v128_t wasm_f32x4_ne(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    float x = __wsimd_get_f32(a, k), y = __wsimd_get_f32(b, k);
    __wsimd_set_u32(&r, k, (x != y) ? (unsigned int)~(unsigned int)0 : (unsigned int)0);
  }
  return r;
}

static v128_t wasm_f32x4_lt(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    float x = __wsimd_get_f32(a, k), y = __wsimd_get_f32(b, k);
    __wsimd_set_u32(&r, k, (x < y) ? (unsigned int)~(unsigned int)0 : (unsigned int)0);
  }
  return r;
}

static v128_t wasm_f32x4_gt(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    float x = __wsimd_get_f32(a, k), y = __wsimd_get_f32(b, k);
    __wsimd_set_u32(&r, k, (x > y) ? (unsigned int)~(unsigned int)0 : (unsigned int)0);
  }
  return r;
}

static v128_t wasm_f32x4_le(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    float x = __wsimd_get_f32(a, k), y = __wsimd_get_f32(b, k);
    __wsimd_set_u32(&r, k, (x <= y) ? (unsigned int)~(unsigned int)0 : (unsigned int)0);
  }
  return r;
}

static v128_t wasm_f32x4_ge(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 4; k++) {
    float x = __wsimd_get_f32(a, k), y = __wsimd_get_f32(b, k);
    __wsimd_set_u32(&r, k, (x >= y) ? (unsigned int)~(unsigned int)0 : (unsigned int)0);
  }
  return r;
}

static v128_t wasm_f64x2_eq(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    double x = __wsimd_get_f64(a, k), y = __wsimd_get_f64(b, k);
    __wsimd_set_u64(&r, k, (x == y) ? (unsigned long)~(unsigned long)0 : (unsigned long)0);
  }
  return r;
}

static v128_t wasm_f64x2_ne(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    double x = __wsimd_get_f64(a, k), y = __wsimd_get_f64(b, k);
    __wsimd_set_u64(&r, k, (x != y) ? (unsigned long)~(unsigned long)0 : (unsigned long)0);
  }
  return r;
}

static v128_t wasm_f64x2_lt(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    double x = __wsimd_get_f64(a, k), y = __wsimd_get_f64(b, k);
    __wsimd_set_u64(&r, k, (x < y) ? (unsigned long)~(unsigned long)0 : (unsigned long)0);
  }
  return r;
}

static v128_t wasm_f64x2_gt(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    double x = __wsimd_get_f64(a, k), y = __wsimd_get_f64(b, k);
    __wsimd_set_u64(&r, k, (x > y) ? (unsigned long)~(unsigned long)0 : (unsigned long)0);
  }
  return r;
}

static v128_t wasm_f64x2_le(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    double x = __wsimd_get_f64(a, k), y = __wsimd_get_f64(b, k);
    __wsimd_set_u64(&r, k, (x <= y) ? (unsigned long)~(unsigned long)0 : (unsigned long)0);
  }
  return r;
}

static v128_t wasm_f64x2_ge(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    double x = __wsimd_get_f64(a, k), y = __wsimd_get_f64(b, k);
    __wsimd_set_u64(&r, k, (x >= y) ? (unsigned long)~(unsigned long)0 : (unsigned long)0);
  }
  return r;
}

static v128_t wasm_i8x16_shl(v128_t a, int n) {
  v128_t r; int k;
  for (k = 0; k < 16; k++)
    __wsimd_set_u8(&r, k, (unsigned char)(__wsimd_get_u8(a, k) << (n & 7)));
  return r;
}

static v128_t wasm_i8x16_shr_s(v128_t a, int n) {
  v128_t r; int k;
  for (k = 0; k < 16; k++)
    __wsimd_set_i8(&r, k, (signed char)(__wsimd_get_i8(a, k) >> (n & 7)));
  return r;
}

static v128_t wasm_i8x16_shr_u(v128_t a, int n) {
  v128_t r; int k;
  for (k = 0; k < 16; k++)
    __wsimd_set_u8(&r, k, (unsigned char)(__wsimd_get_u8(a, k) >> (n & 7)));
  return r;
}

static v128_t wasm_i16x8_shl(v128_t a, int n) {
  v128_t r; int k;
  for (k = 0; k < 8; k++)
    __wsimd_set_u16(&r, k, (unsigned short)(__wsimd_get_u16(a, k) << (n & 15)));
  return r;
}

static v128_t wasm_i16x8_shr_s(v128_t a, int n) {
  v128_t r; int k;
  for (k = 0; k < 8; k++)
    __wsimd_set_i16(&r, k, (short)(__wsimd_get_i16(a, k) >> (n & 15)));
  return r;
}

static v128_t wasm_i16x8_shr_u(v128_t a, int n) {
  v128_t r; int k;
  for (k = 0; k < 8; k++)
    __wsimd_set_u16(&r, k, (unsigned short)(__wsimd_get_u16(a, k) >> (n & 15)));
  return r;
}

static v128_t wasm_i32x4_shl(v128_t a, int n) {
  v128_t r; int k;
  for (k = 0; k < 4; k++)
    __wsimd_set_u32(&r, k, (unsigned int)(__wsimd_get_u32(a, k) << (n & 31)));
  return r;
}

static v128_t wasm_i32x4_shr_s(v128_t a, int n) {
  v128_t r; int k;
  for (k = 0; k < 4; k++)
    __wsimd_set_i32(&r, k, (int)(__wsimd_get_i32(a, k) >> (n & 31)));
  return r;
}

static v128_t wasm_i32x4_shr_u(v128_t a, int n) {
  v128_t r; int k;
  for (k = 0; k < 4; k++)
    __wsimd_set_u32(&r, k, (unsigned int)(__wsimd_get_u32(a, k) >> (n & 31)));
  return r;
}

static v128_t wasm_i64x2_shl(v128_t a, int n) {
  v128_t r; int k;
  for (k = 0; k < 2; k++)
    __wsimd_set_u64(&r, k, (unsigned long)(__wsimd_get_u64(a, k) << (n & 63)));
  return r;
}

static v128_t wasm_i64x2_shr_s(v128_t a, int n) {
  v128_t r; int k;
  for (k = 0; k < 2; k++)
    __wsimd_set_i64(&r, k, (long)(__wsimd_get_i64(a, k) >> (n & 63)));
  return r;
}

static v128_t wasm_i64x2_shr_u(v128_t a, int n) {
  v128_t r; int k;
  for (k = 0; k < 2; k++)
    __wsimd_set_u64(&r, k, (unsigned long)(__wsimd_get_u64(a, k) >> (n & 63)));
  return r;
}

static v128_t wasm_i8x16_splat(int x) {
  v128_t r; int k;
  for (k = 0; k < 16; k++)
    __wsimd_set_i8(&r, k, (signed char)x);
  return r;
}

static int wasm_i8x16_extract_lane_s(v128_t a, int k) {
  return (int)__wsimd_get_i8(a, k);
}

static int wasm_i8x16_extract_lane_u(v128_t a, int k) {
  return (int)__wsimd_get_u8(a, k);
}

static v128_t wasm_i8x16_replace_lane(v128_t a, int k, int x) {
  v128_t r = a; __wsimd_set_i8(&r, k, (signed char)x); return r;
}

static v128_t wasm_i16x8_splat(int x) {
  v128_t r; int k;
  for (k = 0; k < 8; k++)
    __wsimd_set_i16(&r, k, (short)x);
  return r;
}

static int wasm_i16x8_extract_lane_s(v128_t a, int k) {
  return (int)__wsimd_get_i16(a, k);
}

static int wasm_i16x8_extract_lane_u(v128_t a, int k) {
  return (int)__wsimd_get_u16(a, k);
}

static v128_t wasm_i16x8_replace_lane(v128_t a, int k, int x) {
  v128_t r = a; __wsimd_set_i16(&r, k, (short)x); return r;
}

static v128_t wasm_i32x4_splat(int x) {
  v128_t r; int k;
  for (k = 0; k < 4; k++)
    __wsimd_set_i32(&r, k, (int)x);
  return r;
}

static int wasm_i32x4_extract_lane(v128_t a, int k) {
  return (int)__wsimd_get_i32(a, k);
}

static v128_t wasm_i32x4_replace_lane(v128_t a, int k, int x) {
  v128_t r = a; __wsimd_set_i32(&r, k, (int)x); return r;
}

static v128_t wasm_i64x2_splat(long x) {
  v128_t r; int k;
  for (k = 0; k < 2; k++)
    __wsimd_set_i64(&r, k, (long)x);
  return r;
}

static long wasm_i64x2_extract_lane(v128_t a, int k) {
  return (long)__wsimd_get_i64(a, k);
}

static v128_t wasm_i64x2_replace_lane(v128_t a, int k, long x) {
  v128_t r = a; __wsimd_set_i64(&r, k, (long)x); return r;
}

static v128_t wasm_f32x4_splat(float x) {
  v128_t r; int k;
  for (k = 0; k < 4; k++)
    __wsimd_set_f32(&r, k, (float)x);
  return r;
}

static float wasm_f32x4_extract_lane(v128_t a, int k) {
  return (float)__wsimd_get_f32(a, k);
}

static v128_t wasm_f32x4_replace_lane(v128_t a, int k, float x) {
  v128_t r = a; __wsimd_set_f32(&r, k, (float)x); return r;
}

static v128_t wasm_f64x2_splat(double x) {
  v128_t r; int k;
  for (k = 0; k < 2; k++)
    __wsimd_set_f64(&r, k, (double)x);
  return r;
}

static double wasm_f64x2_extract_lane(v128_t a, int k) {
  return (double)__wsimd_get_f64(a, k);
}

static v128_t wasm_f64x2_replace_lane(v128_t a, int k, double x) {
  v128_t r = a; __wsimd_set_f64(&r, k, (double)x); return r;
}

static v128_t wasm_v128_and(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    unsigned long x = __wsimd_get_u64(a, k), y = __wsimd_get_u64(b, k);
    __wsimd_set_u64(&r, k, x & y);
  }
  return r;
}

static v128_t wasm_v128_or(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    unsigned long x = __wsimd_get_u64(a, k), y = __wsimd_get_u64(b, k);
    __wsimd_set_u64(&r, k, x | y);
  }
  return r;
}

static v128_t wasm_v128_xor(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    unsigned long x = __wsimd_get_u64(a, k), y = __wsimd_get_u64(b, k);
    __wsimd_set_u64(&r, k, x ^ y);
  }
  return r;
}

static v128_t wasm_v128_andnot(v128_t a, v128_t b) {
  v128_t r; int k;
  for (k = 0; k < 2; k++) {
    unsigned long x = __wsimd_get_u64(a, k), y = __wsimd_get_u64(b, k);
    __wsimd_set_u64(&r, k, x & ~y);
  }
  return r;
}

static v128_t wasm_v128_not(v128_t a) {
  v128_t r; int k;
  for (k = 0; k < 2; k++)
    __wsimd_set_u64(&r, k, ~__wsimd_get_u64(a, k));
  return r;
}

static v128_t wasm_v128_bitselect(v128_t a, v128_t b, v128_t c) {
  v128_t r; int k;
  /* Set bits of c select from a, clear bits from b. */
  for (k = 0; k < 2; k++) {
    unsigned long x = __wsimd_get_u64(a, k), y = __wsimd_get_u64(b, k), m = __wsimd_get_u64(c, k);
    __wsimd_set_u64(&r, k, (x & m) | (y & ~m));
  }
  return r;
}

static int wasm_v128_any_true(v128_t a) {
  return (__wsimd_get_u64(a, 0) | __wsimd_get_u64(a, 1)) != 0;
}

static int wasm_i8x16_all_true(v128_t a) {
  int k;
  for (k = 0; k < 16; k++)
    if (!__wsimd_get_u8(a, k)) return 0;
  return 1;
}

static int wasm_i8x16_bitmask(v128_t a) {
  int k, m = 0;
  for (k = 0; k < 16; k++)
    if (__wsimd_get_i8(a, k) < 0) m |= 1 << k;
  return m;
}

static int wasm_i16x8_all_true(v128_t a) {
  int k;
  for (k = 0; k < 8; k++)
    if (!__wsimd_get_u16(a, k)) return 0;
  return 1;
}

static int wasm_i16x8_bitmask(v128_t a) {
  int k, m = 0;
  for (k = 0; k < 8; k++)
    if (__wsimd_get_i16(a, k) < 0) m |= 1 << k;
  return m;
}

static int wasm_i32x4_all_true(v128_t a) {
  int k;
  for (k = 0; k < 4; k++)
    if (!__wsimd_get_u32(a, k)) return 0;
  return 1;
}

static int wasm_i32x4_bitmask(v128_t a) {
  int k, m = 0;
  for (k = 0; k < 4; k++)
    if (__wsimd_get_i32(a, k) < 0) m |= 1 << k;
  return m;
}

static int wasm_i64x2_all_true(v128_t a) {
  int k;
  for (k = 0; k < 2; k++)
    if (!__wsimd_get_u64(a, k)) return 0;
  return 1;
}

static int wasm_i64x2_bitmask(v128_t a) {
  int k, m = 0;
  for (k = 0; k < 2; k++)
    if (__wsimd_get_i64(a, k) < 0) m |= 1 << k;
  return m;
}

#endif  /* __wasm__ */

#endif  /* _WASM_SIMD128_H */
