#!/usr/bin/env python3
"""Package runtime/crust_re.{h,c} into tools/rpy_lib/crust_re_src.py.

py2c emits one self-contained C file, so the engine source has to travel as a
string -- the same approach shivyc/musl/*.py uses for musl's sources. This
generates that module from the real files so the two cannot drift.

  python3 pack_crust_re.py           # regenerate
  python3 pack_crust_re.py --check   # exit 1 if stale (for CI)
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC_C = os.path.join(ROOT, "runtime", "crust_re.c")
SRC_H = os.path.join(ROOT, "runtime", "crust_re.h")
OUT = os.path.join(HERE, "rpy_lib", "crust_re_src.py")

HEADER = '''"""Packaged crust_re source (auto-generated by tools/pack_crust_re.py).

Do not edit by hand -- edit runtime/crust_re.{h,c} and re-run the packer.
py2c inlines HEADER + SOURCE into the C it emits when a pattern needs the
full regex VM rather than a specialized translation-time matcher.
"""

'''


def read(path):
    text = open(path, encoding="utf-8").read()
    if "'''" in text:
        sys.exit("pack_crust_re: %s contains a triple quote; "
                 "the packer cannot quote it" % path)
    return text


def build():
    h = read(SRC_H)
    c = read(SRC_C)
    # The packaged copy is compiled as one translation unit with the rest of
    # the generated program, so the #include of the header is dropped and the
    # header text is inlined ahead of it instead.
    c = c.replace('#include "crust_re.h"\n', "")
    out = [HEADER]
    out.append("HEADER = r'''")
    out.append(h)
    out.append("'''\n")
    out.append("SOURCE = r'''")
    out.append(c)
    out.append("'''\n")
    return "".join(out)


def main():
    want = build()
    if "--check" in sys.argv:
        try:
            have = open(OUT, encoding="utf-8").read()
        except OSError:
            have = None
        if have != want:
            sys.exit("crust_re_src.py is stale; run: python3 tools/pack_crust_re.py")
        print("crust_re_src.py: in sync with runtime/crust_re.{h,c}")
        return
    open(OUT, "w", encoding="utf-8").write(want)
    print("crust_re_src.py: regenerated (%d bytes)" % len(want))


main()
