/* Runtime support for C generated by tools/wasm2c.py.
 *
 * The generated code is plain C99 that says what each wasm instruction means;
 * everything here is the handful of operations that cannot be written as a
 * direct C expression without either being wrong or being undefined:
 *
 *   - Division and remainder. Wasm traps on a zero divisor and *defines*
 *     INT_MIN % -1 as 0, where C leaves both undefined.
 *   - Shifts. Wasm masks the shift count to the operand width; C leaves an
 *     over-wide shift undefined.
 *   - Rotates, clz/ctz/popcnt, which C has no operators for.
 *   - Saturating float-to-int, which clamps where a C cast is undefined.
 *   - Memory access, which goes through memcpy so that an unaligned or
 *     type-punned load is not undefined behaviour.
 *
 * Written independently of wabt's wasm2c. The overall approach -- flattening
 * the operand stack into typed temporaries, and lowering wasm's structured
 * control flow to labels and goto -- is the obvious one and is shared with
 * that tool and others, but no code is taken from it. This file and its
 * generator are MIT, like the rest of the tree.
 */
#ifndef WASM2C_RT_H
#define WASM2C_RT_H

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>

typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

/* A wasm trap. The generated code has no way to unwind, and a trap is
 * unrecoverable for our purposes, so this exits with a distinctive status. */
static void wasm_trap(const char *what) {
    /* To stderr, so a trap cannot interleave with the stdout a differential
     * test is comparing. An earlier version hand-declared `stderr` to avoid
     * including <stdio.h>; that conflicts with the real declaration the
     * moment any other header pulls stdio in, so it is included properly. */
    fputs("wasm trap: ", stderr);
    fputs(what, stderr);
    fputs("\n", stderr);
    exit(134);
}

/* ---------------------------------------------------------- integer ops */

#define WASM_DIV_S(T, MIN, a, b)                                        \
    ((b) == 0 ? (wasm_trap("integer divide by zero"), (T)0)             \
     : ((a) == (MIN) && (b) == -1) ? (wasm_trap("integer overflow"), (T)0) \
     : (T)((a) / (b)))

#define WASM_REM_S(T, MIN, a, b)                                        \
    ((b) == 0 ? (wasm_trap("integer divide by zero"), (T)0)             \
     /* Wasm defines INT_MIN %% -1 as 0; C leaves it undefined. */       \
     : ((a) == (MIN) && (b) == -1) ? (T)0                               \
     : (T)((a) % (b)))

#define WASM_DIV_U(T, a, b)                                             \
    ((b) == 0 ? (wasm_trap("integer divide by zero"), (T)0) : (T)((a) / (b)))

#define WASM_REM_U(T, a, b)                                             \
    ((b) == 0 ? (wasm_trap("integer divide by zero"), (T)0) : (T)((a) % (b)))

static u32 wasm_i32_div_s(u32 a, u32 b) {
    return (u32)WASM_DIV_S(s32, INT32_MIN, (s32)a, (s32)b);
}
static u32 wasm_i32_rem_s(u32 a, u32 b) {
    return (u32)WASM_REM_S(s32, INT32_MIN, (s32)a, (s32)b);
}
static u64 wasm_i64_div_s(u64 a, u64 b) {
    return (u64)WASM_DIV_S(s64, INT64_MIN, (s64)a, (s64)b);
}
static u64 wasm_i64_rem_s(u64 a, u64 b) {
    return (u64)WASM_REM_S(s64, INT64_MIN, (s64)a, (s64)b);
}
static u32 wasm_i32_div_u(u32 a, u32 b) { return WASM_DIV_U(u32, a, b); }
static u32 wasm_i32_rem_u(u32 a, u32 b) { return WASM_REM_U(u32, a, b); }
static u64 wasm_i64_div_u(u64 a, u64 b) { return WASM_DIV_U(u64, a, b); }
static u64 wasm_i64_rem_u(u64 a, u64 b) { return WASM_REM_U(u64, a, b); }

/* Shift counts are masked to the operand width, which is what wasm specifies
 * and what the hardware does anyway; in C an over-wide shift is undefined. */
static u32 wasm_i32_shl(u32 a, u32 b)   { return a << (b & 31); }
static u32 wasm_i32_shr_u(u32 a, u32 b) { return a >> (b & 31); }
static u32 wasm_i32_shr_s(u32 a, u32 b) { return (u32)((s32)a >> (b & 31)); }
static u64 wasm_i64_shl(u64 a, u64 b)   { return a << (b & 63); }
static u64 wasm_i64_shr_u(u64 a, u64 b) { return a >> (b & 63); }
static u64 wasm_i64_shr_s(u64 a, u64 b) { return (u64)((s64)a >> (b & 63)); }

static u32 wasm_i32_rotl(u32 a, u32 b) {
    b &= 31; return b ? ((a << b) | (a >> (32 - b))) : a;
}
static u32 wasm_i32_rotr(u32 a, u32 b) {
    b &= 31; return b ? ((a >> b) | (a << (32 - b))) : a;
}
static u64 wasm_i64_rotl(u64 a, u64 b) {
    b &= 63; return b ? ((a << b) | (a >> (64 - b))) : a;
}
static u64 wasm_i64_rotr(u64 a, u64 b) {
    b &= 63; return b ? ((a >> b) | (a << (64 - b))) : a;
}

static u32 wasm_i32_clz(u32 a) {
    u32 n = 0; if (!a) return 32;
    while (!(a & 0x80000000u)) { a <<= 1; n++; }
    return n;
}
static u32 wasm_i32_ctz(u32 a) {
    u32 n = 0; if (!a) return 32;
    while (!(a & 1u)) { a >>= 1; n++; }
    return n;
}
static u32 wasm_i32_popcnt(u32 a) {
    u32 n = 0; while (a) { n += a & 1u; a >>= 1; }
    return n;
}
static u64 wasm_i64_clz(u64 a) {
    u64 n = 0; if (!a) return 64;
    while (!(a & 0x8000000000000000ull)) { a <<= 1; n++; }
    return n;
}
static u64 wasm_i64_ctz(u64 a) {
    u64 n = 0; if (!a) return 64;
    while (!(a & 1ull)) { a >>= 1; n++; }
    return n;
}
static u64 wasm_i64_popcnt(u64 a) {
    u64 n = 0; while (a) { n += a & 1ull; a >>= 1; }
    return n;
}

/* ------------------------------------------------- float and conversion */

static f32 wasm_f32_min(f32 a, f32 b) {
    if (isnan(a) || isnan(b)) return (f32)NAN;
    if (a == 0 && b == 0) return signbit(a) ? a : b;
    return a < b ? a : b;
}
static f32 wasm_f32_max(f32 a, f32 b) {
    if (isnan(a) || isnan(b)) return (f32)NAN;
    if (a == 0 && b == 0) return signbit(a) ? b : a;
    return a > b ? a : b;
}
static f64 wasm_f64_min(f64 a, f64 b) {
    if (isnan(a) || isnan(b)) return (f64)NAN;
    if (a == 0 && b == 0) return signbit(a) ? a : b;
    return a < b ? a : b;
}
static f64 wasm_f64_max(f64 a, f64 b) {
    if (isnan(a) || isnan(b)) return (f64)NAN;
    if (a == 0 && b == 0) return signbit(a) ? b : a;
    return a > b ? a : b;
}

/* Saturating float-to-int: NaN becomes 0 and out-of-range clamps, where the
 * plain C cast would be undefined. */
#define WASM_TRUNC_SAT(NAME, IN, OUT, SOUT, LO, HI)                     \
    static OUT NAME(IN v) {                                             \
        if (isnan(v)) return (OUT)0;                                    \
        if (v <= (IN)(LO)) return (OUT)(SOUT)(LO);                      \
        if (v >= (IN)(HI)) return (OUT)(SOUT)(HI);                      \
        return (OUT)(SOUT)v;                                            \
    }

WASM_TRUNC_SAT(wasm_i32_trunc_sat_f32_s, f32, u32, s32, INT32_MIN, INT32_MAX)
WASM_TRUNC_SAT(wasm_i32_trunc_sat_f64_s, f64, u32, s32, INT32_MIN, INT32_MAX)
WASM_TRUNC_SAT(wasm_i64_trunc_sat_f32_s, f32, u64, s64, INT64_MIN, INT64_MAX)
WASM_TRUNC_SAT(wasm_i64_trunc_sat_f64_s, f64, u64, s64, INT64_MIN, INT64_MAX)

#define WASM_TRUNC_SAT_U(NAME, IN, OUT, HI)                             \
    static OUT NAME(IN v) {                                             \
        if (isnan(v) || v <= (IN)0) return (OUT)0;                      \
        if (v >= (IN)(HI)) return (OUT)(HI);                            \
        return (OUT)v;                                                  \
    }

WASM_TRUNC_SAT_U(wasm_i32_trunc_sat_f32_u, f32, u32, UINT32_MAX)
WASM_TRUNC_SAT_U(wasm_i32_trunc_sat_f64_u, f64, u32, UINT32_MAX)
WASM_TRUNC_SAT_U(wasm_i64_trunc_sat_f32_u, f32, u64, UINT64_MAX)
WASM_TRUNC_SAT_U(wasm_i64_trunc_sat_f64_u, f64, u64, UINT64_MAX)

/* The trapping conversions, for modules that use them. */
#define WASM_TRUNC(NAME, IN, OUT, SOUT, LO, HI)                         \
    static OUT NAME(IN v) {                                             \
        if (isnan(v)) { wasm_trap("invalid conversion to integer"); }   \
        if (v <= (IN)(LO) - 1 || v >= (IN)(HI) + 1)                     \
            { wasm_trap("integer overflow"); }                          \
        return (OUT)(SOUT)v;                                            \
    }
WASM_TRUNC(wasm_i32_trunc_f32_s, f32, u32, s32, INT32_MIN, INT32_MAX)
WASM_TRUNC(wasm_i32_trunc_f64_s, f64, u32, s32, INT32_MIN, INT32_MAX)
WASM_TRUNC(wasm_i64_trunc_f32_s, f32, u64, s64, INT64_MIN, INT64_MAX)
WASM_TRUNC(wasm_i64_trunc_f64_s, f64, u64, s64, INT64_MIN, INT64_MAX)
#define wasm_i32_trunc_f32_u wasm_i32_trunc_sat_f32_u
#define wasm_i32_trunc_f64_u wasm_i32_trunc_sat_f64_u
#define wasm_i64_trunc_f32_u wasm_i64_trunc_sat_f32_u
#define wasm_i64_trunc_f64_u wasm_i64_trunc_sat_f64_u

/* Bit-preserving reinterpretation, via memcpy so that no aliasing rule is
 * broken -- every compiler folds this to a register move. */
static u32 wasm_f32_bits(f32 v) { u32 r; memcpy(&r, &v, 4); return r; }
static f32 wasm_f32_from_bits(u32 v) { f32 r; memcpy(&r, &v, 4); return r; }
static u64 wasm_f64_bits(f64 v) { u64 r; memcpy(&r, &v, 8); return r; }
static f64 wasm_f64_from_bits(u64 v) { f64 r; memcpy(&r, &v, 8); return r; }

/* ---------------------------------------------------------- memory ------ */

/* Every access goes through memcpy: linear memory is a byte array, and
 * reading a u32 out of it by pointer cast would be both unaligned and an
 * aliasing violation. Compilers turn these into single instructions. */
#define WASM_LOAD(NAME, T, N)                                           \
    static T NAME(const u8 *mem, u64 size, u32 addr) {                  \
        T v;                                                            \
        if ((u64)addr + (N) > size) wasm_trap("out of bounds memory access"); \
        memcpy(&v, mem + addr, (N));                                    \
        return v;                                                       \
    }

WASM_LOAD(wasm_load_u8, u8, 1)
WASM_LOAD(wasm_load_u16, u16, 2)
WASM_LOAD(wasm_load_u32, u32, 4)
WASM_LOAD(wasm_load_u64, u64, 8)
WASM_LOAD(wasm_load_f32, f32, 4)
WASM_LOAD(wasm_load_f64, f64, 8)

#define WASM_STORE(NAME, T, N)                                          \
    static void NAME(u8 *mem, u64 size, u32 addr, T v) {                \
        if ((u64)addr + (N) > size) wasm_trap("out of bounds memory access"); \
        memcpy(mem + addr, &v, (N));                                    \
    }

WASM_STORE(wasm_store_u8, u8, 1)
WASM_STORE(wasm_store_u16, u16, 2)
WASM_STORE(wasm_store_u32, u32, 4)
WASM_STORE(wasm_store_u64, u64, 8)
WASM_STORE(wasm_store_f32, f32, 4)
WASM_STORE(wasm_store_f64, f64, 8)

static void wasm_memory_copy(u8 *mem, u64 size, u32 dst, u32 src, u32 n) {
    if ((u64)dst + n > size || (u64)src + n > size)
        wasm_trap("out of bounds memory access");
    memmove(mem + dst, mem + src, n);     /* wasm defines copy as overlap-safe */
}

static void wasm_memory_fill(u8 *mem, u64 size, u32 dst, u32 val, u32 n) {
    if ((u64)dst + n > size) wasm_trap("out of bounds memory access");
    memset(mem + dst, (int)(val & 0xFF), n);
}

#endif /* WASM2C_RT_H */
