/* WASI preview-1 imports for C generated by tools/wasm2c.py.
 *
 * A translated module still calls the host functions its imports named. This
 * binds them to POSIX, so a module that came from C originally becomes a
 * native binary that behaves the same as compiling that C directly -- which
 * is what makes the round trip
 *
 *     prog.c --shivyc--> prog.wasm --wasm2c--> prog2.c --cc--> a.out
 *
 * checkable against a plain `cc prog.c`.
 *
 * The names are those wasm2c.py generates for imports:
 * wasm_import_<module>_<field>. Only the calls the toolchain actually emits
 * are implemented; the rest return ENOSYS rather than being absent, so a
 * module that merely *probes* for a capability still links.
 */
#ifndef WASM2C_RT_WASI_H
#define WASM2C_RT_WASI_H

#include <unistd.h>
#include <stdlib.h>
#include <string.h>

/* Linear memory belongs to the generated file, so this header is included
 * *after* it defines `mem` and MEM_SIZE rather than before -- the shims below
 * take wasm addresses and have to reach into it. */
#ifndef MEM_SIZE
#error "include wasm2c_rt_wasi.h after the generated memory definition"
#endif

/* Where the exit status lands. `proc_exit` does not return in wasm, and the
 * generated `main` reads this after `_start`. */
static int wasm_exit_code = 0;

#define WASI_ERRNO_SUCCESS 0
#define WASI_ERRNO_BADF    8
#define WASI_ERRNO_NOSYS  52

static u32 wasm_wasi_load32(u32 addr) {
    u32 v;
    if ((u64)addr + 4 > MEM_SIZE) wasm_trap("out of bounds memory access");
    memcpy(&v, mem + addr, 4);
    return v;
}

static void wasm_wasi_store32(u32 addr, u32 v) {
    if ((u64)addr + 4 > MEM_SIZE) wasm_trap("out of bounds memory access");
    memcpy(mem + addr, &v, 4);
}

/* fd_write(fd, iovs, iovs_len, nwritten) -> errno
 *
 * Each iovec is two little-endian 32-bit fields -- a pointer into linear
 * memory and a length -- exactly as the module laid them out. */
static u32 wasm_import_wasi_snapshot_preview1_fd_write(
        u32 fd, u32 iovs, u32 iovs_len, u32 nwritten) {
    u32 total = 0;
    u32 i;
    if (fd != 1 && fd != 2) return WASI_ERRNO_BADF;
    for (i = 0; i < iovs_len; i++) {
        u32 base = iovs + i * 8;
        u32 ptr = wasm_wasi_load32(base);
        u32 len = wasm_wasi_load32(base + 4);
        if ((u64)ptr + len > MEM_SIZE)
            wasm_trap("out of bounds memory access");
        if (len) {
            ssize_t n = write((int)fd, mem + ptr, (size_t)len);
            if (n < 0) return WASI_ERRNO_BADF;
            total += (u32)n;
        }
    }
    wasm_wasi_store32(nwritten, total);
    return WASI_ERRNO_SUCCESS;
}

static void wasm_import_wasi_snapshot_preview1_proc_exit(u32 code) {
    /* Flushing is not needed: fd_write above goes straight to write(2). */
    exit((int)(code & 0xFF));
}

static u32 wasm_import_wasi_snapshot_preview1_fd_read(
        u32 fd, u32 iovs, u32 iovs_len, u32 nread) {
    u32 total = 0;
    u32 i;
    for (i = 0; i < iovs_len; i++) {
        u32 base = iovs + i * 8;
        u32 ptr = wasm_wasi_load32(base);
        u32 len = wasm_wasi_load32(base + 4);
        if ((u64)ptr + len > MEM_SIZE)
            wasm_trap("out of bounds memory access");
        if (len) {
            ssize_t n = read((int)fd, mem + ptr, (size_t)len);
            if (n < 0) return WASI_ERRNO_BADF;
            total += (u32)n;
            if ((u32)n < len) break;
        }
    }
    wasm_wasi_store32(nread, total);
    return WASI_ERRNO_SUCCESS;
}

static u32 wasm_import_wasi_snapshot_preview1_fd_close(u32 fd) {
    (void)fd; return WASI_ERRNO_SUCCESS;
}
static u32 wasm_import_wasi_snapshot_preview1_fd_seek(
        u32 a, u64 b, u32 c, u32 d) {
    (void)a; (void)b; (void)c; (void)d; return WASI_ERRNO_NOSYS;
}
static u32 wasm_import_wasi_snapshot_preview1_fd_fdstat_get(u32 a, u32 b) {
    (void)a; (void)b; return WASI_ERRNO_NOSYS;
}
static u32 wasm_import_wasi_snapshot_preview1_path_open(
        u32 a, u32 b, u32 c, u32 d, u32 e, u64 f, u64 g, u32 h, u32 i) {
    (void)a; (void)b; (void)c; (void)d; (void)e;
    (void)f; (void)g; (void)h; (void)i;
    return WASI_ERRNO_NOSYS;
}
static u32 wasm_import_wasi_snapshot_preview1_environ_get(u32 a, u32 b) {
    (void)a; (void)b; return WASI_ERRNO_SUCCESS;
}
static u32 wasm_import_wasi_snapshot_preview1_environ_sizes_get(
        u32 count, u32 size) {
    wasm_wasi_store32(count, 0);
    wasm_wasi_store32(size, 0);
    return WASI_ERRNO_SUCCESS;
}
static u32 wasm_import_wasi_snapshot_preview1_args_get(u32 a, u32 b) {
    (void)a; (void)b; return WASI_ERRNO_SUCCESS;
}
static u32 wasm_import_wasi_snapshot_preview1_args_sizes_get(
        u32 argc, u32 size) {
    wasm_wasi_store32(argc, 0);
    wasm_wasi_store32(size, 0);
    return WASI_ERRNO_SUCCESS;
}
static u32 wasm_import_wasi_snapshot_preview1_random_get(u32 a, u32 b) {
    (void)a; (void)b; return WASI_ERRNO_NOSYS;
}
static u32 wasm_import_wasi_snapshot_preview1_clock_time_get(
        u32 a, u64 b, u32 c) {
    (void)a; (void)b; (void)c; return WASI_ERRNO_NOSYS;
}

#endif /* WASM2C_RT_WASI_H */
