/* SIMD (v128) support for C generated by tools/wasm2c.py.
 *
 * A v128 is a union of arrays, one per lane shape. That is the whole trick:
 * `i32x4.add` becomes a four-iteration loop over `.u32x4`, and the generator
 * needs to know nothing about the operation beyond its lane count, its field
 * name and its C operator. Reading a lane through a different member than it
 * was written is type punning through a union, which C99 explicitly permits.
 *
 * No vector intrinsics are used. The point is portable C that says exactly
 * what the specification says; compilers re-vectorise these loops perfectly
 * well, and correctness is checkable against a real wasm engine.
 */
#ifndef WASM2C_RT_SIMD_H
#define WASM2C_RT_SIMD_H

#include "wasm2c_rt.h"

typedef union {
    u8  u8x16[16];  s8  s8x16[16];
    u16 u16x8[8];   s16 s16x8[8];
    u32 u32x4[4];   s32 s32x4[4];
    u64 u64x2[2];   s64 s64x2[2];
    f32 f32x4[4];   f64 f64x2[2];
    u8  bytes[16];
} v128;

/* Lanes are little-endian in memory, which is what the union gives us on
 * every target wasm2c output is compiled for. */
static v128 wasm_v128_load(const u8 *mem, u64 size, u32 addr) {
    v128 v;
    if ((u64)addr + 16 > size) wasm_trap("out of bounds memory access");
    memcpy(v.bytes, mem + addr, 16);
    return v;
}

static void wasm_v128_store(u8 *mem, u64 size, u32 addr, v128 v) {
    if ((u64)addr + 16 > size) wasm_trap("out of bounds memory access");
    memcpy(mem + addr, v.bytes, 16);
}

static v128 wasm_v128_zero(void) {
    v128 v;
    memset(v.bytes, 0, 16);
    return v;
}

/* -------------------------------------------------------- bitwise ------ */

#define WASM_V128_BITWISE(NAME, EXPR)                                   \
    static v128 NAME(v128 a, v128 b) {                                  \
        v128 r; int k;                                                  \
        for (k = 0; k < 2; k++) { u64 x = a.u64x2[k], y = b.u64x2[k];    \
                                  r.u64x2[k] = (EXPR); }                \
        return r;                                                       \
    }

WASM_V128_BITWISE(wasm_v128_and, x & y)
WASM_V128_BITWISE(wasm_v128_or, x | y)
WASM_V128_BITWISE(wasm_v128_xor, x ^ y)
WASM_V128_BITWISE(wasm_v128_andnot, x & ~y)

static v128 wasm_v128_not(v128 a) {
    v128 r; int k;
    for (k = 0; k < 2; k++) r.u64x2[k] = ~a.u64x2[k];
    return r;
}

static v128 wasm_v128_bitselect(v128 a, v128 b, v128 c) {
    v128 r; int k;
    /* Bits of `c` that are set select from `a`, clear bits from `b`. */
    for (k = 0; k < 2; k++)
        r.u64x2[k] = (a.u64x2[k] & c.u64x2[k]) | (b.u64x2[k] & ~c.u64x2[k]);
    return r;
}

static u32 wasm_v128_any_true(v128 a) {
    return (a.u64x2[0] | a.u64x2[1]) != 0;
}

/* ------------------------------------------------------- lane helpers -- */

/* all_true and bitmask are per shape but identical in form, so they are
 * generated the same way the operators are. */
#define WASM_ALL_TRUE(NAME, FIELD, N)                                   \
    static u32 NAME(v128 a) {                                           \
        int k;                                                          \
        for (k = 0; k < (N); k++) if (!a.FIELD[k]) return 0;            \
        return 1;                                                       \
    }
WASM_ALL_TRUE(wasm_i8x16_all_true, u8x16, 16)
WASM_ALL_TRUE(wasm_i16x8_all_true, u16x8, 8)
WASM_ALL_TRUE(wasm_i32x4_all_true, u32x4, 4)
WASM_ALL_TRUE(wasm_i64x2_all_true, u64x2, 2)

#define WASM_BITMASK(NAME, FIELD, N)                                    \
    static u32 NAME(v128 a) {                                           \
        u32 m = 0; int k;                                               \
        for (k = 0; k < (N); k++) if (a.FIELD[k] < 0) m |= 1u << k;     \
        return m;                                                       \
    }
WASM_BITMASK(wasm_i8x16_bitmask, s8x16, 16)
WASM_BITMASK(wasm_i16x8_bitmask, s16x8, 8)
WASM_BITMASK(wasm_i32x4_bitmask, s32x4, 4)
WASM_BITMASK(wasm_i64x2_bitmask, s64x2, 2)

/* Saturating add/sub. The lane arithmetic is done in a wider type and then
 * clamped, which is both correct and obviously so. */
#define WASM_SAT(NAME, FIELD, N, WIDE, LO, HI)                          \
    static v128 NAME(v128 a, v128 b, int sub) {                         \
        v128 r; int k;                                                  \
        for (k = 0; k < (N); k++) {                                     \
            WIDE t = sub ? (WIDE)a.FIELD[k] - (WIDE)b.FIELD[k]          \
                         : (WIDE)a.FIELD[k] + (WIDE)b.FIELD[k];         \
            if (t < (WIDE)(LO)) t = (WIDE)(LO);                         \
            if (t > (WIDE)(HI)) t = (WIDE)(HI);                         \
            r.FIELD[k] = t;                                             \
        }                                                               \
        return r;                                                       \
    }
WASM_SAT(wasm_i8x16_sat_s, s8x16, 16, s32, -128, 127)
WASM_SAT(wasm_i8x16_sat_u, u8x16, 16, s32, 0, 255)
WASM_SAT(wasm_i16x8_sat_s, s16x8, 8, s32, -32768, 32767)
WASM_SAT(wasm_i16x8_sat_u, u16x8, 8, s32, 0, 65535)

/* i8x16.swizzle: each lane of `b` selects a byte of `a`, out of range gives
 * zero. i8x16.shuffle is the same with the selectors as immediates and two
 * source vectors, so the generator emits it inline. */
static v128 wasm_i8x16_swizzle(v128 a, v128 b) {
    v128 r; int k;
    for (k = 0; k < 16; k++) {
        u8 sel = b.u8x16[k];
        r.u8x16[k] = (sel < 16) ? a.u8x16[sel] : 0;
    }
    return r;
}

static v128 wasm_i8x16_splat(u32 x) {
    v128 r; int k;
    for (k = 0; k < 16; k++) r.u8x16[k] = (u8)x;
    return r;
}
static v128 wasm_i16x8_splat(u32 x) {
    v128 r; int k;
    for (k = 0; k < 8; k++) r.u16x8[k] = (u16)x;
    return r;
}
static v128 wasm_i32x4_splat(u32 x) {
    v128 r; int k;
    for (k = 0; k < 4; k++) r.u32x4[k] = x;
    return r;
}
static v128 wasm_i64x2_splat(u64 x) {
    v128 r; int k;
    for (k = 0; k < 2; k++) r.u64x2[k] = x;
    return r;
}
static v128 wasm_f32x4_splat(f32 x) {
    v128 r; int k;
    for (k = 0; k < 4; k++) r.f32x4[k] = x;
    return r;
}
static v128 wasm_f64x2_splat(f64 x) {
    v128 r; int k;
    for (k = 0; k < 2; k++) r.f64x2[k] = x;
    return r;
}

/* The splat loads: read one lane's worth and broadcast it. */
static v128 wasm_v128_load8_splat(const u8 *m, u64 sz, u32 a) {
    return wasm_i8x16_splat(wasm_load_u8(m, sz, a));
}
static v128 wasm_v128_load16_splat(const u8 *m, u64 sz, u32 a) {
    return wasm_i16x8_splat(wasm_load_u16(m, sz, a));
}
static v128 wasm_v128_load32_splat(const u8 *m, u64 sz, u32 a) {
    return wasm_i32x4_splat(wasm_load_u32(m, sz, a));
}
static v128 wasm_v128_load64_splat(const u8 *m, u64 sz, u32 a) {
    return wasm_i64x2_splat(wasm_load_u64(m, sz, a));
}

static v128 wasm_v128_load32_zero(const u8 *m, u64 sz, u32 a) {
    v128 r = wasm_v128_zero();
    r.u32x4[0] = wasm_load_u32(m, sz, a);
    return r;
}
static v128 wasm_v128_load64_zero(const u8 *m, u64 sz, u32 a) {
    v128 r = wasm_v128_zero();
    r.u64x2[0] = wasm_load_u64(m, sz, a);
    return r;
}

/* The widening loads: eight (or four, or two) narrow lanes read from memory
 * and sign- or zero-extended into the next shape up. */
#define WASM_LOAD_EXTEND(NAME, DST, SRCT, N, LOADER)                    \
    static v128 NAME(const u8 *m, u64 sz, u32 a) {                      \
        v128 r; int k;                                                  \
        if ((u64)a + 8 > sz) wasm_trap("out of bounds memory access");  \
        for (k = 0; k < (N); k++)                                       \
            r.DST[k] = (SRCT)LOADER(m, sz, a + k * (8 / (N)));          \
        return r;                                                       \
    }
WASM_LOAD_EXTEND(wasm_v128_load8x8_s, s16x8, s8, 8, wasm_load_u8)
WASM_LOAD_EXTEND(wasm_v128_load8x8_u, u16x8, u8, 8, wasm_load_u8)
WASM_LOAD_EXTEND(wasm_v128_load16x4_s, s32x4, s16, 4, wasm_load_u16)
WASM_LOAD_EXTEND(wasm_v128_load16x4_u, u32x4, u16, 4, wasm_load_u16)
WASM_LOAD_EXTEND(wasm_v128_load32x2_s, s64x2, s32, 2, wasm_load_u32)
WASM_LOAD_EXTEND(wasm_v128_load32x2_u, u64x2, u32, 2, wasm_load_u32)

/* Narrowing: two source vectors' lanes clamped into one narrower vector. */
#define WASM_NARROW(NAME, DSTF, SRCF, N, LO, HI)                        \
    static v128 NAME(v128 a, v128 b) {                                  \
        v128 r; int k;                                                  \
        for (k = 0; k < (N); k++) {                                     \
            s32 x = (s32)a.SRCF[k];                                     \
            r.DSTF[k] = x < (LO) ? (LO) : (x > (HI) ? (HI) : x);        \
            x = (s32)b.SRCF[k];                                         \
            r.DSTF[k + (N)] = x < (LO) ? (LO) : (x > (HI) ? (HI) : x);  \
        }                                                               \
        return r;                                                       \
    }
WASM_NARROW(wasm_i8x16_narrow_i16x8_s, s8x16, s16x8, 8, -128, 127)
WASM_NARROW(wasm_i8x16_narrow_i16x8_u, u8x16, s16x8, 8, 0, 255)
WASM_NARROW(wasm_i16x8_narrow_i32x4_s, s16x8, s32x4, 4, -32768, 32767)
WASM_NARROW(wasm_i16x8_narrow_i32x4_u, u16x8, s32x4, 4, 0, 65535)

/* Extending half a vector into the next shape up. */
#define WASM_EXTEND(NAME, DSTF, SRCF, N, HIGH)                          \
    static v128 NAME(v128 a) {                                          \
        v128 r; int k;                                                  \
        for (k = 0; k < (N); k++) r.DSTF[k] = a.SRCF[k + (HIGH)];       \
        return r;                                                       \
    }
WASM_EXTEND(wasm_i16x8_extend_low_i8x16_s, s16x8, s8x16, 8, 0)
WASM_EXTEND(wasm_i16x8_extend_high_i8x16_s, s16x8, s8x16, 8, 8)
WASM_EXTEND(wasm_i16x8_extend_low_i8x16_u, u16x8, u8x16, 8, 0)
WASM_EXTEND(wasm_i16x8_extend_high_i8x16_u, u16x8, u8x16, 8, 8)
WASM_EXTEND(wasm_i32x4_extend_low_i16x8_s, s32x4, s16x8, 4, 0)
WASM_EXTEND(wasm_i32x4_extend_high_i16x8_s, s32x4, s16x8, 4, 4)
WASM_EXTEND(wasm_i32x4_extend_low_i16x8_u, u32x4, u16x8, 4, 0)
WASM_EXTEND(wasm_i32x4_extend_high_i16x8_u, u32x4, u16x8, 4, 4)
WASM_EXTEND(wasm_i64x2_extend_low_i32x4_s, s64x2, s32x4, 2, 0)
WASM_EXTEND(wasm_i64x2_extend_high_i32x4_s, s64x2, s32x4, 2, 2)
WASM_EXTEND(wasm_i64x2_extend_low_i32x4_u, u64x2, u32x4, 2, 0)
WASM_EXTEND(wasm_i64x2_extend_high_i32x4_u, u64x2, u32x4, 2, 2)

/* Float min/max propagate NaN and distinguish signed zeroes, exactly as the
 * scalar versions do; pmin/pmax are the "pseudo" forms, which do not. */
#define WASM_FMINMAX(NAME, FIELD, N, SCALAR)                            \
    static v128 NAME(v128 a, v128 b) {                                  \
        v128 r; int k;                                                  \
        for (k = 0; k < (N); k++) r.FIELD[k] = SCALAR(a.FIELD[k],       \
                                                      b.FIELD[k]);      \
        return r;                                                       \
    }
WASM_FMINMAX(wasm_f32x4_min, f32x4, 4, wasm_f32_min)
WASM_FMINMAX(wasm_f32x4_max, f32x4, 4, wasm_f32_max)
WASM_FMINMAX(wasm_f64x2_min, f64x2, 2, wasm_f64_min)
WASM_FMINMAX(wasm_f64x2_max, f64x2, 2, wasm_f64_max)

#define WASM_PMINMAX(NAME, FIELD, N, OP)                                \
    static v128 NAME(v128 a, v128 b) {                                  \
        v128 r; int k;                                                  \
        /* pmin(a,b) is `b OP a ? b : a` -- note the operand order, which \
         * is what makes it differ from min on NaN and on -0.0. */       \
        for (k = 0; k < (N); k++)                                       \
            r.FIELD[k] = (b.FIELD[k] OP a.FIELD[k]) ? b.FIELD[k]        \
                                                    : a.FIELD[k];       \
        return r;                                                       \
    }
WASM_PMINMAX(wasm_f32x4_pmin, f32x4, 4, <)
WASM_PMINMAX(wasm_f32x4_pmax, f32x4, 4, >)
WASM_PMINMAX(wasm_f64x2_pmin, f64x2, 2, <)
WASM_PMINMAX(wasm_f64x2_pmax, f64x2, 2, >)

/* Averaging (rounding up), dot product, and the pairwise/extending
 * multiplies -- each one shape-specific enough to write out. */
#define WASM_AVGR(NAME, FIELD, N)                                       \
    static v128 NAME(v128 a, v128 b) {                                  \
        v128 r; int k;                                                  \
        for (k = 0; k < (N); k++)                                       \
            r.FIELD[k] = (u32)((a.FIELD[k] + b.FIELD[k] + 1) / 2);      \
        return r;                                                       \
    }
WASM_AVGR(wasm_i8x16_avgr_u, u8x16, 16)
WASM_AVGR(wasm_i16x8_avgr_u, u16x8, 8)

static v128 wasm_i32x4_dot_i16x8_s(v128 a, v128 b) {
    v128 r; int k;
    for (k = 0; k < 4; k++)
        r.s32x4[k] = (s32)a.s16x8[k * 2] * (s32)b.s16x8[k * 2]
                   + (s32)a.s16x8[k * 2 + 1] * (s32)b.s16x8[k * 2 + 1];
    return r;
}

#define WASM_EXTADD(NAME, DSTF, SRCF, N)                                \
    static v128 NAME(v128 a) {                                          \
        v128 r; int k;                                                  \
        for (k = 0; k < (N); k++)                                       \
            r.DSTF[k] = a.SRCF[k * 2] + a.SRCF[k * 2 + 1];              \
        return r;                                                       \
    }
WASM_EXTADD(wasm_i16x8_extadd_pairwise_i8x16_s, s16x8, s8x16, 8)
WASM_EXTADD(wasm_i16x8_extadd_pairwise_i8x16_u, u16x8, u8x16, 8)
WASM_EXTADD(wasm_i32x4_extadd_pairwise_i16x8_s, s32x4, s16x8, 4)
WASM_EXTADD(wasm_i32x4_extadd_pairwise_i16x8_u, u32x4, u16x8, 4)

#define WASM_EXTMUL(NAME, DSTF, SRCF, N, HIGH)                          \
    static v128 NAME(v128 a, v128 b) {                                  \
        v128 r; int k;                                                  \
        for (k = 0; k < (N); k++)                                       \
            r.DSTF[k] = (a.SRCF[k + (HIGH)]) * (b.SRCF[k + (HIGH)]);    \
        return r;                                                       \
    }
WASM_EXTMUL(wasm_i16x8_extmul_low_i8x16_s, s16x8, s8x16, 8, 0)
WASM_EXTMUL(wasm_i16x8_extmul_high_i8x16_s, s16x8, s8x16, 8, 8)
WASM_EXTMUL(wasm_i16x8_extmul_low_i8x16_u, u16x8, u8x16, 8, 0)
WASM_EXTMUL(wasm_i16x8_extmul_high_i8x16_u, u16x8, u8x16, 8, 8)
WASM_EXTMUL(wasm_i32x4_extmul_low_i16x8_s, s32x4, s16x8, 4, 0)
WASM_EXTMUL(wasm_i32x4_extmul_high_i16x8_s, s32x4, s16x8, 4, 4)
WASM_EXTMUL(wasm_i32x4_extmul_low_i16x8_u, u32x4, u16x8, 4, 0)
WASM_EXTMUL(wasm_i32x4_extmul_high_i16x8_u, u32x4, u16x8, 4, 4)
WASM_EXTMUL(wasm_i64x2_extmul_low_i32x4_s, s64x2, s32x4, 2, 0)
WASM_EXTMUL(wasm_i64x2_extmul_high_i32x4_s, s64x2, s32x4, 2, 2)
WASM_EXTMUL(wasm_i64x2_extmul_low_i32x4_u, u64x2, u32x4, 2, 0)
WASM_EXTMUL(wasm_i64x2_extmul_high_i32x4_u, u64x2, u32x4, 2, 2)

static v128 wasm_i16x8_q15mulr_sat_s(v128 a, v128 b) {
    v128 r; int k;
    for (k = 0; k < 8; k++) {
        s32 t = ((s32)a.s16x8[k] * (s32)b.s16x8[k] + 0x4000) >> 15;
        if (t < -32768) t = -32768;
        if (t > 32767) t = 32767;
        r.s16x8[k] = (s16)t;
    }
    return r;
}

/* Conversions between the integer and float shapes. */
static v128 wasm_i32x4_trunc_sat_f32x4_s(v128 a) {
    v128 r; int k;
    for (k = 0; k < 4; k++)
        r.u32x4[k] = wasm_i32_trunc_sat_f32_s(a.f32x4[k]);
    return r;
}
static v128 wasm_i32x4_trunc_sat_f32x4_u(v128 a) {
    v128 r; int k;
    for (k = 0; k < 4; k++)
        r.u32x4[k] = wasm_i32_trunc_sat_f32_u(a.f32x4[k]);
    return r;
}
static v128 wasm_i32x4_trunc_sat_f64x2_s_zero(v128 a) {
    v128 r = wasm_v128_zero(); int k;
    for (k = 0; k < 2; k++)
        r.u32x4[k] = wasm_i32_trunc_sat_f64_s(a.f64x2[k]);
    return r;
}
static v128 wasm_i32x4_trunc_sat_f64x2_u_zero(v128 a) {
    v128 r = wasm_v128_zero(); int k;
    for (k = 0; k < 2; k++)
        r.u32x4[k] = wasm_i32_trunc_sat_f64_u(a.f64x2[k]);
    return r;
}
static v128 wasm_f32x4_convert_i32x4_s(v128 a) {
    v128 r; int k;
    for (k = 0; k < 4; k++) r.f32x4[k] = (f32)a.s32x4[k];
    return r;
}
static v128 wasm_f32x4_convert_i32x4_u(v128 a) {
    v128 r; int k;
    for (k = 0; k < 4; k++) r.f32x4[k] = (f32)a.u32x4[k];
    return r;
}
static v128 wasm_f64x2_convert_low_i32x4_s(v128 a) {
    v128 r; int k;
    for (k = 0; k < 2; k++) r.f64x2[k] = (f64)a.s32x4[k];
    return r;
}
static v128 wasm_f64x2_convert_low_i32x4_u(v128 a) {
    v128 r; int k;
    for (k = 0; k < 2; k++) r.f64x2[k] = (f64)a.u32x4[k];
    return r;
}
static v128 wasm_f32x4_demote_f64x2_zero(v128 a) {
    v128 r = wasm_v128_zero(); int k;
    for (k = 0; k < 2; k++) r.f32x4[k] = (f32)a.f64x2[k];
    return r;
}
static v128 wasm_f64x2_promote_low_f32x4(v128 a) {
    v128 r; int k;
    for (k = 0; k < 2; k++) r.f64x2[k] = (f64)a.f32x4[k];
    return r;
}

static v128 wasm_i8x16_popcnt(v128 a) {
    v128 r; int k;
    for (k = 0; k < 16; k++) r.u8x16[k] = (u8)wasm_i32_popcnt(a.u8x16[k]);
    return r;
}

#endif /* WASM2C_RT_SIMD_H */
